/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the MergePatchSetInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MergePatchSetInput{}

// MergePatchSetInput struct for MergePatchSetInput
type MergePatchSetInput struct {
	// The new subject for the change, if not specified, will reuse the current patch set's subject
	Subject *string `json:"subject,omitempty"`
	// Use the current patch set's first parent as the merge tip when set to true.
	InheritParent *bool `json:"inherit_parent,omitempty"`
	// A \\{change-id\\} that identifies a change. When inherit_parent is false, the merge tip will be the current patch set of the base_change if it's set. Otherwise, the current branch tip of the destination branch will be used.
	BaseChange *string `json:"base_change,omitempty"`
	// The detail of the source commit for merge as a MergeInput entity.
	Merge *MergeInput `json:"merge,omitempty"`
	// The author of the commit to create. Must be an AccountInput entity with at least the name and email fields set. The caller needs \"Forge Author\" permission when using this field. This field does not affect the owner or the committer of the change, which will continue to use the identity of the caller.
	Author *AccountInput `json:"author,omitempty"`
	// Map with key-value pairs that are forwarded as options to the commit validation listeners (e.g. can be used to skip certain validations). Which validation options are supported depends on the installed commit validation listeners.
	ValidationOptions map[string]string `json:"validation_options,omitempty"`
}

// NewMergePatchSetInput instantiates a new MergePatchSetInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMergePatchSetInput() *MergePatchSetInput {
	this := MergePatchSetInput{}
	return &this
}

// NewMergePatchSetInputWithDefaults instantiates a new MergePatchSetInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMergePatchSetInputWithDefaults() *MergePatchSetInput {
	this := MergePatchSetInput{}
	return &this
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *MergePatchSetInput) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergePatchSetInput) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *MergePatchSetInput) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *MergePatchSetInput) SetSubject(v string) {
	o.Subject = &v
}

// GetInheritParent returns the InheritParent field value if set, zero value otherwise.
func (o *MergePatchSetInput) GetInheritParent() bool {
	if o == nil || IsNil(o.InheritParent) {
		var ret bool
		return ret
	}
	return *o.InheritParent
}

// GetInheritParentOk returns a tuple with the InheritParent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergePatchSetInput) GetInheritParentOk() (*bool, bool) {
	if o == nil || IsNil(o.InheritParent) {
		return nil, false
	}
	return o.InheritParent, true
}

// HasInheritParent returns a boolean if a field has been set.
func (o *MergePatchSetInput) HasInheritParent() bool {
	if o != nil && !IsNil(o.InheritParent) {
		return true
	}

	return false
}

// SetInheritParent gets a reference to the given bool and assigns it to the InheritParent field.
func (o *MergePatchSetInput) SetInheritParent(v bool) {
	o.InheritParent = &v
}

// GetBaseChange returns the BaseChange field value if set, zero value otherwise.
func (o *MergePatchSetInput) GetBaseChange() string {
	if o == nil || IsNil(o.BaseChange) {
		var ret string
		return ret
	}
	return *o.BaseChange
}

// GetBaseChangeOk returns a tuple with the BaseChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergePatchSetInput) GetBaseChangeOk() (*string, bool) {
	if o == nil || IsNil(o.BaseChange) {
		return nil, false
	}
	return o.BaseChange, true
}

// HasBaseChange returns a boolean if a field has been set.
func (o *MergePatchSetInput) HasBaseChange() bool {
	if o != nil && !IsNil(o.BaseChange) {
		return true
	}

	return false
}

// SetBaseChange gets a reference to the given string and assigns it to the BaseChange field.
func (o *MergePatchSetInput) SetBaseChange(v string) {
	o.BaseChange = &v
}

// GetMerge returns the Merge field value if set, zero value otherwise.
func (o *MergePatchSetInput) GetMerge() MergeInput {
	if o == nil || IsNil(o.Merge) {
		var ret MergeInput
		return ret
	}
	return *o.Merge
}

// GetMergeOk returns a tuple with the Merge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergePatchSetInput) GetMergeOk() (*MergeInput, bool) {
	if o == nil || IsNil(o.Merge) {
		return nil, false
	}
	return o.Merge, true
}

// HasMerge returns a boolean if a field has been set.
func (o *MergePatchSetInput) HasMerge() bool {
	if o != nil && !IsNil(o.Merge) {
		return true
	}

	return false
}

// SetMerge gets a reference to the given MergeInput and assigns it to the Merge field.
func (o *MergePatchSetInput) SetMerge(v MergeInput) {
	o.Merge = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *MergePatchSetInput) GetAuthor() AccountInput {
	if o == nil || IsNil(o.Author) {
		var ret AccountInput
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergePatchSetInput) GetAuthorOk() (*AccountInput, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *MergePatchSetInput) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given AccountInput and assigns it to the Author field.
func (o *MergePatchSetInput) SetAuthor(v AccountInput) {
	o.Author = &v
}

// GetValidationOptions returns the ValidationOptions field value if set, zero value otherwise.
func (o *MergePatchSetInput) GetValidationOptions() map[string]string {
	if o == nil || IsNil(o.ValidationOptions) {
		var ret map[string]string
		return ret
	}
	return o.ValidationOptions
}

// GetValidationOptionsOk returns a tuple with the ValidationOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergePatchSetInput) GetValidationOptionsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.ValidationOptions) {
		return map[string]string{}, false
	}
	return o.ValidationOptions, true
}

// HasValidationOptions returns a boolean if a field has been set.
func (o *MergePatchSetInput) HasValidationOptions() bool {
	if o != nil && !IsNil(o.ValidationOptions) {
		return true
	}

	return false
}

// SetValidationOptions gets a reference to the given map[string]string and assigns it to the ValidationOptions field.
func (o *MergePatchSetInput) SetValidationOptions(v map[string]string) {
	o.ValidationOptions = v
}

func (o MergePatchSetInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MergePatchSetInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.InheritParent) {
		toSerialize["inherit_parent"] = o.InheritParent
	}
	if !IsNil(o.BaseChange) {
		toSerialize["base_change"] = o.BaseChange
	}
	if !IsNil(o.Merge) {
		toSerialize["merge"] = o.Merge
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.ValidationOptions) {
		toSerialize["validation_options"] = o.ValidationOptions
	}
	return toSerialize, nil
}

type NullableMergePatchSetInput struct {
	value *MergePatchSetInput
	isSet bool
}

func (v NullableMergePatchSetInput) Get() *MergePatchSetInput {
	return v.value
}

func (v *NullableMergePatchSetInput) Set(val *MergePatchSetInput) {
	v.value = val
	v.isSet = true
}

func (v NullableMergePatchSetInput) IsSet() bool {
	return v.isSet
}

func (v *NullableMergePatchSetInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMergePatchSetInput(val *MergePatchSetInput) *NullableMergePatchSetInput {
	return &NullableMergePatchSetInput{value: val, isSet: true}
}

func (v NullableMergePatchSetInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMergePatchSetInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


