/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
	"fmt"
)

// ChangeKind the model 'ChangeKind'
type ChangeKind string

// List of ChangeKind
const (
	CHANGEKIND_REWORK ChangeKind = "REWORK"
	CHANGEKIND_TRIVIAL_REBASE ChangeKind = "TRIVIAL_REBASE"
	CHANGEKIND_TRIVIAL_REBASE_WITH_MESSAGE_UPDATE ChangeKind = "TRIVIAL_REBASE_WITH_MESSAGE_UPDATE"
	CHANGEKIND_MERGE_FIRST_PARENT_UPDATE ChangeKind = "MERGE_FIRST_PARENT_UPDATE"
	CHANGEKIND_NO_CODE_CHANGE ChangeKind = "NO_CODE_CHANGE"
	CHANGEKIND_NO_CHANGE ChangeKind = "NO_CHANGE"
)

// All allowed values of ChangeKind enum
var AllowedChangeKindEnumValues = []ChangeKind{
	"REWORK",
	"TRIVIAL_REBASE",
	"TRIVIAL_REBASE_WITH_MESSAGE_UPDATE",
	"MERGE_FIRST_PARENT_UPDATE",
	"NO_CODE_CHANGE",
	"NO_CHANGE",
}

func (v *ChangeKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ChangeKind(value)
	for _, existing := range AllowedChangeKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ChangeKind", value)
}

// NewChangeKindFromValue returns a pointer to a valid ChangeKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewChangeKindFromValue(v string) (*ChangeKind, error) {
	ev := ChangeKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ChangeKind: valid values are %v", v, AllowedChangeKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ChangeKind) IsValid() bool {
	for _, existing := range AllowedChangeKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ChangeKind value
func (v ChangeKind) Ptr() *ChangeKind {
	return &v
}

type NullableChangeKind struct {
	value *ChangeKind
	isSet bool
}

func (v NullableChangeKind) Get() *ChangeKind {
	return v.value
}

func (v *NullableChangeKind) Set(val *ChangeKind) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeKind) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeKind(val *ChangeKind) *NullableChangeKind {
	return &NullableChangeKind{value: val, isSet: true}
}

func (v NullableChangeKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

