/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
	"fmt"
)

// IntraLineStatus the model 'IntraLineStatus'
type IntraLineStatus string

// List of IntraLineStatus
const (
	INTRALINESTATUS_OK IntraLineStatus = "OK"
	INTRALINESTATUS_TIMEOUT IntraLineStatus = "TIMEOUT"
	INTRALINESTATUS_FAILURE IntraLineStatus = "FAILURE"
)

// All allowed values of IntraLineStatus enum
var AllowedIntraLineStatusEnumValues = []IntraLineStatus{
	"OK",
	"TIMEOUT",
	"FAILURE",
}

func (v *IntraLineStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IntraLineStatus(value)
	for _, existing := range AllowedIntraLineStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IntraLineStatus", value)
}

// NewIntraLineStatusFromValue returns a pointer to a valid IntraLineStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIntraLineStatusFromValue(v string) (*IntraLineStatus, error) {
	ev := IntraLineStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IntraLineStatus: valid values are %v", v, AllowedIntraLineStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IntraLineStatus) IsValid() bool {
	for _, existing := range AllowedIntraLineStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IntraLineStatus value
func (v IntraLineStatus) Ptr() *IntraLineStatus {
	return &v
}

type NullableIntraLineStatus struct {
	value *IntraLineStatus
	isSet bool
}

func (v NullableIntraLineStatus) Get() *IntraLineStatus {
	return v.value
}

func (v *NullableIntraLineStatus) Set(val *IntraLineStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraLineStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraLineStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraLineStatus(val *IntraLineStatus) *NullableIntraLineStatus {
	return &NullableIntraLineStatus{value: val, isSet: true}
}

func (v NullableIntraLineStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraLineStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

