/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ConfigInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigInput{}

// ConfigInput struct for ConfigInput
type ConfigInput struct {
	Description *string `json:"description,omitempty"`
	UseContributorAgreements *InheritableBoolean `json:"use_contributor_agreements,omitempty"`
	UseContentMerge *InheritableBoolean `json:"use_content_merge,omitempty"`
	UseSignedOffBy *InheritableBoolean `json:"use_signed_off_by,omitempty"`
	CreateNewChangeForAllNotInTarget *InheritableBoolean `json:"create_new_change_for_all_not_in_target,omitempty"`
	RequireChangeId *InheritableBoolean `json:"require_change_id,omitempty"`
	EnableSignedPush *InheritableBoolean `json:"enable_signed_push,omitempty"`
	RequireSignedPush *InheritableBoolean `json:"require_signed_push,omitempty"`
	RejectImplicitMerges *InheritableBoolean `json:"reject_implicit_merges,omitempty"`
	PrivateByDefault *InheritableBoolean `json:"private_by_default,omitempty"`
	WorkInProgressByDefault *InheritableBoolean `json:"work_in_progress_by_default,omitempty"`
	EnableReviewerByEmail *InheritableBoolean `json:"enable_reviewer_by_email,omitempty"`
	MatchAuthorToCommitterDate *InheritableBoolean `json:"match_author_to_committer_date,omitempty"`
	RejectEmptyCommit *InheritableBoolean `json:"reject_empty_commit,omitempty"`
	SkipAddingAuthorAndCommitterAsReviewers *InheritableBoolean `json:"skip_adding_author_and_committer_as_reviewers,omitempty"`
	MaxObjectSizeLimit *string `json:"max_object_size_limit,omitempty"`
	SubmitType *SubmitType `json:"submit_type,omitempty"`
	State *ProjectState `json:"state,omitempty"`
	PluginConfigValues map[string]map[string]ConfigValue `json:"plugin_config_values,omitempty"`
	CommentLinks map[string]CommentLinkInput `json:"comment_links,omitempty"`
	CommitMessage *string `json:"commit_message,omitempty"`
}

// NewConfigInput instantiates a new ConfigInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigInput() *ConfigInput {
	this := ConfigInput{}
	return &this
}

// NewConfigInputWithDefaults instantiates a new ConfigInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigInputWithDefaults() *ConfigInput {
	this := ConfigInput{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ConfigInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ConfigInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ConfigInput) SetDescription(v string) {
	o.Description = &v
}

// GetUseContributorAgreements returns the UseContributorAgreements field value if set, zero value otherwise.
func (o *ConfigInput) GetUseContributorAgreements() InheritableBoolean {
	if o == nil || IsNil(o.UseContributorAgreements) {
		var ret InheritableBoolean
		return ret
	}
	return *o.UseContributorAgreements
}

// GetUseContributorAgreementsOk returns a tuple with the UseContributorAgreements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetUseContributorAgreementsOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.UseContributorAgreements) {
		return nil, false
	}
	return o.UseContributorAgreements, true
}

// HasUseContributorAgreements returns a boolean if a field has been set.
func (o *ConfigInput) HasUseContributorAgreements() bool {
	if o != nil && !IsNil(o.UseContributorAgreements) {
		return true
	}

	return false
}

// SetUseContributorAgreements gets a reference to the given InheritableBoolean and assigns it to the UseContributorAgreements field.
func (o *ConfigInput) SetUseContributorAgreements(v InheritableBoolean) {
	o.UseContributorAgreements = &v
}

// GetUseContentMerge returns the UseContentMerge field value if set, zero value otherwise.
func (o *ConfigInput) GetUseContentMerge() InheritableBoolean {
	if o == nil || IsNil(o.UseContentMerge) {
		var ret InheritableBoolean
		return ret
	}
	return *o.UseContentMerge
}

// GetUseContentMergeOk returns a tuple with the UseContentMerge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetUseContentMergeOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.UseContentMerge) {
		return nil, false
	}
	return o.UseContentMerge, true
}

// HasUseContentMerge returns a boolean if a field has been set.
func (o *ConfigInput) HasUseContentMerge() bool {
	if o != nil && !IsNil(o.UseContentMerge) {
		return true
	}

	return false
}

// SetUseContentMerge gets a reference to the given InheritableBoolean and assigns it to the UseContentMerge field.
func (o *ConfigInput) SetUseContentMerge(v InheritableBoolean) {
	o.UseContentMerge = &v
}

// GetUseSignedOffBy returns the UseSignedOffBy field value if set, zero value otherwise.
func (o *ConfigInput) GetUseSignedOffBy() InheritableBoolean {
	if o == nil || IsNil(o.UseSignedOffBy) {
		var ret InheritableBoolean
		return ret
	}
	return *o.UseSignedOffBy
}

// GetUseSignedOffByOk returns a tuple with the UseSignedOffBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetUseSignedOffByOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.UseSignedOffBy) {
		return nil, false
	}
	return o.UseSignedOffBy, true
}

// HasUseSignedOffBy returns a boolean if a field has been set.
func (o *ConfigInput) HasUseSignedOffBy() bool {
	if o != nil && !IsNil(o.UseSignedOffBy) {
		return true
	}

	return false
}

// SetUseSignedOffBy gets a reference to the given InheritableBoolean and assigns it to the UseSignedOffBy field.
func (o *ConfigInput) SetUseSignedOffBy(v InheritableBoolean) {
	o.UseSignedOffBy = &v
}

// GetCreateNewChangeForAllNotInTarget returns the CreateNewChangeForAllNotInTarget field value if set, zero value otherwise.
func (o *ConfigInput) GetCreateNewChangeForAllNotInTarget() InheritableBoolean {
	if o == nil || IsNil(o.CreateNewChangeForAllNotInTarget) {
		var ret InheritableBoolean
		return ret
	}
	return *o.CreateNewChangeForAllNotInTarget
}

// GetCreateNewChangeForAllNotInTargetOk returns a tuple with the CreateNewChangeForAllNotInTarget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetCreateNewChangeForAllNotInTargetOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.CreateNewChangeForAllNotInTarget) {
		return nil, false
	}
	return o.CreateNewChangeForAllNotInTarget, true
}

// HasCreateNewChangeForAllNotInTarget returns a boolean if a field has been set.
func (o *ConfigInput) HasCreateNewChangeForAllNotInTarget() bool {
	if o != nil && !IsNil(o.CreateNewChangeForAllNotInTarget) {
		return true
	}

	return false
}

// SetCreateNewChangeForAllNotInTarget gets a reference to the given InheritableBoolean and assigns it to the CreateNewChangeForAllNotInTarget field.
func (o *ConfigInput) SetCreateNewChangeForAllNotInTarget(v InheritableBoolean) {
	o.CreateNewChangeForAllNotInTarget = &v
}

// GetRequireChangeId returns the RequireChangeId field value if set, zero value otherwise.
func (o *ConfigInput) GetRequireChangeId() InheritableBoolean {
	if o == nil || IsNil(o.RequireChangeId) {
		var ret InheritableBoolean
		return ret
	}
	return *o.RequireChangeId
}

// GetRequireChangeIdOk returns a tuple with the RequireChangeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetRequireChangeIdOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.RequireChangeId) {
		return nil, false
	}
	return o.RequireChangeId, true
}

// HasRequireChangeId returns a boolean if a field has been set.
func (o *ConfigInput) HasRequireChangeId() bool {
	if o != nil && !IsNil(o.RequireChangeId) {
		return true
	}

	return false
}

// SetRequireChangeId gets a reference to the given InheritableBoolean and assigns it to the RequireChangeId field.
func (o *ConfigInput) SetRequireChangeId(v InheritableBoolean) {
	o.RequireChangeId = &v
}

// GetEnableSignedPush returns the EnableSignedPush field value if set, zero value otherwise.
func (o *ConfigInput) GetEnableSignedPush() InheritableBoolean {
	if o == nil || IsNil(o.EnableSignedPush) {
		var ret InheritableBoolean
		return ret
	}
	return *o.EnableSignedPush
}

// GetEnableSignedPushOk returns a tuple with the EnableSignedPush field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetEnableSignedPushOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.EnableSignedPush) {
		return nil, false
	}
	return o.EnableSignedPush, true
}

// HasEnableSignedPush returns a boolean if a field has been set.
func (o *ConfigInput) HasEnableSignedPush() bool {
	if o != nil && !IsNil(o.EnableSignedPush) {
		return true
	}

	return false
}

// SetEnableSignedPush gets a reference to the given InheritableBoolean and assigns it to the EnableSignedPush field.
func (o *ConfigInput) SetEnableSignedPush(v InheritableBoolean) {
	o.EnableSignedPush = &v
}

// GetRequireSignedPush returns the RequireSignedPush field value if set, zero value otherwise.
func (o *ConfigInput) GetRequireSignedPush() InheritableBoolean {
	if o == nil || IsNil(o.RequireSignedPush) {
		var ret InheritableBoolean
		return ret
	}
	return *o.RequireSignedPush
}

// GetRequireSignedPushOk returns a tuple with the RequireSignedPush field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetRequireSignedPushOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.RequireSignedPush) {
		return nil, false
	}
	return o.RequireSignedPush, true
}

// HasRequireSignedPush returns a boolean if a field has been set.
func (o *ConfigInput) HasRequireSignedPush() bool {
	if o != nil && !IsNil(o.RequireSignedPush) {
		return true
	}

	return false
}

// SetRequireSignedPush gets a reference to the given InheritableBoolean and assigns it to the RequireSignedPush field.
func (o *ConfigInput) SetRequireSignedPush(v InheritableBoolean) {
	o.RequireSignedPush = &v
}

// GetRejectImplicitMerges returns the RejectImplicitMerges field value if set, zero value otherwise.
func (o *ConfigInput) GetRejectImplicitMerges() InheritableBoolean {
	if o == nil || IsNil(o.RejectImplicitMerges) {
		var ret InheritableBoolean
		return ret
	}
	return *o.RejectImplicitMerges
}

// GetRejectImplicitMergesOk returns a tuple with the RejectImplicitMerges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetRejectImplicitMergesOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.RejectImplicitMerges) {
		return nil, false
	}
	return o.RejectImplicitMerges, true
}

// HasRejectImplicitMerges returns a boolean if a field has been set.
func (o *ConfigInput) HasRejectImplicitMerges() bool {
	if o != nil && !IsNil(o.RejectImplicitMerges) {
		return true
	}

	return false
}

// SetRejectImplicitMerges gets a reference to the given InheritableBoolean and assigns it to the RejectImplicitMerges field.
func (o *ConfigInput) SetRejectImplicitMerges(v InheritableBoolean) {
	o.RejectImplicitMerges = &v
}

// GetPrivateByDefault returns the PrivateByDefault field value if set, zero value otherwise.
func (o *ConfigInput) GetPrivateByDefault() InheritableBoolean {
	if o == nil || IsNil(o.PrivateByDefault) {
		var ret InheritableBoolean
		return ret
	}
	return *o.PrivateByDefault
}

// GetPrivateByDefaultOk returns a tuple with the PrivateByDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetPrivateByDefaultOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.PrivateByDefault) {
		return nil, false
	}
	return o.PrivateByDefault, true
}

// HasPrivateByDefault returns a boolean if a field has been set.
func (o *ConfigInput) HasPrivateByDefault() bool {
	if o != nil && !IsNil(o.PrivateByDefault) {
		return true
	}

	return false
}

// SetPrivateByDefault gets a reference to the given InheritableBoolean and assigns it to the PrivateByDefault field.
func (o *ConfigInput) SetPrivateByDefault(v InheritableBoolean) {
	o.PrivateByDefault = &v
}

// GetWorkInProgressByDefault returns the WorkInProgressByDefault field value if set, zero value otherwise.
func (o *ConfigInput) GetWorkInProgressByDefault() InheritableBoolean {
	if o == nil || IsNil(o.WorkInProgressByDefault) {
		var ret InheritableBoolean
		return ret
	}
	return *o.WorkInProgressByDefault
}

// GetWorkInProgressByDefaultOk returns a tuple with the WorkInProgressByDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetWorkInProgressByDefaultOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.WorkInProgressByDefault) {
		return nil, false
	}
	return o.WorkInProgressByDefault, true
}

// HasWorkInProgressByDefault returns a boolean if a field has been set.
func (o *ConfigInput) HasWorkInProgressByDefault() bool {
	if o != nil && !IsNil(o.WorkInProgressByDefault) {
		return true
	}

	return false
}

// SetWorkInProgressByDefault gets a reference to the given InheritableBoolean and assigns it to the WorkInProgressByDefault field.
func (o *ConfigInput) SetWorkInProgressByDefault(v InheritableBoolean) {
	o.WorkInProgressByDefault = &v
}

// GetEnableReviewerByEmail returns the EnableReviewerByEmail field value if set, zero value otherwise.
func (o *ConfigInput) GetEnableReviewerByEmail() InheritableBoolean {
	if o == nil || IsNil(o.EnableReviewerByEmail) {
		var ret InheritableBoolean
		return ret
	}
	return *o.EnableReviewerByEmail
}

// GetEnableReviewerByEmailOk returns a tuple with the EnableReviewerByEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetEnableReviewerByEmailOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.EnableReviewerByEmail) {
		return nil, false
	}
	return o.EnableReviewerByEmail, true
}

// HasEnableReviewerByEmail returns a boolean if a field has been set.
func (o *ConfigInput) HasEnableReviewerByEmail() bool {
	if o != nil && !IsNil(o.EnableReviewerByEmail) {
		return true
	}

	return false
}

// SetEnableReviewerByEmail gets a reference to the given InheritableBoolean and assigns it to the EnableReviewerByEmail field.
func (o *ConfigInput) SetEnableReviewerByEmail(v InheritableBoolean) {
	o.EnableReviewerByEmail = &v
}

// GetMatchAuthorToCommitterDate returns the MatchAuthorToCommitterDate field value if set, zero value otherwise.
func (o *ConfigInput) GetMatchAuthorToCommitterDate() InheritableBoolean {
	if o == nil || IsNil(o.MatchAuthorToCommitterDate) {
		var ret InheritableBoolean
		return ret
	}
	return *o.MatchAuthorToCommitterDate
}

// GetMatchAuthorToCommitterDateOk returns a tuple with the MatchAuthorToCommitterDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetMatchAuthorToCommitterDateOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.MatchAuthorToCommitterDate) {
		return nil, false
	}
	return o.MatchAuthorToCommitterDate, true
}

// HasMatchAuthorToCommitterDate returns a boolean if a field has been set.
func (o *ConfigInput) HasMatchAuthorToCommitterDate() bool {
	if o != nil && !IsNil(o.MatchAuthorToCommitterDate) {
		return true
	}

	return false
}

// SetMatchAuthorToCommitterDate gets a reference to the given InheritableBoolean and assigns it to the MatchAuthorToCommitterDate field.
func (o *ConfigInput) SetMatchAuthorToCommitterDate(v InheritableBoolean) {
	o.MatchAuthorToCommitterDate = &v
}

// GetRejectEmptyCommit returns the RejectEmptyCommit field value if set, zero value otherwise.
func (o *ConfigInput) GetRejectEmptyCommit() InheritableBoolean {
	if o == nil || IsNil(o.RejectEmptyCommit) {
		var ret InheritableBoolean
		return ret
	}
	return *o.RejectEmptyCommit
}

// GetRejectEmptyCommitOk returns a tuple with the RejectEmptyCommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetRejectEmptyCommitOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.RejectEmptyCommit) {
		return nil, false
	}
	return o.RejectEmptyCommit, true
}

// HasRejectEmptyCommit returns a boolean if a field has been set.
func (o *ConfigInput) HasRejectEmptyCommit() bool {
	if o != nil && !IsNil(o.RejectEmptyCommit) {
		return true
	}

	return false
}

// SetRejectEmptyCommit gets a reference to the given InheritableBoolean and assigns it to the RejectEmptyCommit field.
func (o *ConfigInput) SetRejectEmptyCommit(v InheritableBoolean) {
	o.RejectEmptyCommit = &v
}

// GetSkipAddingAuthorAndCommitterAsReviewers returns the SkipAddingAuthorAndCommitterAsReviewers field value if set, zero value otherwise.
func (o *ConfigInput) GetSkipAddingAuthorAndCommitterAsReviewers() InheritableBoolean {
	if o == nil || IsNil(o.SkipAddingAuthorAndCommitterAsReviewers) {
		var ret InheritableBoolean
		return ret
	}
	return *o.SkipAddingAuthorAndCommitterAsReviewers
}

// GetSkipAddingAuthorAndCommitterAsReviewersOk returns a tuple with the SkipAddingAuthorAndCommitterAsReviewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetSkipAddingAuthorAndCommitterAsReviewersOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.SkipAddingAuthorAndCommitterAsReviewers) {
		return nil, false
	}
	return o.SkipAddingAuthorAndCommitterAsReviewers, true
}

// HasSkipAddingAuthorAndCommitterAsReviewers returns a boolean if a field has been set.
func (o *ConfigInput) HasSkipAddingAuthorAndCommitterAsReviewers() bool {
	if o != nil && !IsNil(o.SkipAddingAuthorAndCommitterAsReviewers) {
		return true
	}

	return false
}

// SetSkipAddingAuthorAndCommitterAsReviewers gets a reference to the given InheritableBoolean and assigns it to the SkipAddingAuthorAndCommitterAsReviewers field.
func (o *ConfigInput) SetSkipAddingAuthorAndCommitterAsReviewers(v InheritableBoolean) {
	o.SkipAddingAuthorAndCommitterAsReviewers = &v
}

// GetMaxObjectSizeLimit returns the MaxObjectSizeLimit field value if set, zero value otherwise.
func (o *ConfigInput) GetMaxObjectSizeLimit() string {
	if o == nil || IsNil(o.MaxObjectSizeLimit) {
		var ret string
		return ret
	}
	return *o.MaxObjectSizeLimit
}

// GetMaxObjectSizeLimitOk returns a tuple with the MaxObjectSizeLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetMaxObjectSizeLimitOk() (*string, bool) {
	if o == nil || IsNil(o.MaxObjectSizeLimit) {
		return nil, false
	}
	return o.MaxObjectSizeLimit, true
}

// HasMaxObjectSizeLimit returns a boolean if a field has been set.
func (o *ConfigInput) HasMaxObjectSizeLimit() bool {
	if o != nil && !IsNil(o.MaxObjectSizeLimit) {
		return true
	}

	return false
}

// SetMaxObjectSizeLimit gets a reference to the given string and assigns it to the MaxObjectSizeLimit field.
func (o *ConfigInput) SetMaxObjectSizeLimit(v string) {
	o.MaxObjectSizeLimit = &v
}

// GetSubmitType returns the SubmitType field value if set, zero value otherwise.
func (o *ConfigInput) GetSubmitType() SubmitType {
	if o == nil || IsNil(o.SubmitType) {
		var ret SubmitType
		return ret
	}
	return *o.SubmitType
}

// GetSubmitTypeOk returns a tuple with the SubmitType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetSubmitTypeOk() (*SubmitType, bool) {
	if o == nil || IsNil(o.SubmitType) {
		return nil, false
	}
	return o.SubmitType, true
}

// HasSubmitType returns a boolean if a field has been set.
func (o *ConfigInput) HasSubmitType() bool {
	if o != nil && !IsNil(o.SubmitType) {
		return true
	}

	return false
}

// SetSubmitType gets a reference to the given SubmitType and assigns it to the SubmitType field.
func (o *ConfigInput) SetSubmitType(v SubmitType) {
	o.SubmitType = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ConfigInput) GetState() ProjectState {
	if o == nil || IsNil(o.State) {
		var ret ProjectState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetStateOk() (*ProjectState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ConfigInput) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given ProjectState and assigns it to the State field.
func (o *ConfigInput) SetState(v ProjectState) {
	o.State = &v
}

// GetPluginConfigValues returns the PluginConfigValues field value if set, zero value otherwise.
func (o *ConfigInput) GetPluginConfigValues() map[string]map[string]ConfigValue {
	if o == nil || IsNil(o.PluginConfigValues) {
		var ret map[string]map[string]ConfigValue
		return ret
	}
	return o.PluginConfigValues
}

// GetPluginConfigValuesOk returns a tuple with the PluginConfigValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetPluginConfigValuesOk() (map[string]map[string]ConfigValue, bool) {
	if o == nil || IsNil(o.PluginConfigValues) {
		return map[string]map[string]ConfigValue{}, false
	}
	return o.PluginConfigValues, true
}

// HasPluginConfigValues returns a boolean if a field has been set.
func (o *ConfigInput) HasPluginConfigValues() bool {
	if o != nil && !IsNil(o.PluginConfigValues) {
		return true
	}

	return false
}

// SetPluginConfigValues gets a reference to the given map[string]map[string]ConfigValue and assigns it to the PluginConfigValues field.
func (o *ConfigInput) SetPluginConfigValues(v map[string]map[string]ConfigValue) {
	o.PluginConfigValues = v
}

// GetCommentLinks returns the CommentLinks field value if set, zero value otherwise.
func (o *ConfigInput) GetCommentLinks() map[string]CommentLinkInput {
	if o == nil || IsNil(o.CommentLinks) {
		var ret map[string]CommentLinkInput
		return ret
	}
	return o.CommentLinks
}

// GetCommentLinksOk returns a tuple with the CommentLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetCommentLinksOk() (map[string]CommentLinkInput, bool) {
	if o == nil || IsNil(o.CommentLinks) {
		return map[string]CommentLinkInput{}, false
	}
	return o.CommentLinks, true
}

// HasCommentLinks returns a boolean if a field has been set.
func (o *ConfigInput) HasCommentLinks() bool {
	if o != nil && !IsNil(o.CommentLinks) {
		return true
	}

	return false
}

// SetCommentLinks gets a reference to the given map[string]CommentLinkInput and assigns it to the CommentLinks field.
func (o *ConfigInput) SetCommentLinks(v map[string]CommentLinkInput) {
	o.CommentLinks = v
}

// GetCommitMessage returns the CommitMessage field value if set, zero value otherwise.
func (o *ConfigInput) GetCommitMessage() string {
	if o == nil || IsNil(o.CommitMessage) {
		var ret string
		return ret
	}
	return *o.CommitMessage
}

// GetCommitMessageOk returns a tuple with the CommitMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigInput) GetCommitMessageOk() (*string, bool) {
	if o == nil || IsNil(o.CommitMessage) {
		return nil, false
	}
	return o.CommitMessage, true
}

// HasCommitMessage returns a boolean if a field has been set.
func (o *ConfigInput) HasCommitMessage() bool {
	if o != nil && !IsNil(o.CommitMessage) {
		return true
	}

	return false
}

// SetCommitMessage gets a reference to the given string and assigns it to the CommitMessage field.
func (o *ConfigInput) SetCommitMessage(v string) {
	o.CommitMessage = &v
}

func (o ConfigInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.UseContributorAgreements) {
		toSerialize["use_contributor_agreements"] = o.UseContributorAgreements
	}
	if !IsNil(o.UseContentMerge) {
		toSerialize["use_content_merge"] = o.UseContentMerge
	}
	if !IsNil(o.UseSignedOffBy) {
		toSerialize["use_signed_off_by"] = o.UseSignedOffBy
	}
	if !IsNil(o.CreateNewChangeForAllNotInTarget) {
		toSerialize["create_new_change_for_all_not_in_target"] = o.CreateNewChangeForAllNotInTarget
	}
	if !IsNil(o.RequireChangeId) {
		toSerialize["require_change_id"] = o.RequireChangeId
	}
	if !IsNil(o.EnableSignedPush) {
		toSerialize["enable_signed_push"] = o.EnableSignedPush
	}
	if !IsNil(o.RequireSignedPush) {
		toSerialize["require_signed_push"] = o.RequireSignedPush
	}
	if !IsNil(o.RejectImplicitMerges) {
		toSerialize["reject_implicit_merges"] = o.RejectImplicitMerges
	}
	if !IsNil(o.PrivateByDefault) {
		toSerialize["private_by_default"] = o.PrivateByDefault
	}
	if !IsNil(o.WorkInProgressByDefault) {
		toSerialize["work_in_progress_by_default"] = o.WorkInProgressByDefault
	}
	if !IsNil(o.EnableReviewerByEmail) {
		toSerialize["enable_reviewer_by_email"] = o.EnableReviewerByEmail
	}
	if !IsNil(o.MatchAuthorToCommitterDate) {
		toSerialize["match_author_to_committer_date"] = o.MatchAuthorToCommitterDate
	}
	if !IsNil(o.RejectEmptyCommit) {
		toSerialize["reject_empty_commit"] = o.RejectEmptyCommit
	}
	if !IsNil(o.SkipAddingAuthorAndCommitterAsReviewers) {
		toSerialize["skip_adding_author_and_committer_as_reviewers"] = o.SkipAddingAuthorAndCommitterAsReviewers
	}
	if !IsNil(o.MaxObjectSizeLimit) {
		toSerialize["max_object_size_limit"] = o.MaxObjectSizeLimit
	}
	if !IsNil(o.SubmitType) {
		toSerialize["submit_type"] = o.SubmitType
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.PluginConfigValues) {
		toSerialize["plugin_config_values"] = o.PluginConfigValues
	}
	if !IsNil(o.CommentLinks) {
		toSerialize["comment_links"] = o.CommentLinks
	}
	if !IsNil(o.CommitMessage) {
		toSerialize["commit_message"] = o.CommitMessage
	}
	return toSerialize, nil
}

type NullableConfigInput struct {
	value *ConfigInput
	isSet bool
}

func (v NullableConfigInput) Get() *ConfigInput {
	return v.value
}

func (v *NullableConfigInput) Set(val *ConfigInput) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigInput) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigInput(val *ConfigInput) *NullableConfigInput {
	return &NullableConfigInput{value: val, isSet: true}
}

func (v NullableConfigInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


