/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ProjectAccessInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAccessInput{}

// ProjectAccessInput struct for ProjectAccessInput
type ProjectAccessInput struct {
	Remove map[string]AccessSectionInfo `json:"remove,omitempty"`
	Add map[string]AccessSectionInfo `json:"add,omitempty"`
	Parent *string `json:"parent,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewProjectAccessInput instantiates a new ProjectAccessInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAccessInput() *ProjectAccessInput {
	this := ProjectAccessInput{}
	return &this
}

// NewProjectAccessInputWithDefaults instantiates a new ProjectAccessInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAccessInputWithDefaults() *ProjectAccessInput {
	this := ProjectAccessInput{}
	return &this
}

// GetRemove returns the Remove field value if set, zero value otherwise.
func (o *ProjectAccessInput) GetRemove() map[string]AccessSectionInfo {
	if o == nil || IsNil(o.Remove) {
		var ret map[string]AccessSectionInfo
		return ret
	}
	return o.Remove
}

// GetRemoveOk returns a tuple with the Remove field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInput) GetRemoveOk() (map[string]AccessSectionInfo, bool) {
	if o == nil || IsNil(o.Remove) {
		return map[string]AccessSectionInfo{}, false
	}
	return o.Remove, true
}

// HasRemove returns a boolean if a field has been set.
func (o *ProjectAccessInput) HasRemove() bool {
	if o != nil && !IsNil(o.Remove) {
		return true
	}

	return false
}

// SetRemove gets a reference to the given map[string]AccessSectionInfo and assigns it to the Remove field.
func (o *ProjectAccessInput) SetRemove(v map[string]AccessSectionInfo) {
	o.Remove = v
}

// GetAdd returns the Add field value if set, zero value otherwise.
func (o *ProjectAccessInput) GetAdd() map[string]AccessSectionInfo {
	if o == nil || IsNil(o.Add) {
		var ret map[string]AccessSectionInfo
		return ret
	}
	return o.Add
}

// GetAddOk returns a tuple with the Add field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInput) GetAddOk() (map[string]AccessSectionInfo, bool) {
	if o == nil || IsNil(o.Add) {
		return map[string]AccessSectionInfo{}, false
	}
	return o.Add, true
}

// HasAdd returns a boolean if a field has been set.
func (o *ProjectAccessInput) HasAdd() bool {
	if o != nil && !IsNil(o.Add) {
		return true
	}

	return false
}

// SetAdd gets a reference to the given map[string]AccessSectionInfo and assigns it to the Add field.
func (o *ProjectAccessInput) SetAdd(v map[string]AccessSectionInfo) {
	o.Add = v
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *ProjectAccessInput) GetParent() string {
	if o == nil || IsNil(o.Parent) {
		var ret string
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInput) GetParentOk() (*string, bool) {
	if o == nil || IsNil(o.Parent) {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *ProjectAccessInput) HasParent() bool {
	if o != nil && !IsNil(o.Parent) {
		return true
	}

	return false
}

// SetParent gets a reference to the given string and assigns it to the Parent field.
func (o *ProjectAccessInput) SetParent(v string) {
	o.Parent = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ProjectAccessInput) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInput) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ProjectAccessInput) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ProjectAccessInput) SetMessage(v string) {
	o.Message = &v
}

func (o ProjectAccessInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAccessInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Remove) {
		toSerialize["remove"] = o.Remove
	}
	if !IsNil(o.Add) {
		toSerialize["add"] = o.Add
	}
	if !IsNil(o.Parent) {
		toSerialize["parent"] = o.Parent
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableProjectAccessInput struct {
	value *ProjectAccessInput
	isSet bool
}

func (v NullableProjectAccessInput) Get() *ProjectAccessInput {
	return v.value
}

func (v *NullableProjectAccessInput) Set(val *ProjectAccessInput) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAccessInput) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAccessInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAccessInput(val *ProjectAccessInput) *NullableProjectAccessInput {
	return &NullableProjectAccessInput{value: val, isSet: true}
}

func (v NullableProjectAccessInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAccessInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


