/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the DeletedDraftCommentInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletedDraftCommentInfo{}

// DeletedDraftCommentInfo struct for DeletedDraftCommentInfo
type DeletedDraftCommentInfo struct {
	Change *ChangeInfo `json:"change,omitempty"`
	Deleted []CommentInfo `json:"deleted,omitempty"`
}

// NewDeletedDraftCommentInfo instantiates a new DeletedDraftCommentInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletedDraftCommentInfo() *DeletedDraftCommentInfo {
	this := DeletedDraftCommentInfo{}
	return &this
}

// NewDeletedDraftCommentInfoWithDefaults instantiates a new DeletedDraftCommentInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletedDraftCommentInfoWithDefaults() *DeletedDraftCommentInfo {
	this := DeletedDraftCommentInfo{}
	return &this
}

// GetChange returns the Change field value if set, zero value otherwise.
func (o *DeletedDraftCommentInfo) GetChange() ChangeInfo {
	if o == nil || IsNil(o.Change) {
		var ret ChangeInfo
		return ret
	}
	return *o.Change
}

// GetChangeOk returns a tuple with the Change field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedDraftCommentInfo) GetChangeOk() (*ChangeInfo, bool) {
	if o == nil || IsNil(o.Change) {
		return nil, false
	}
	return o.Change, true
}

// HasChange returns a boolean if a field has been set.
func (o *DeletedDraftCommentInfo) HasChange() bool {
	if o != nil && !IsNil(o.Change) {
		return true
	}

	return false
}

// SetChange gets a reference to the given ChangeInfo and assigns it to the Change field.
func (o *DeletedDraftCommentInfo) SetChange(v ChangeInfo) {
	o.Change = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *DeletedDraftCommentInfo) GetDeleted() []CommentInfo {
	if o == nil || IsNil(o.Deleted) {
		var ret []CommentInfo
		return ret
	}
	return o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletedDraftCommentInfo) GetDeletedOk() ([]CommentInfo, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *DeletedDraftCommentInfo) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given []CommentInfo and assigns it to the Deleted field.
func (o *DeletedDraftCommentInfo) SetDeleted(v []CommentInfo) {
	o.Deleted = v
}

func (o DeletedDraftCommentInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletedDraftCommentInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Change) {
		toSerialize["change"] = o.Change
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	return toSerialize, nil
}

type NullableDeletedDraftCommentInfo struct {
	value *DeletedDraftCommentInfo
	isSet bool
}

func (v NullableDeletedDraftCommentInfo) Get() *DeletedDraftCommentInfo {
	return v.value
}

func (v *NullableDeletedDraftCommentInfo) Set(val *DeletedDraftCommentInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletedDraftCommentInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletedDraftCommentInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletedDraftCommentInfo(val *DeletedDraftCommentInfo) *NullableDeletedDraftCommentInfo {
	return &NullableDeletedDraftCommentInfo{value: val, isSet: true}
}

func (v NullableDeletedDraftCommentInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletedDraftCommentInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


