/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the GetConfigServerVersion200ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetConfigServerVersion200ResponseOneOf{}

// GetConfigServerVersion200ResponseOneOf struct for GetConfigServerVersion200ResponseOneOf
type GetConfigServerVersion200ResponseOneOf struct {
	GerritVersion *string `json:"gerrit_version,omitempty"`
	NoteDbVersion *int32 `json:"note_db_version,omitempty"`
	ChangeIndexVersion *int32 `json:"change_index_version,omitempty"`
	AccountIndexVersion *int32 `json:"account_index_version,omitempty"`
	ProjectIndexVersion *int32 `json:"project_index_version,omitempty"`
	GroupIndexVersion *int32 `json:"group_index_version,omitempty"`
}

// NewGetConfigServerVersion200ResponseOneOf instantiates a new GetConfigServerVersion200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConfigServerVersion200ResponseOneOf() *GetConfigServerVersion200ResponseOneOf {
	this := GetConfigServerVersion200ResponseOneOf{}
	return &this
}

// NewGetConfigServerVersion200ResponseOneOfWithDefaults instantiates a new GetConfigServerVersion200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConfigServerVersion200ResponseOneOfWithDefaults() *GetConfigServerVersion200ResponseOneOf {
	this := GetConfigServerVersion200ResponseOneOf{}
	return &this
}

// GetGerritVersion returns the GerritVersion field value if set, zero value otherwise.
func (o *GetConfigServerVersion200ResponseOneOf) GetGerritVersion() string {
	if o == nil || IsNil(o.GerritVersion) {
		var ret string
		return ret
	}
	return *o.GerritVersion
}

// GetGerritVersionOk returns a tuple with the GerritVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConfigServerVersion200ResponseOneOf) GetGerritVersionOk() (*string, bool) {
	if o == nil || IsNil(o.GerritVersion) {
		return nil, false
	}
	return o.GerritVersion, true
}

// HasGerritVersion returns a boolean if a field has been set.
func (o *GetConfigServerVersion200ResponseOneOf) HasGerritVersion() bool {
	if o != nil && !IsNil(o.GerritVersion) {
		return true
	}

	return false
}

// SetGerritVersion gets a reference to the given string and assigns it to the GerritVersion field.
func (o *GetConfigServerVersion200ResponseOneOf) SetGerritVersion(v string) {
	o.GerritVersion = &v
}

// GetNoteDbVersion returns the NoteDbVersion field value if set, zero value otherwise.
func (o *GetConfigServerVersion200ResponseOneOf) GetNoteDbVersion() int32 {
	if o == nil || IsNil(o.NoteDbVersion) {
		var ret int32
		return ret
	}
	return *o.NoteDbVersion
}

// GetNoteDbVersionOk returns a tuple with the NoteDbVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConfigServerVersion200ResponseOneOf) GetNoteDbVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.NoteDbVersion) {
		return nil, false
	}
	return o.NoteDbVersion, true
}

// HasNoteDbVersion returns a boolean if a field has been set.
func (o *GetConfigServerVersion200ResponseOneOf) HasNoteDbVersion() bool {
	if o != nil && !IsNil(o.NoteDbVersion) {
		return true
	}

	return false
}

// SetNoteDbVersion gets a reference to the given int32 and assigns it to the NoteDbVersion field.
func (o *GetConfigServerVersion200ResponseOneOf) SetNoteDbVersion(v int32) {
	o.NoteDbVersion = &v
}

// GetChangeIndexVersion returns the ChangeIndexVersion field value if set, zero value otherwise.
func (o *GetConfigServerVersion200ResponseOneOf) GetChangeIndexVersion() int32 {
	if o == nil || IsNil(o.ChangeIndexVersion) {
		var ret int32
		return ret
	}
	return *o.ChangeIndexVersion
}

// GetChangeIndexVersionOk returns a tuple with the ChangeIndexVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConfigServerVersion200ResponseOneOf) GetChangeIndexVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.ChangeIndexVersion) {
		return nil, false
	}
	return o.ChangeIndexVersion, true
}

// HasChangeIndexVersion returns a boolean if a field has been set.
func (o *GetConfigServerVersion200ResponseOneOf) HasChangeIndexVersion() bool {
	if o != nil && !IsNil(o.ChangeIndexVersion) {
		return true
	}

	return false
}

// SetChangeIndexVersion gets a reference to the given int32 and assigns it to the ChangeIndexVersion field.
func (o *GetConfigServerVersion200ResponseOneOf) SetChangeIndexVersion(v int32) {
	o.ChangeIndexVersion = &v
}

// GetAccountIndexVersion returns the AccountIndexVersion field value if set, zero value otherwise.
func (o *GetConfigServerVersion200ResponseOneOf) GetAccountIndexVersion() int32 {
	if o == nil || IsNil(o.AccountIndexVersion) {
		var ret int32
		return ret
	}
	return *o.AccountIndexVersion
}

// GetAccountIndexVersionOk returns a tuple with the AccountIndexVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConfigServerVersion200ResponseOneOf) GetAccountIndexVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.AccountIndexVersion) {
		return nil, false
	}
	return o.AccountIndexVersion, true
}

// HasAccountIndexVersion returns a boolean if a field has been set.
func (o *GetConfigServerVersion200ResponseOneOf) HasAccountIndexVersion() bool {
	if o != nil && !IsNil(o.AccountIndexVersion) {
		return true
	}

	return false
}

// SetAccountIndexVersion gets a reference to the given int32 and assigns it to the AccountIndexVersion field.
func (o *GetConfigServerVersion200ResponseOneOf) SetAccountIndexVersion(v int32) {
	o.AccountIndexVersion = &v
}

// GetProjectIndexVersion returns the ProjectIndexVersion field value if set, zero value otherwise.
func (o *GetConfigServerVersion200ResponseOneOf) GetProjectIndexVersion() int32 {
	if o == nil || IsNil(o.ProjectIndexVersion) {
		var ret int32
		return ret
	}
	return *o.ProjectIndexVersion
}

// GetProjectIndexVersionOk returns a tuple with the ProjectIndexVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConfigServerVersion200ResponseOneOf) GetProjectIndexVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectIndexVersion) {
		return nil, false
	}
	return o.ProjectIndexVersion, true
}

// HasProjectIndexVersion returns a boolean if a field has been set.
func (o *GetConfigServerVersion200ResponseOneOf) HasProjectIndexVersion() bool {
	if o != nil && !IsNil(o.ProjectIndexVersion) {
		return true
	}

	return false
}

// SetProjectIndexVersion gets a reference to the given int32 and assigns it to the ProjectIndexVersion field.
func (o *GetConfigServerVersion200ResponseOneOf) SetProjectIndexVersion(v int32) {
	o.ProjectIndexVersion = &v
}

// GetGroupIndexVersion returns the GroupIndexVersion field value if set, zero value otherwise.
func (o *GetConfigServerVersion200ResponseOneOf) GetGroupIndexVersion() int32 {
	if o == nil || IsNil(o.GroupIndexVersion) {
		var ret int32
		return ret
	}
	return *o.GroupIndexVersion
}

// GetGroupIndexVersionOk returns a tuple with the GroupIndexVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConfigServerVersion200ResponseOneOf) GetGroupIndexVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.GroupIndexVersion) {
		return nil, false
	}
	return o.GroupIndexVersion, true
}

// HasGroupIndexVersion returns a boolean if a field has been set.
func (o *GetConfigServerVersion200ResponseOneOf) HasGroupIndexVersion() bool {
	if o != nil && !IsNil(o.GroupIndexVersion) {
		return true
	}

	return false
}

// SetGroupIndexVersion gets a reference to the given int32 and assigns it to the GroupIndexVersion field.
func (o *GetConfigServerVersion200ResponseOneOf) SetGroupIndexVersion(v int32) {
	o.GroupIndexVersion = &v
}

func (o GetConfigServerVersion200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetConfigServerVersion200ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GerritVersion) {
		toSerialize["gerrit_version"] = o.GerritVersion
	}
	if !IsNil(o.NoteDbVersion) {
		toSerialize["note_db_version"] = o.NoteDbVersion
	}
	if !IsNil(o.ChangeIndexVersion) {
		toSerialize["change_index_version"] = o.ChangeIndexVersion
	}
	if !IsNil(o.AccountIndexVersion) {
		toSerialize["account_index_version"] = o.AccountIndexVersion
	}
	if !IsNil(o.ProjectIndexVersion) {
		toSerialize["project_index_version"] = o.ProjectIndexVersion
	}
	if !IsNil(o.GroupIndexVersion) {
		toSerialize["group_index_version"] = o.GroupIndexVersion
	}
	return toSerialize, nil
}

type NullableGetConfigServerVersion200ResponseOneOf struct {
	value *GetConfigServerVersion200ResponseOneOf
	isSet bool
}

func (v NullableGetConfigServerVersion200ResponseOneOf) Get() *GetConfigServerVersion200ResponseOneOf {
	return v.value
}

func (v *NullableGetConfigServerVersion200ResponseOneOf) Set(val *GetConfigServerVersion200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConfigServerVersion200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConfigServerVersion200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConfigServerVersion200ResponseOneOf(val *GetConfigServerVersion200ResponseOneOf) *NullableGetConfigServerVersion200ResponseOneOf {
	return &NullableGetConfigServerVersion200ResponseOneOf{value: val, isSet: true}
}

func (v NullableGetConfigServerVersion200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConfigServerVersion200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


