/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the RebaseInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RebaseInput{}

// RebaseInput struct for RebaseInput
type RebaseInput struct {
	// The new parent revision. This can be a ref or a SHA-1 to a concrete patchset. + Alternatively, a change number can be specified, in which case the current patch set is inferred.
	Base *string `json:"base,omitempty"`
	// The strategy of the merge, can be recursive, resolve, simple-two-way-in-core, ours or theirs, default will use project settings.
	Strategy *string `json:"strategy,omitempty"`
	// If true, the rebase also succeeds if there are conflicts. + If there are conflicts the file contents of the rebased patch set contain git conflict markers to indicate the conflicts.
	AllowConflicts *bool `json:"allow_conflicts,omitempty"`
	// If true, the rebase is done on behalf of the uploader. + This means the uploader of the current patch set will also be the uploader of the rebased patch set. The calling user will be recorded as the real user. + Rebasing on behalf of the uploader is only supported for trivial rebases.
	OnBehalfOfUploader *bool `json:"on_behalf_of_uploader,omitempty"`
	// Map with key-value pairs that are forwarded as options to the commit validation listeners (e.g. can be used to skip certain validations). Which validation options are supported depends on the installed commit validation listeners.
	ValidationOptions map[string]string `json:"validation_options,omitempty"`
	// Rebase is committed using this email address. Only the registered emails of the calling user or uploader (when on_behalf_of_uploader is true) are considered valid. This option is not supported when rebasing a chain.
	CommitterEmail *string `json:"committer_email,omitempty"`
}

// NewRebaseInput instantiates a new RebaseInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRebaseInput() *RebaseInput {
	this := RebaseInput{}
	return &this
}

// NewRebaseInputWithDefaults instantiates a new RebaseInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRebaseInputWithDefaults() *RebaseInput {
	this := RebaseInput{}
	return &this
}

// GetBase returns the Base field value if set, zero value otherwise.
func (o *RebaseInput) GetBase() string {
	if o == nil || IsNil(o.Base) {
		var ret string
		return ret
	}
	return *o.Base
}

// GetBaseOk returns a tuple with the Base field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RebaseInput) GetBaseOk() (*string, bool) {
	if o == nil || IsNil(o.Base) {
		return nil, false
	}
	return o.Base, true
}

// HasBase returns a boolean if a field has been set.
func (o *RebaseInput) HasBase() bool {
	if o != nil && !IsNil(o.Base) {
		return true
	}

	return false
}

// SetBase gets a reference to the given string and assigns it to the Base field.
func (o *RebaseInput) SetBase(v string) {
	o.Base = &v
}

// GetStrategy returns the Strategy field value if set, zero value otherwise.
func (o *RebaseInput) GetStrategy() string {
	if o == nil || IsNil(o.Strategy) {
		var ret string
		return ret
	}
	return *o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RebaseInput) GetStrategyOk() (*string, bool) {
	if o == nil || IsNil(o.Strategy) {
		return nil, false
	}
	return o.Strategy, true
}

// HasStrategy returns a boolean if a field has been set.
func (o *RebaseInput) HasStrategy() bool {
	if o != nil && !IsNil(o.Strategy) {
		return true
	}

	return false
}

// SetStrategy gets a reference to the given string and assigns it to the Strategy field.
func (o *RebaseInput) SetStrategy(v string) {
	o.Strategy = &v
}

// GetAllowConflicts returns the AllowConflicts field value if set, zero value otherwise.
func (o *RebaseInput) GetAllowConflicts() bool {
	if o == nil || IsNil(o.AllowConflicts) {
		var ret bool
		return ret
	}
	return *o.AllowConflicts
}

// GetAllowConflictsOk returns a tuple with the AllowConflicts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RebaseInput) GetAllowConflictsOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowConflicts) {
		return nil, false
	}
	return o.AllowConflicts, true
}

// HasAllowConflicts returns a boolean if a field has been set.
func (o *RebaseInput) HasAllowConflicts() bool {
	if o != nil && !IsNil(o.AllowConflicts) {
		return true
	}

	return false
}

// SetAllowConflicts gets a reference to the given bool and assigns it to the AllowConflicts field.
func (o *RebaseInput) SetAllowConflicts(v bool) {
	o.AllowConflicts = &v
}

// GetOnBehalfOfUploader returns the OnBehalfOfUploader field value if set, zero value otherwise.
func (o *RebaseInput) GetOnBehalfOfUploader() bool {
	if o == nil || IsNil(o.OnBehalfOfUploader) {
		var ret bool
		return ret
	}
	return *o.OnBehalfOfUploader
}

// GetOnBehalfOfUploaderOk returns a tuple with the OnBehalfOfUploader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RebaseInput) GetOnBehalfOfUploaderOk() (*bool, bool) {
	if o == nil || IsNil(o.OnBehalfOfUploader) {
		return nil, false
	}
	return o.OnBehalfOfUploader, true
}

// HasOnBehalfOfUploader returns a boolean if a field has been set.
func (o *RebaseInput) HasOnBehalfOfUploader() bool {
	if o != nil && !IsNil(o.OnBehalfOfUploader) {
		return true
	}

	return false
}

// SetOnBehalfOfUploader gets a reference to the given bool and assigns it to the OnBehalfOfUploader field.
func (o *RebaseInput) SetOnBehalfOfUploader(v bool) {
	o.OnBehalfOfUploader = &v
}

// GetValidationOptions returns the ValidationOptions field value if set, zero value otherwise.
func (o *RebaseInput) GetValidationOptions() map[string]string {
	if o == nil || IsNil(o.ValidationOptions) {
		var ret map[string]string
		return ret
	}
	return o.ValidationOptions
}

// GetValidationOptionsOk returns a tuple with the ValidationOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RebaseInput) GetValidationOptionsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.ValidationOptions) {
		return map[string]string{}, false
	}
	return o.ValidationOptions, true
}

// HasValidationOptions returns a boolean if a field has been set.
func (o *RebaseInput) HasValidationOptions() bool {
	if o != nil && !IsNil(o.ValidationOptions) {
		return true
	}

	return false
}

// SetValidationOptions gets a reference to the given map[string]string and assigns it to the ValidationOptions field.
func (o *RebaseInput) SetValidationOptions(v map[string]string) {
	o.ValidationOptions = v
}

// GetCommitterEmail returns the CommitterEmail field value if set, zero value otherwise.
func (o *RebaseInput) GetCommitterEmail() string {
	if o == nil || IsNil(o.CommitterEmail) {
		var ret string
		return ret
	}
	return *o.CommitterEmail
}

// GetCommitterEmailOk returns a tuple with the CommitterEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RebaseInput) GetCommitterEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CommitterEmail) {
		return nil, false
	}
	return o.CommitterEmail, true
}

// HasCommitterEmail returns a boolean if a field has been set.
func (o *RebaseInput) HasCommitterEmail() bool {
	if o != nil && !IsNil(o.CommitterEmail) {
		return true
	}

	return false
}

// SetCommitterEmail gets a reference to the given string and assigns it to the CommitterEmail field.
func (o *RebaseInput) SetCommitterEmail(v string) {
	o.CommitterEmail = &v
}

func (o RebaseInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RebaseInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Base) {
		toSerialize["base"] = o.Base
	}
	if !IsNil(o.Strategy) {
		toSerialize["strategy"] = o.Strategy
	}
	if !IsNil(o.AllowConflicts) {
		toSerialize["allow_conflicts"] = o.AllowConflicts
	}
	if !IsNil(o.OnBehalfOfUploader) {
		toSerialize["on_behalf_of_uploader"] = o.OnBehalfOfUploader
	}
	if !IsNil(o.ValidationOptions) {
		toSerialize["validation_options"] = o.ValidationOptions
	}
	if !IsNil(o.CommitterEmail) {
		toSerialize["committer_email"] = o.CommitterEmail
	}
	return toSerialize, nil
}

type NullableRebaseInput struct {
	value *RebaseInput
	isSet bool
}

func (v NullableRebaseInput) Get() *RebaseInput {
	return v.value
}

func (v *NullableRebaseInput) Set(val *RebaseInput) {
	v.value = val
	v.isSet = true
}

func (v NullableRebaseInput) IsSet() bool {
	return v.isSet
}

func (v *NullableRebaseInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRebaseInput(val *RebaseInput) *NullableRebaseInput {
	return &NullableRebaseInput{value: val, isSet: true}
}

func (v NullableRebaseInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRebaseInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


