/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ProjectAccessInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAccessInfo{}

// ProjectAccessInfo struct for ProjectAccessInfo
type ProjectAccessInfo struct {
	// The revision of the refs/meta/config branch from which the access rights were loaded.
	Revision *string `json:"revision,omitempty"`
	// The parent project from which permissions are inherited as a ProjectInfo entity.
	InheritsFrom *ProjectInfo `json:"inherits_from,omitempty"`
	// The local access rights of the project as a map that maps the refs to AccessSectionInfo entities.
	Local map[string]AccessSectionInfo `json:"local,omitempty"`
	// Whether the calling user owns this project.
	IsOwner *bool `json:"is_owner,omitempty"`
	// The list of refs owned by the calling user.
	OwnerOf []string `json:"owner_of,omitempty"`
	// Whether the calling user can upload to any ref.
	CanUpload *bool `json:"can_upload,omitempty"`
	// Whether the calling user can add any ref.
	CanAdd *bool `json:"can_add,omitempty"`
	// Whether the calling user can add any tag ref.
	CanAddTags *bool `json:"can_add_tags,omitempty"`
	// Whether the calling user can see the refs/meta/config branch of the project.
	ConfigVisible *bool `json:"config_visible,omitempty"`
	// Whether the calling user must create a change for updating project config. If true, all API requests which directly update project config are rejected.
	RequireChangeForConfigUpdate *bool `json:"require_change_for_config_update,omitempty"`
	// A map of group UUID to GroupInfo objects, with names and URLs for the group UUIDs used in the local map. This will include names for groups that might be invisible to the caller.
	Groups map[string]GroupInfo `json:"groups,omitempty"`
	// Links to the history of the configuration file governing this project's access rights as list of WebLinkInfo entities.
	ConfigWebLinks []WebLinkInfo `json:"config_web_links,omitempty"`
}

// NewProjectAccessInfo instantiates a new ProjectAccessInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAccessInfo() *ProjectAccessInfo {
	this := ProjectAccessInfo{}
	return &this
}

// NewProjectAccessInfoWithDefaults instantiates a new ProjectAccessInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAccessInfoWithDefaults() *ProjectAccessInfo {
	this := ProjectAccessInfo{}
	return &this
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetRevision() string {
	if o == nil || IsNil(o.Revision) {
		var ret string
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasRevision() bool {
	if o != nil && !IsNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given string and assigns it to the Revision field.
func (o *ProjectAccessInfo) SetRevision(v string) {
	o.Revision = &v
}

// GetInheritsFrom returns the InheritsFrom field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetInheritsFrom() ProjectInfo {
	if o == nil || IsNil(o.InheritsFrom) {
		var ret ProjectInfo
		return ret
	}
	return *o.InheritsFrom
}

// GetInheritsFromOk returns a tuple with the InheritsFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetInheritsFromOk() (*ProjectInfo, bool) {
	if o == nil || IsNil(o.InheritsFrom) {
		return nil, false
	}
	return o.InheritsFrom, true
}

// HasInheritsFrom returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasInheritsFrom() bool {
	if o != nil && !IsNil(o.InheritsFrom) {
		return true
	}

	return false
}

// SetInheritsFrom gets a reference to the given ProjectInfo and assigns it to the InheritsFrom field.
func (o *ProjectAccessInfo) SetInheritsFrom(v ProjectInfo) {
	o.InheritsFrom = &v
}

// GetLocal returns the Local field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetLocal() map[string]AccessSectionInfo {
	if o == nil || IsNil(o.Local) {
		var ret map[string]AccessSectionInfo
		return ret
	}
	return o.Local
}

// GetLocalOk returns a tuple with the Local field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetLocalOk() (map[string]AccessSectionInfo, bool) {
	if o == nil || IsNil(o.Local) {
		return map[string]AccessSectionInfo{}, false
	}
	return o.Local, true
}

// HasLocal returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasLocal() bool {
	if o != nil && !IsNil(o.Local) {
		return true
	}

	return false
}

// SetLocal gets a reference to the given map[string]AccessSectionInfo and assigns it to the Local field.
func (o *ProjectAccessInfo) SetLocal(v map[string]AccessSectionInfo) {
	o.Local = v
}

// GetIsOwner returns the IsOwner field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetIsOwner() bool {
	if o == nil || IsNil(o.IsOwner) {
		var ret bool
		return ret
	}
	return *o.IsOwner
}

// GetIsOwnerOk returns a tuple with the IsOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetIsOwnerOk() (*bool, bool) {
	if o == nil || IsNil(o.IsOwner) {
		return nil, false
	}
	return o.IsOwner, true
}

// HasIsOwner returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasIsOwner() bool {
	if o != nil && !IsNil(o.IsOwner) {
		return true
	}

	return false
}

// SetIsOwner gets a reference to the given bool and assigns it to the IsOwner field.
func (o *ProjectAccessInfo) SetIsOwner(v bool) {
	o.IsOwner = &v
}

// GetOwnerOf returns the OwnerOf field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetOwnerOf() []string {
	if o == nil || IsNil(o.OwnerOf) {
		var ret []string
		return ret
	}
	return o.OwnerOf
}

// GetOwnerOfOk returns a tuple with the OwnerOf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetOwnerOfOk() ([]string, bool) {
	if o == nil || IsNil(o.OwnerOf) {
		return nil, false
	}
	return o.OwnerOf, true
}

// HasOwnerOf returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasOwnerOf() bool {
	if o != nil && !IsNil(o.OwnerOf) {
		return true
	}

	return false
}

// SetOwnerOf gets a reference to the given []string and assigns it to the OwnerOf field.
func (o *ProjectAccessInfo) SetOwnerOf(v []string) {
	o.OwnerOf = v
}

// GetCanUpload returns the CanUpload field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetCanUpload() bool {
	if o == nil || IsNil(o.CanUpload) {
		var ret bool
		return ret
	}
	return *o.CanUpload
}

// GetCanUploadOk returns a tuple with the CanUpload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetCanUploadOk() (*bool, bool) {
	if o == nil || IsNil(o.CanUpload) {
		return nil, false
	}
	return o.CanUpload, true
}

// HasCanUpload returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasCanUpload() bool {
	if o != nil && !IsNil(o.CanUpload) {
		return true
	}

	return false
}

// SetCanUpload gets a reference to the given bool and assigns it to the CanUpload field.
func (o *ProjectAccessInfo) SetCanUpload(v bool) {
	o.CanUpload = &v
}

// GetCanAdd returns the CanAdd field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetCanAdd() bool {
	if o == nil || IsNil(o.CanAdd) {
		var ret bool
		return ret
	}
	return *o.CanAdd
}

// GetCanAddOk returns a tuple with the CanAdd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetCanAddOk() (*bool, bool) {
	if o == nil || IsNil(o.CanAdd) {
		return nil, false
	}
	return o.CanAdd, true
}

// HasCanAdd returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasCanAdd() bool {
	if o != nil && !IsNil(o.CanAdd) {
		return true
	}

	return false
}

// SetCanAdd gets a reference to the given bool and assigns it to the CanAdd field.
func (o *ProjectAccessInfo) SetCanAdd(v bool) {
	o.CanAdd = &v
}

// GetCanAddTags returns the CanAddTags field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetCanAddTags() bool {
	if o == nil || IsNil(o.CanAddTags) {
		var ret bool
		return ret
	}
	return *o.CanAddTags
}

// GetCanAddTagsOk returns a tuple with the CanAddTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetCanAddTagsOk() (*bool, bool) {
	if o == nil || IsNil(o.CanAddTags) {
		return nil, false
	}
	return o.CanAddTags, true
}

// HasCanAddTags returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasCanAddTags() bool {
	if o != nil && !IsNil(o.CanAddTags) {
		return true
	}

	return false
}

// SetCanAddTags gets a reference to the given bool and assigns it to the CanAddTags field.
func (o *ProjectAccessInfo) SetCanAddTags(v bool) {
	o.CanAddTags = &v
}

// GetConfigVisible returns the ConfigVisible field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetConfigVisible() bool {
	if o == nil || IsNil(o.ConfigVisible) {
		var ret bool
		return ret
	}
	return *o.ConfigVisible
}

// GetConfigVisibleOk returns a tuple with the ConfigVisible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetConfigVisibleOk() (*bool, bool) {
	if o == nil || IsNil(o.ConfigVisible) {
		return nil, false
	}
	return o.ConfigVisible, true
}

// HasConfigVisible returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasConfigVisible() bool {
	if o != nil && !IsNil(o.ConfigVisible) {
		return true
	}

	return false
}

// SetConfigVisible gets a reference to the given bool and assigns it to the ConfigVisible field.
func (o *ProjectAccessInfo) SetConfigVisible(v bool) {
	o.ConfigVisible = &v
}

// GetRequireChangeForConfigUpdate returns the RequireChangeForConfigUpdate field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetRequireChangeForConfigUpdate() bool {
	if o == nil || IsNil(o.RequireChangeForConfigUpdate) {
		var ret bool
		return ret
	}
	return *o.RequireChangeForConfigUpdate
}

// GetRequireChangeForConfigUpdateOk returns a tuple with the RequireChangeForConfigUpdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetRequireChangeForConfigUpdateOk() (*bool, bool) {
	if o == nil || IsNil(o.RequireChangeForConfigUpdate) {
		return nil, false
	}
	return o.RequireChangeForConfigUpdate, true
}

// HasRequireChangeForConfigUpdate returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasRequireChangeForConfigUpdate() bool {
	if o != nil && !IsNil(o.RequireChangeForConfigUpdate) {
		return true
	}

	return false
}

// SetRequireChangeForConfigUpdate gets a reference to the given bool and assigns it to the RequireChangeForConfigUpdate field.
func (o *ProjectAccessInfo) SetRequireChangeForConfigUpdate(v bool) {
	o.RequireChangeForConfigUpdate = &v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetGroups() map[string]GroupInfo {
	if o == nil || IsNil(o.Groups) {
		var ret map[string]GroupInfo
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetGroupsOk() (map[string]GroupInfo, bool) {
	if o == nil || IsNil(o.Groups) {
		return map[string]GroupInfo{}, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given map[string]GroupInfo and assigns it to the Groups field.
func (o *ProjectAccessInfo) SetGroups(v map[string]GroupInfo) {
	o.Groups = v
}

// GetConfigWebLinks returns the ConfigWebLinks field value if set, zero value otherwise.
func (o *ProjectAccessInfo) GetConfigWebLinks() []WebLinkInfo {
	if o == nil || IsNil(o.ConfigWebLinks) {
		var ret []WebLinkInfo
		return ret
	}
	return o.ConfigWebLinks
}

// GetConfigWebLinksOk returns a tuple with the ConfigWebLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAccessInfo) GetConfigWebLinksOk() ([]WebLinkInfo, bool) {
	if o == nil || IsNil(o.ConfigWebLinks) {
		return nil, false
	}
	return o.ConfigWebLinks, true
}

// HasConfigWebLinks returns a boolean if a field has been set.
func (o *ProjectAccessInfo) HasConfigWebLinks() bool {
	if o != nil && !IsNil(o.ConfigWebLinks) {
		return true
	}

	return false
}

// SetConfigWebLinks gets a reference to the given []WebLinkInfo and assigns it to the ConfigWebLinks field.
func (o *ProjectAccessInfo) SetConfigWebLinks(v []WebLinkInfo) {
	o.ConfigWebLinks = v
}

func (o ProjectAccessInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAccessInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Revision) {
		toSerialize["revision"] = o.Revision
	}
	if !IsNil(o.InheritsFrom) {
		toSerialize["inherits_from"] = o.InheritsFrom
	}
	if !IsNil(o.Local) {
		toSerialize["local"] = o.Local
	}
	if !IsNil(o.IsOwner) {
		toSerialize["is_owner"] = o.IsOwner
	}
	if !IsNil(o.OwnerOf) {
		toSerialize["owner_of"] = o.OwnerOf
	}
	if !IsNil(o.CanUpload) {
		toSerialize["can_upload"] = o.CanUpload
	}
	if !IsNil(o.CanAdd) {
		toSerialize["can_add"] = o.CanAdd
	}
	if !IsNil(o.CanAddTags) {
		toSerialize["can_add_tags"] = o.CanAddTags
	}
	if !IsNil(o.ConfigVisible) {
		toSerialize["config_visible"] = o.ConfigVisible
	}
	if !IsNil(o.RequireChangeForConfigUpdate) {
		toSerialize["require_change_for_config_update"] = o.RequireChangeForConfigUpdate
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	if !IsNil(o.ConfigWebLinks) {
		toSerialize["config_web_links"] = o.ConfigWebLinks
	}
	return toSerialize, nil
}

type NullableProjectAccessInfo struct {
	value *ProjectAccessInfo
	isSet bool
}

func (v NullableProjectAccessInfo) Get() *ProjectAccessInfo {
	return v.value
}

func (v *NullableProjectAccessInfo) Set(val *ProjectAccessInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAccessInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAccessInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAccessInfo(val *ProjectAccessInfo) *NullableProjectAccessInfo {
	return &NullableProjectAccessInfo{value: val, isSet: true}
}

func (v NullableProjectAccessInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAccessInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


