/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the UserConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserConfigInfo{}

// UserConfigInfo struct for UserConfigInfo
type UserConfigInfo struct {
	// Username that is displayed in the Gerrit Web UI and in e-mail notifications if the full name of the user is not set.
	AnonymousCowardName *string `json:"anonymous_coward_name,omitempty"`
}

// NewUserConfigInfo instantiates a new UserConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserConfigInfo() *UserConfigInfo {
	this := UserConfigInfo{}
	return &this
}

// NewUserConfigInfoWithDefaults instantiates a new UserConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserConfigInfoWithDefaults() *UserConfigInfo {
	this := UserConfigInfo{}
	return &this
}

// GetAnonymousCowardName returns the AnonymousCowardName field value if set, zero value otherwise.
func (o *UserConfigInfo) GetAnonymousCowardName() string {
	if o == nil || IsNil(o.AnonymousCowardName) {
		var ret string
		return ret
	}
	return *o.AnonymousCowardName
}

// GetAnonymousCowardNameOk returns a tuple with the AnonymousCowardName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserConfigInfo) GetAnonymousCowardNameOk() (*string, bool) {
	if o == nil || IsNil(o.AnonymousCowardName) {
		return nil, false
	}
	return o.AnonymousCowardName, true
}

// HasAnonymousCowardName returns a boolean if a field has been set.
func (o *UserConfigInfo) HasAnonymousCowardName() bool {
	if o != nil && !IsNil(o.AnonymousCowardName) {
		return true
	}

	return false
}

// SetAnonymousCowardName gets a reference to the given string and assigns it to the AnonymousCowardName field.
func (o *UserConfigInfo) SetAnonymousCowardName(v string) {
	o.AnonymousCowardName = &v
}

func (o UserConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AnonymousCowardName) {
		toSerialize["anonymous_coward_name"] = o.AnonymousCowardName
	}
	return toSerialize, nil
}

type NullableUserConfigInfo struct {
	value *UserConfigInfo
	isSet bool
}

func (v NullableUserConfigInfo) Get() *UserConfigInfo {
	return v.value
}

func (v *NullableUserConfigInfo) Set(val *UserConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableUserConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableUserConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserConfigInfo(val *UserConfigInfo) *NullableUserConfigInfo {
	return &NullableUserConfigInfo{value: val, isSet: true}
}

func (v NullableUserConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


