/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ReviewerUpdateInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewerUpdateInfo{}

// ReviewerUpdateInfo struct for ReviewerUpdateInfo
type ReviewerUpdateInfo struct {
	Updated *string `json:"updated,omitempty"`
	UpdatedBy *AccountInfo `json:"updated_by,omitempty"`
	RealUpdatedBy *AccountInfo `json:"real_updated_by,omitempty"`
	Reviewer *AccountInfo `json:"reviewer,omitempty"`
	State *ReviewerState `json:"state,omitempty"`
}

// NewReviewerUpdateInfo instantiates a new ReviewerUpdateInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewerUpdateInfo() *ReviewerUpdateInfo {
	this := ReviewerUpdateInfo{}
	return &this
}

// NewReviewerUpdateInfoWithDefaults instantiates a new ReviewerUpdateInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewerUpdateInfoWithDefaults() *ReviewerUpdateInfo {
	this := ReviewerUpdateInfo{}
	return &this
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ReviewerUpdateInfo) GetUpdated() string {
	if o == nil || IsNil(o.Updated) {
		var ret string
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerUpdateInfo) GetUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ReviewerUpdateInfo) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given string and assigns it to the Updated field.
func (o *ReviewerUpdateInfo) SetUpdated(v string) {
	o.Updated = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *ReviewerUpdateInfo) GetUpdatedBy() AccountInfo {
	if o == nil || IsNil(o.UpdatedBy) {
		var ret AccountInfo
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerUpdateInfo) GetUpdatedByOk() (*AccountInfo, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *ReviewerUpdateInfo) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given AccountInfo and assigns it to the UpdatedBy field.
func (o *ReviewerUpdateInfo) SetUpdatedBy(v AccountInfo) {
	o.UpdatedBy = &v
}

// GetRealUpdatedBy returns the RealUpdatedBy field value if set, zero value otherwise.
func (o *ReviewerUpdateInfo) GetRealUpdatedBy() AccountInfo {
	if o == nil || IsNil(o.RealUpdatedBy) {
		var ret AccountInfo
		return ret
	}
	return *o.RealUpdatedBy
}

// GetRealUpdatedByOk returns a tuple with the RealUpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerUpdateInfo) GetRealUpdatedByOk() (*AccountInfo, bool) {
	if o == nil || IsNil(o.RealUpdatedBy) {
		return nil, false
	}
	return o.RealUpdatedBy, true
}

// HasRealUpdatedBy returns a boolean if a field has been set.
func (o *ReviewerUpdateInfo) HasRealUpdatedBy() bool {
	if o != nil && !IsNil(o.RealUpdatedBy) {
		return true
	}

	return false
}

// SetRealUpdatedBy gets a reference to the given AccountInfo and assigns it to the RealUpdatedBy field.
func (o *ReviewerUpdateInfo) SetRealUpdatedBy(v AccountInfo) {
	o.RealUpdatedBy = &v
}

// GetReviewer returns the Reviewer field value if set, zero value otherwise.
func (o *ReviewerUpdateInfo) GetReviewer() AccountInfo {
	if o == nil || IsNil(o.Reviewer) {
		var ret AccountInfo
		return ret
	}
	return *o.Reviewer
}

// GetReviewerOk returns a tuple with the Reviewer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerUpdateInfo) GetReviewerOk() (*AccountInfo, bool) {
	if o == nil || IsNil(o.Reviewer) {
		return nil, false
	}
	return o.Reviewer, true
}

// HasReviewer returns a boolean if a field has been set.
func (o *ReviewerUpdateInfo) HasReviewer() bool {
	if o != nil && !IsNil(o.Reviewer) {
		return true
	}

	return false
}

// SetReviewer gets a reference to the given AccountInfo and assigns it to the Reviewer field.
func (o *ReviewerUpdateInfo) SetReviewer(v AccountInfo) {
	o.Reviewer = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ReviewerUpdateInfo) GetState() ReviewerState {
	if o == nil || IsNil(o.State) {
		var ret ReviewerState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerUpdateInfo) GetStateOk() (*ReviewerState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ReviewerUpdateInfo) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given ReviewerState and assigns it to the State field.
func (o *ReviewerUpdateInfo) SetState(v ReviewerState) {
	o.State = &v
}

func (o ReviewerUpdateInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewerUpdateInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.UpdatedBy) {
		toSerialize["updated_by"] = o.UpdatedBy
	}
	if !IsNil(o.RealUpdatedBy) {
		toSerialize["real_updated_by"] = o.RealUpdatedBy
	}
	if !IsNil(o.Reviewer) {
		toSerialize["reviewer"] = o.Reviewer
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableReviewerUpdateInfo struct {
	value *ReviewerUpdateInfo
	isSet bool
}

func (v NullableReviewerUpdateInfo) Get() *ReviewerUpdateInfo {
	return v.value
}

func (v *NullableReviewerUpdateInfo) Set(val *ReviewerUpdateInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewerUpdateInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewerUpdateInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewerUpdateInfo(val *ReviewerUpdateInfo) *NullableReviewerUpdateInfo {
	return &NullableReviewerUpdateInfo{value: val, isSet: true}
}

func (v NullableReviewerUpdateInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewerUpdateInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


