/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the SnapshotIndexInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnapshotIndexInput{}

// SnapshotIndexInput struct for SnapshotIndexInput
type SnapshotIndexInput struct {
	Id *string `json:"id,omitempty"`
}

// NewSnapshotIndexInput instantiates a new SnapshotIndexInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnapshotIndexInput() *SnapshotIndexInput {
	this := SnapshotIndexInput{}
	return &this
}

// NewSnapshotIndexInputWithDefaults instantiates a new SnapshotIndexInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnapshotIndexInputWithDefaults() *SnapshotIndexInput {
	this := SnapshotIndexInput{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SnapshotIndexInput) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnapshotIndexInput) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SnapshotIndexInput) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SnapshotIndexInput) SetId(v string) {
	o.Id = &v
}

func (o SnapshotIndexInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnapshotIndexInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableSnapshotIndexInput struct {
	value *SnapshotIndexInput
	isSet bool
}

func (v NullableSnapshotIndexInput) Get() *SnapshotIndexInput {
	return v.value
}

func (v *NullableSnapshotIndexInput) Set(val *SnapshotIndexInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSnapshotIndexInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSnapshotIndexInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnapshotIndexInput(val *SnapshotIndexInput) *NullableSnapshotIndexInput {
	return &NullableSnapshotIndexInput{value: val, isSet: true}
}

func (v NullableSnapshotIndexInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnapshotIndexInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


