/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
	"fmt"
)

// ProjectConfigEntryType the model 'ProjectConfigEntryType'
type ProjectConfigEntryType string

// List of ProjectConfigEntryType
const (
	PROJECTCONFIGENTRYTYPE_STRING ProjectConfigEntryType = "STRING"
	PROJECTCONFIGENTRYTYPE_INT ProjectConfigEntryType = "INT"
	PROJECTCONFIGENTRYTYPE_LONG ProjectConfigEntryType = "LONG"
	PROJECTCONFIGENTRYTYPE_BOOLEAN ProjectConfigEntryType = "BOOLEAN"
	PROJECTCONFIGENTRYTYPE_LIST ProjectConfigEntryType = "LIST"
	PROJECTCONFIGENTRYTYPE_ARRAY ProjectConfigEntryType = "ARRAY"
)

// All allowed values of ProjectConfigEntryType enum
var AllowedProjectConfigEntryTypeEnumValues = []ProjectConfigEntryType{
	"STRING",
	"INT",
	"LONG",
	"BOOLEAN",
	"LIST",
	"ARRAY",
}

func (v *ProjectConfigEntryType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProjectConfigEntryType(value)
	for _, existing := range AllowedProjectConfigEntryTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ProjectConfigEntryType", value)
}

// NewProjectConfigEntryTypeFromValue returns a pointer to a valid ProjectConfigEntryType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewProjectConfigEntryTypeFromValue(v string) (*ProjectConfigEntryType, error) {
	ev := ProjectConfigEntryType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ProjectConfigEntryType: valid values are %v", v, AllowedProjectConfigEntryTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ProjectConfigEntryType) IsValid() bool {
	for _, existing := range AllowedProjectConfigEntryTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ProjectConfigEntryType value
func (v ProjectConfigEntryType) Ptr() *ProjectConfigEntryType {
	return &v
}

type NullableProjectConfigEntryType struct {
	value *ProjectConfigEntryType
	isSet bool
}

func (v NullableProjectConfigEntryType) Get() *ProjectConfigEntryType {
	return v.value
}

func (v *NullableProjectConfigEntryType) Set(val *ProjectConfigEntryType) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectConfigEntryType) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectConfigEntryType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectConfigEntryType(val *ProjectConfigEntryType) *NullableProjectConfigEntryType {
	return &NullableProjectConfigEntryType{value: val, isSet: true}
}

func (v NullableProjectConfigEntryType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectConfigEntryType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

