/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the CommentInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommentInput{}

// CommentInput struct for CommentInput
type CommentInput struct {
	EnableContext *bool `json:"enable_context,omitempty"`
}

// NewCommentInput instantiates a new CommentInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommentInput() *CommentInput {
	this := CommentInput{}
	return &this
}

// NewCommentInputWithDefaults instantiates a new CommentInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommentInputWithDefaults() *CommentInput {
	this := CommentInput{}
	return &this
}

// GetEnableContext returns the EnableContext field value if set, zero value otherwise.
func (o *CommentInput) GetEnableContext() bool {
	if o == nil || IsNil(o.EnableContext) {
		var ret bool
		return ret
	}
	return *o.EnableContext
}

// GetEnableContextOk returns a tuple with the EnableContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentInput) GetEnableContextOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableContext) {
		return nil, false
	}
	return o.EnableContext, true
}

// HasEnableContext returns a boolean if a field has been set.
func (o *CommentInput) HasEnableContext() bool {
	if o != nil && !IsNil(o.EnableContext) {
		return true
	}

	return false
}

// SetEnableContext gets a reference to the given bool and assigns it to the EnableContext field.
func (o *CommentInput) SetEnableContext(v bool) {
	o.EnableContext = &v
}

func (o CommentInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommentInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EnableContext) {
		toSerialize["enable_context"] = o.EnableContext
	}
	return toSerialize, nil
}

type NullableCommentInput struct {
	value *CommentInput
	isSet bool
}

func (v NullableCommentInput) Get() *CommentInput {
	return v.value
}

func (v *NullableCommentInput) Set(val *CommentInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCommentInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCommentInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommentInput(val *CommentInput) *NullableCommentInput {
	return &NullableCommentInput{value: val, isSet: true}
}

func (v NullableCommentInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommentInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


