/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ThreadSummaryInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThreadSummaryInfo{}

// ThreadSummaryInfo struct for ThreadSummaryInfo
type ThreadSummaryInfo struct {
	Cpus *int32 `json:"cpus,omitempty"`
	Threads *int32 `json:"threads,omitempty"`
	Counts map[string]map[string]int32 `json:"counts,omitempty"`
}

// NewThreadSummaryInfo instantiates a new ThreadSummaryInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThreadSummaryInfo() *ThreadSummaryInfo {
	this := ThreadSummaryInfo{}
	return &this
}

// NewThreadSummaryInfoWithDefaults instantiates a new ThreadSummaryInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThreadSummaryInfoWithDefaults() *ThreadSummaryInfo {
	this := ThreadSummaryInfo{}
	return &this
}

// GetCpus returns the Cpus field value if set, zero value otherwise.
func (o *ThreadSummaryInfo) GetCpus() int32 {
	if o == nil || IsNil(o.Cpus) {
		var ret int32
		return ret
	}
	return *o.Cpus
}

// GetCpusOk returns a tuple with the Cpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreadSummaryInfo) GetCpusOk() (*int32, bool) {
	if o == nil || IsNil(o.Cpus) {
		return nil, false
	}
	return o.Cpus, true
}

// HasCpus returns a boolean if a field has been set.
func (o *ThreadSummaryInfo) HasCpus() bool {
	if o != nil && !IsNil(o.Cpus) {
		return true
	}

	return false
}

// SetCpus gets a reference to the given int32 and assigns it to the Cpus field.
func (o *ThreadSummaryInfo) SetCpus(v int32) {
	o.Cpus = &v
}

// GetThreads returns the Threads field value if set, zero value otherwise.
func (o *ThreadSummaryInfo) GetThreads() int32 {
	if o == nil || IsNil(o.Threads) {
		var ret int32
		return ret
	}
	return *o.Threads
}

// GetThreadsOk returns a tuple with the Threads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreadSummaryInfo) GetThreadsOk() (*int32, bool) {
	if o == nil || IsNil(o.Threads) {
		return nil, false
	}
	return o.Threads, true
}

// HasThreads returns a boolean if a field has been set.
func (o *ThreadSummaryInfo) HasThreads() bool {
	if o != nil && !IsNil(o.Threads) {
		return true
	}

	return false
}

// SetThreads gets a reference to the given int32 and assigns it to the Threads field.
func (o *ThreadSummaryInfo) SetThreads(v int32) {
	o.Threads = &v
}

// GetCounts returns the Counts field value if set, zero value otherwise.
func (o *ThreadSummaryInfo) GetCounts() map[string]map[string]int32 {
	if o == nil || IsNil(o.Counts) {
		var ret map[string]map[string]int32
		return ret
	}
	return o.Counts
}

// GetCountsOk returns a tuple with the Counts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreadSummaryInfo) GetCountsOk() (map[string]map[string]int32, bool) {
	if o == nil || IsNil(o.Counts) {
		return map[string]map[string]int32{}, false
	}
	return o.Counts, true
}

// HasCounts returns a boolean if a field has been set.
func (o *ThreadSummaryInfo) HasCounts() bool {
	if o != nil && !IsNil(o.Counts) {
		return true
	}

	return false
}

// SetCounts gets a reference to the given map[string]map[string]int32 and assigns it to the Counts field.
func (o *ThreadSummaryInfo) SetCounts(v map[string]map[string]int32) {
	o.Counts = v
}

func (o ThreadSummaryInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThreadSummaryInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cpus) {
		toSerialize["cpus"] = o.Cpus
	}
	if !IsNil(o.Threads) {
		toSerialize["threads"] = o.Threads
	}
	if !IsNil(o.Counts) {
		toSerialize["counts"] = o.Counts
	}
	return toSerialize, nil
}

type NullableThreadSummaryInfo struct {
	value *ThreadSummaryInfo
	isSet bool
}

func (v NullableThreadSummaryInfo) Get() *ThreadSummaryInfo {
	return v.value
}

func (v *NullableThreadSummaryInfo) Set(val *ThreadSummaryInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableThreadSummaryInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableThreadSummaryInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThreadSummaryInfo(val *ThreadSummaryInfo) *NullableThreadSummaryInfo {
	return &NullableThreadSummaryInfo{value: val, isSet: true}
}

func (v NullableThreadSummaryInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThreadSummaryInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


