/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the GpgKeyInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GpgKeyInfo{}

// GpgKeyInfo struct for GpgKeyInfo
type GpgKeyInfo struct {
	// The 8-char hex GPG key ID.
	Id *string `json:"id,omitempty"`
	// The 40-char (plus spaces) hex GPG key fingerprint.
	Fingerprint *string `json:"fingerprint,omitempty"`
	// OpenPGP User IDs,role=external,window=_blank associated with the public key.
	UserIds []string `json:"user_ids,omitempty"`
	// ASCII armored public key material.
	Key *string `json:"key,omitempty"`
	// The result of server-side checks on the key; one of BAD, OK, or TRUSTED. BAD keys have serious problems and should not be used. If a key is OK, inspecting only that key found no problems, but the system does not fully trust the key's origin.
	Status *GpgKeyInfoStatus `json:"status,omitempty"`
	// A list of human-readable problem strings found in the course of checking whether the key is valid and trusted.
	Problems []string `json:"problems,omitempty"`
}

// NewGpgKeyInfo instantiates a new GpgKeyInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGpgKeyInfo() *GpgKeyInfo {
	this := GpgKeyInfo{}
	return &this
}

// NewGpgKeyInfoWithDefaults instantiates a new GpgKeyInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGpgKeyInfoWithDefaults() *GpgKeyInfo {
	this := GpgKeyInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GpgKeyInfo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyInfo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GpgKeyInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GpgKeyInfo) SetId(v string) {
	o.Id = &v
}

// GetFingerprint returns the Fingerprint field value if set, zero value otherwise.
func (o *GpgKeyInfo) GetFingerprint() string {
	if o == nil || IsNil(o.Fingerprint) {
		var ret string
		return ret
	}
	return *o.Fingerprint
}

// GetFingerprintOk returns a tuple with the Fingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyInfo) GetFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.Fingerprint) {
		return nil, false
	}
	return o.Fingerprint, true
}

// HasFingerprint returns a boolean if a field has been set.
func (o *GpgKeyInfo) HasFingerprint() bool {
	if o != nil && !IsNil(o.Fingerprint) {
		return true
	}

	return false
}

// SetFingerprint gets a reference to the given string and assigns it to the Fingerprint field.
func (o *GpgKeyInfo) SetFingerprint(v string) {
	o.Fingerprint = &v
}

// GetUserIds returns the UserIds field value if set, zero value otherwise.
func (o *GpgKeyInfo) GetUserIds() []string {
	if o == nil || IsNil(o.UserIds) {
		var ret []string
		return ret
	}
	return o.UserIds
}

// GetUserIdsOk returns a tuple with the UserIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyInfo) GetUserIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.UserIds) {
		return nil, false
	}
	return o.UserIds, true
}

// HasUserIds returns a boolean if a field has been set.
func (o *GpgKeyInfo) HasUserIds() bool {
	if o != nil && !IsNil(o.UserIds) {
		return true
	}

	return false
}

// SetUserIds gets a reference to the given []string and assigns it to the UserIds field.
func (o *GpgKeyInfo) SetUserIds(v []string) {
	o.UserIds = v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *GpgKeyInfo) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyInfo) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *GpgKeyInfo) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *GpgKeyInfo) SetKey(v string) {
	o.Key = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GpgKeyInfo) GetStatus() GpgKeyInfoStatus {
	if o == nil || IsNil(o.Status) {
		var ret GpgKeyInfoStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyInfo) GetStatusOk() (*GpgKeyInfoStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GpgKeyInfo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given GpgKeyInfoStatus and assigns it to the Status field.
func (o *GpgKeyInfo) SetStatus(v GpgKeyInfoStatus) {
	o.Status = &v
}

// GetProblems returns the Problems field value if set, zero value otherwise.
func (o *GpgKeyInfo) GetProblems() []string {
	if o == nil || IsNil(o.Problems) {
		var ret []string
		return ret
	}
	return o.Problems
}

// GetProblemsOk returns a tuple with the Problems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GpgKeyInfo) GetProblemsOk() ([]string, bool) {
	if o == nil || IsNil(o.Problems) {
		return nil, false
	}
	return o.Problems, true
}

// HasProblems returns a boolean if a field has been set.
func (o *GpgKeyInfo) HasProblems() bool {
	if o != nil && !IsNil(o.Problems) {
		return true
	}

	return false
}

// SetProblems gets a reference to the given []string and assigns it to the Problems field.
func (o *GpgKeyInfo) SetProblems(v []string) {
	o.Problems = v
}

func (o GpgKeyInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GpgKeyInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Fingerprint) {
		toSerialize["fingerprint"] = o.Fingerprint
	}
	if !IsNil(o.UserIds) {
		toSerialize["user_ids"] = o.UserIds
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Problems) {
		toSerialize["problems"] = o.Problems
	}
	return toSerialize, nil
}

type NullableGpgKeyInfo struct {
	value *GpgKeyInfo
	isSet bool
}

func (v NullableGpgKeyInfo) Get() *GpgKeyInfo {
	return v.value
}

func (v *NullableGpgKeyInfo) Set(val *GpgKeyInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGpgKeyInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGpgKeyInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGpgKeyInfo(val *GpgKeyInfo) *NullableGpgKeyInfo {
	return &NullableGpgKeyInfo{value: val, isSet: true}
}

func (v NullableGpgKeyInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGpgKeyInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


