/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ApplyPatchPatchSetInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplyPatchPatchSetInput{}

// ApplyPatchPatchSetInput struct for ApplyPatchPatchSetInput
type ApplyPatchPatchSetInput struct {
	Patch *ApplyPatchInput `json:"patch,omitempty"`
	CommitMessage *string `json:"commit_message,omitempty"`
	Base *string `json:"base,omitempty"`
	Author *AccountInput `json:"author,omitempty"`
	ResponseFormatOptions []ListChangesOption `json:"response_format_options,omitempty"`
	Amend *bool `json:"amend,omitempty"`
}

// NewApplyPatchPatchSetInput instantiates a new ApplyPatchPatchSetInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyPatchPatchSetInput() *ApplyPatchPatchSetInput {
	this := ApplyPatchPatchSetInput{}
	return &this
}

// NewApplyPatchPatchSetInputWithDefaults instantiates a new ApplyPatchPatchSetInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyPatchPatchSetInputWithDefaults() *ApplyPatchPatchSetInput {
	this := ApplyPatchPatchSetInput{}
	return &this
}

// GetPatch returns the Patch field value if set, zero value otherwise.
func (o *ApplyPatchPatchSetInput) GetPatch() ApplyPatchInput {
	if o == nil || IsNil(o.Patch) {
		var ret ApplyPatchInput
		return ret
	}
	return *o.Patch
}

// GetPatchOk returns a tuple with the Patch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyPatchPatchSetInput) GetPatchOk() (*ApplyPatchInput, bool) {
	if o == nil || IsNil(o.Patch) {
		return nil, false
	}
	return o.Patch, true
}

// HasPatch returns a boolean if a field has been set.
func (o *ApplyPatchPatchSetInput) HasPatch() bool {
	if o != nil && !IsNil(o.Patch) {
		return true
	}

	return false
}

// SetPatch gets a reference to the given ApplyPatchInput and assigns it to the Patch field.
func (o *ApplyPatchPatchSetInput) SetPatch(v ApplyPatchInput) {
	o.Patch = &v
}

// GetCommitMessage returns the CommitMessage field value if set, zero value otherwise.
func (o *ApplyPatchPatchSetInput) GetCommitMessage() string {
	if o == nil || IsNil(o.CommitMessage) {
		var ret string
		return ret
	}
	return *o.CommitMessage
}

// GetCommitMessageOk returns a tuple with the CommitMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyPatchPatchSetInput) GetCommitMessageOk() (*string, bool) {
	if o == nil || IsNil(o.CommitMessage) {
		return nil, false
	}
	return o.CommitMessage, true
}

// HasCommitMessage returns a boolean if a field has been set.
func (o *ApplyPatchPatchSetInput) HasCommitMessage() bool {
	if o != nil && !IsNil(o.CommitMessage) {
		return true
	}

	return false
}

// SetCommitMessage gets a reference to the given string and assigns it to the CommitMessage field.
func (o *ApplyPatchPatchSetInput) SetCommitMessage(v string) {
	o.CommitMessage = &v
}

// GetBase returns the Base field value if set, zero value otherwise.
func (o *ApplyPatchPatchSetInput) GetBase() string {
	if o == nil || IsNil(o.Base) {
		var ret string
		return ret
	}
	return *o.Base
}

// GetBaseOk returns a tuple with the Base field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyPatchPatchSetInput) GetBaseOk() (*string, bool) {
	if o == nil || IsNil(o.Base) {
		return nil, false
	}
	return o.Base, true
}

// HasBase returns a boolean if a field has been set.
func (o *ApplyPatchPatchSetInput) HasBase() bool {
	if o != nil && !IsNil(o.Base) {
		return true
	}

	return false
}

// SetBase gets a reference to the given string and assigns it to the Base field.
func (o *ApplyPatchPatchSetInput) SetBase(v string) {
	o.Base = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *ApplyPatchPatchSetInput) GetAuthor() AccountInput {
	if o == nil || IsNil(o.Author) {
		var ret AccountInput
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyPatchPatchSetInput) GetAuthorOk() (*AccountInput, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *ApplyPatchPatchSetInput) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given AccountInput and assigns it to the Author field.
func (o *ApplyPatchPatchSetInput) SetAuthor(v AccountInput) {
	o.Author = &v
}

// GetResponseFormatOptions returns the ResponseFormatOptions field value if set, zero value otherwise.
func (o *ApplyPatchPatchSetInput) GetResponseFormatOptions() []ListChangesOption {
	if o == nil || IsNil(o.ResponseFormatOptions) {
		var ret []ListChangesOption
		return ret
	}
	return o.ResponseFormatOptions
}

// GetResponseFormatOptionsOk returns a tuple with the ResponseFormatOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyPatchPatchSetInput) GetResponseFormatOptionsOk() ([]ListChangesOption, bool) {
	if o == nil || IsNil(o.ResponseFormatOptions) {
		return nil, false
	}
	return o.ResponseFormatOptions, true
}

// HasResponseFormatOptions returns a boolean if a field has been set.
func (o *ApplyPatchPatchSetInput) HasResponseFormatOptions() bool {
	if o != nil && !IsNil(o.ResponseFormatOptions) {
		return true
	}

	return false
}

// SetResponseFormatOptions gets a reference to the given []ListChangesOption and assigns it to the ResponseFormatOptions field.
func (o *ApplyPatchPatchSetInput) SetResponseFormatOptions(v []ListChangesOption) {
	o.ResponseFormatOptions = v
}

// GetAmend returns the Amend field value if set, zero value otherwise.
func (o *ApplyPatchPatchSetInput) GetAmend() bool {
	if o == nil || IsNil(o.Amend) {
		var ret bool
		return ret
	}
	return *o.Amend
}

// GetAmendOk returns a tuple with the Amend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyPatchPatchSetInput) GetAmendOk() (*bool, bool) {
	if o == nil || IsNil(o.Amend) {
		return nil, false
	}
	return o.Amend, true
}

// HasAmend returns a boolean if a field has been set.
func (o *ApplyPatchPatchSetInput) HasAmend() bool {
	if o != nil && !IsNil(o.Amend) {
		return true
	}

	return false
}

// SetAmend gets a reference to the given bool and assigns it to the Amend field.
func (o *ApplyPatchPatchSetInput) SetAmend(v bool) {
	o.Amend = &v
}

func (o ApplyPatchPatchSetInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyPatchPatchSetInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Patch) {
		toSerialize["patch"] = o.Patch
	}
	if !IsNil(o.CommitMessage) {
		toSerialize["commit_message"] = o.CommitMessage
	}
	if !IsNil(o.Base) {
		toSerialize["base"] = o.Base
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.ResponseFormatOptions) {
		toSerialize["response_format_options"] = o.ResponseFormatOptions
	}
	if !IsNil(o.Amend) {
		toSerialize["amend"] = o.Amend
	}
	return toSerialize, nil
}

type NullableApplyPatchPatchSetInput struct {
	value *ApplyPatchPatchSetInput
	isSet bool
}

func (v NullableApplyPatchPatchSetInput) Get() *ApplyPatchPatchSetInput {
	return v.value
}

func (v *NullableApplyPatchPatchSetInput) Set(val *ApplyPatchPatchSetInput) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyPatchPatchSetInput) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyPatchPatchSetInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyPatchPatchSetInput(val *ApplyPatchPatchSetInput) *NullableApplyPatchPatchSetInput {
	return &NullableApplyPatchPatchSetInput{value: val, isSet: true}
}

func (v NullableApplyPatchPatchSetInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyPatchPatchSetInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


