/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
	"fmt"
)

// SubmitType the model 'SubmitType'
type SubmitType string

// List of SubmitType
const (
	SUBMITTYPE_INHERIT SubmitType = "INHERIT"
	SUBMITTYPE_FAST_FORWARD_ONLY SubmitType = "FAST_FORWARD_ONLY"
	SUBMITTYPE_MERGE_IF_NECESSARY SubmitType = "MERGE_IF_NECESSARY"
	SUBMITTYPE_REBASE_IF_NECESSARY SubmitType = "REBASE_IF_NECESSARY"
	SUBMITTYPE_REBASE_ALWAYS SubmitType = "REBASE_ALWAYS"
	SUBMITTYPE_MERGE_ALWAYS SubmitType = "MERGE_ALWAYS"
	SUBMITTYPE_CHERRY_PICK SubmitType = "CHERRY_PICK"
)

// All allowed values of SubmitType enum
var AllowedSubmitTypeEnumValues = []SubmitType{
	"INHERIT",
	"FAST_FORWARD_ONLY",
	"MERGE_IF_NECESSARY",
	"REBASE_IF_NECESSARY",
	"REBASE_ALWAYS",
	"MERGE_ALWAYS",
	"CHERRY_PICK",
}

func (v *SubmitType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SubmitType(value)
	for _, existing := range AllowedSubmitTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SubmitType", value)
}

// NewSubmitTypeFromValue returns a pointer to a valid SubmitType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSubmitTypeFromValue(v string) (*SubmitType, error) {
	ev := SubmitType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SubmitType: valid values are %v", v, AllowedSubmitTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SubmitType) IsValid() bool {
	for _, existing := range AllowedSubmitTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SubmitType value
func (v SubmitType) Ptr() *SubmitType {
	return &v
}

type NullableSubmitType struct {
	value *SubmitType
	isSet bool
}

func (v NullableSubmitType) Get() *SubmitType {
	return v.value
}

func (v *NullableSubmitType) Set(val *SubmitType) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitType) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitType(val *SubmitType) *NullableSubmitType {
	return &NullableSubmitType{value: val, isSet: true}
}

func (v NullableSubmitType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

