/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the GitPerson type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitPerson{}

// GitPerson struct for GitPerson
type GitPerson struct {
	// The name of the author/committer.
	Name *string `json:"name,omitempty"`
	// The email address of the author/committer.
	Email *string `json:"email,omitempty"`
	// The timestamp of when this identity was constructed.
	Date *string `json:"date,omitempty"`
	// The timezone offset from UTC of when this identity was constructed.
	Tz *int32 `json:"tz,omitempty"`
}

// NewGitPerson instantiates a new GitPerson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitPerson() *GitPerson {
	this := GitPerson{}
	return &this
}

// NewGitPersonWithDefaults instantiates a new GitPerson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitPersonWithDefaults() *GitPerson {
	this := GitPerson{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GitPerson) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitPerson) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GitPerson) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GitPerson) SetName(v string) {
	o.Name = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *GitPerson) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitPerson) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *GitPerson) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *GitPerson) SetEmail(v string) {
	o.Email = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *GitPerson) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitPerson) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *GitPerson) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *GitPerson) SetDate(v string) {
	o.Date = &v
}

// GetTz returns the Tz field value if set, zero value otherwise.
func (o *GitPerson) GetTz() int32 {
	if o == nil || IsNil(o.Tz) {
		var ret int32
		return ret
	}
	return *o.Tz
}

// GetTzOk returns a tuple with the Tz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitPerson) GetTzOk() (*int32, bool) {
	if o == nil || IsNil(o.Tz) {
		return nil, false
	}
	return o.Tz, true
}

// HasTz returns a boolean if a field has been set.
func (o *GitPerson) HasTz() bool {
	if o != nil && !IsNil(o.Tz) {
		return true
	}

	return false
}

// SetTz gets a reference to the given int32 and assigns it to the Tz field.
func (o *GitPerson) SetTz(v int32) {
	o.Tz = &v
}

func (o GitPerson) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitPerson) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Tz) {
		toSerialize["tz"] = o.Tz
	}
	return toSerialize, nil
}

type NullableGitPerson struct {
	value *GitPerson
	isSet bool
}

func (v NullableGitPerson) Get() *GitPerson {
	return v.value
}

func (v *NullableGitPerson) Set(val *GitPerson) {
	v.value = val
	v.isSet = true
}

func (v NullableGitPerson) IsSet() bool {
	return v.isSet
}

func (v *NullableGitPerson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitPerson(val *GitPerson) *NullableGitPerson {
	return &NullableGitPerson{value: val, isSet: true}
}

func (v NullableGitPerson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitPerson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


