/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the GerritInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GerritInfo{}

// GerritInfo struct for GerritInfo
type GerritInfo struct {
	AllProjects *string `json:"all_projects,omitempty"`
	AllUsers *string `json:"all_users,omitempty"`
	// Whether documentation search is available.
	DocSearch *bool `json:"doc_search,omitempty"`
	// Custom base URL where Gerrit server documentation is located. (Documentation may still be available at /Documentation relative to the Gerrit base path even if this value is unset.)
	DocUrl *string `json:"doc_url,omitempty"`
	// Whether to enable the web UI for editing GPG keys.
	EditGpgKeys *bool `json:"edit_gpg_keys,omitempty"`
	// URL to report bugs.
	ReportBugUrl *string `json:"report_bug_url,omitempty"`
	PrimaryWeblinkName *string `json:"primary_weblink_name,omitempty"`
	// Short identifier for this Gerrit installation.
	InstanceId *string `json:"instance_id,omitempty"`
	// Name of the default branch to use on the project creation.
	DefaultBranch *string `json:"default_branch,omitempty"`
	// Whether the instance supports filtering projects by state.
	ProjectStatePredicateEnabled *bool `json:"project_state_predicate_enabled,omitempty"`
}

// NewGerritInfo instantiates a new GerritInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGerritInfo() *GerritInfo {
	this := GerritInfo{}
	return &this
}

// NewGerritInfoWithDefaults instantiates a new GerritInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGerritInfoWithDefaults() *GerritInfo {
	this := GerritInfo{}
	return &this
}

// GetAllProjects returns the AllProjects field value if set, zero value otherwise.
func (o *GerritInfo) GetAllProjects() string {
	if o == nil || IsNil(o.AllProjects) {
		var ret string
		return ret
	}
	return *o.AllProjects
}

// GetAllProjectsOk returns a tuple with the AllProjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GerritInfo) GetAllProjectsOk() (*string, bool) {
	if o == nil || IsNil(o.AllProjects) {
		return nil, false
	}
	return o.AllProjects, true
}

// HasAllProjects returns a boolean if a field has been set.
func (o *GerritInfo) HasAllProjects() bool {
	if o != nil && !IsNil(o.AllProjects) {
		return true
	}

	return false
}

// SetAllProjects gets a reference to the given string and assigns it to the AllProjects field.
func (o *GerritInfo) SetAllProjects(v string) {
	o.AllProjects = &v
}

// GetAllUsers returns the AllUsers field value if set, zero value otherwise.
func (o *GerritInfo) GetAllUsers() string {
	if o == nil || IsNil(o.AllUsers) {
		var ret string
		return ret
	}
	return *o.AllUsers
}

// GetAllUsersOk returns a tuple with the AllUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GerritInfo) GetAllUsersOk() (*string, bool) {
	if o == nil || IsNil(o.AllUsers) {
		return nil, false
	}
	return o.AllUsers, true
}

// HasAllUsers returns a boolean if a field has been set.
func (o *GerritInfo) HasAllUsers() bool {
	if o != nil && !IsNil(o.AllUsers) {
		return true
	}

	return false
}

// SetAllUsers gets a reference to the given string and assigns it to the AllUsers field.
func (o *GerritInfo) SetAllUsers(v string) {
	o.AllUsers = &v
}

// GetDocSearch returns the DocSearch field value if set, zero value otherwise.
func (o *GerritInfo) GetDocSearch() bool {
	if o == nil || IsNil(o.DocSearch) {
		var ret bool
		return ret
	}
	return *o.DocSearch
}

// GetDocSearchOk returns a tuple with the DocSearch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GerritInfo) GetDocSearchOk() (*bool, bool) {
	if o == nil || IsNil(o.DocSearch) {
		return nil, false
	}
	return o.DocSearch, true
}

// HasDocSearch returns a boolean if a field has been set.
func (o *GerritInfo) HasDocSearch() bool {
	if o != nil && !IsNil(o.DocSearch) {
		return true
	}

	return false
}

// SetDocSearch gets a reference to the given bool and assigns it to the DocSearch field.
func (o *GerritInfo) SetDocSearch(v bool) {
	o.DocSearch = &v
}

// GetDocUrl returns the DocUrl field value if set, zero value otherwise.
func (o *GerritInfo) GetDocUrl() string {
	if o == nil || IsNil(o.DocUrl) {
		var ret string
		return ret
	}
	return *o.DocUrl
}

// GetDocUrlOk returns a tuple with the DocUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GerritInfo) GetDocUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DocUrl) {
		return nil, false
	}
	return o.DocUrl, true
}

// HasDocUrl returns a boolean if a field has been set.
func (o *GerritInfo) HasDocUrl() bool {
	if o != nil && !IsNil(o.DocUrl) {
		return true
	}

	return false
}

// SetDocUrl gets a reference to the given string and assigns it to the DocUrl field.
func (o *GerritInfo) SetDocUrl(v string) {
	o.DocUrl = &v
}

// GetEditGpgKeys returns the EditGpgKeys field value if set, zero value otherwise.
func (o *GerritInfo) GetEditGpgKeys() bool {
	if o == nil || IsNil(o.EditGpgKeys) {
		var ret bool
		return ret
	}
	return *o.EditGpgKeys
}

// GetEditGpgKeysOk returns a tuple with the EditGpgKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GerritInfo) GetEditGpgKeysOk() (*bool, bool) {
	if o == nil || IsNil(o.EditGpgKeys) {
		return nil, false
	}
	return o.EditGpgKeys, true
}

// HasEditGpgKeys returns a boolean if a field has been set.
func (o *GerritInfo) HasEditGpgKeys() bool {
	if o != nil && !IsNil(o.EditGpgKeys) {
		return true
	}

	return false
}

// SetEditGpgKeys gets a reference to the given bool and assigns it to the EditGpgKeys field.
func (o *GerritInfo) SetEditGpgKeys(v bool) {
	o.EditGpgKeys = &v
}

// GetReportBugUrl returns the ReportBugUrl field value if set, zero value otherwise.
func (o *GerritInfo) GetReportBugUrl() string {
	if o == nil || IsNil(o.ReportBugUrl) {
		var ret string
		return ret
	}
	return *o.ReportBugUrl
}

// GetReportBugUrlOk returns a tuple with the ReportBugUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GerritInfo) GetReportBugUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ReportBugUrl) {
		return nil, false
	}
	return o.ReportBugUrl, true
}

// HasReportBugUrl returns a boolean if a field has been set.
func (o *GerritInfo) HasReportBugUrl() bool {
	if o != nil && !IsNil(o.ReportBugUrl) {
		return true
	}

	return false
}

// SetReportBugUrl gets a reference to the given string and assigns it to the ReportBugUrl field.
func (o *GerritInfo) SetReportBugUrl(v string) {
	o.ReportBugUrl = &v
}

// GetPrimaryWeblinkName returns the PrimaryWeblinkName field value if set, zero value otherwise.
func (o *GerritInfo) GetPrimaryWeblinkName() string {
	if o == nil || IsNil(o.PrimaryWeblinkName) {
		var ret string
		return ret
	}
	return *o.PrimaryWeblinkName
}

// GetPrimaryWeblinkNameOk returns a tuple with the PrimaryWeblinkName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GerritInfo) GetPrimaryWeblinkNameOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryWeblinkName) {
		return nil, false
	}
	return o.PrimaryWeblinkName, true
}

// HasPrimaryWeblinkName returns a boolean if a field has been set.
func (o *GerritInfo) HasPrimaryWeblinkName() bool {
	if o != nil && !IsNil(o.PrimaryWeblinkName) {
		return true
	}

	return false
}

// SetPrimaryWeblinkName gets a reference to the given string and assigns it to the PrimaryWeblinkName field.
func (o *GerritInfo) SetPrimaryWeblinkName(v string) {
	o.PrimaryWeblinkName = &v
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *GerritInfo) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GerritInfo) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *GerritInfo) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *GerritInfo) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetDefaultBranch returns the DefaultBranch field value if set, zero value otherwise.
func (o *GerritInfo) GetDefaultBranch() string {
	if o == nil || IsNil(o.DefaultBranch) {
		var ret string
		return ret
	}
	return *o.DefaultBranch
}

// GetDefaultBranchOk returns a tuple with the DefaultBranch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GerritInfo) GetDefaultBranchOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultBranch) {
		return nil, false
	}
	return o.DefaultBranch, true
}

// HasDefaultBranch returns a boolean if a field has been set.
func (o *GerritInfo) HasDefaultBranch() bool {
	if o != nil && !IsNil(o.DefaultBranch) {
		return true
	}

	return false
}

// SetDefaultBranch gets a reference to the given string and assigns it to the DefaultBranch field.
func (o *GerritInfo) SetDefaultBranch(v string) {
	o.DefaultBranch = &v
}

// GetProjectStatePredicateEnabled returns the ProjectStatePredicateEnabled field value if set, zero value otherwise.
func (o *GerritInfo) GetProjectStatePredicateEnabled() bool {
	if o == nil || IsNil(o.ProjectStatePredicateEnabled) {
		var ret bool
		return ret
	}
	return *o.ProjectStatePredicateEnabled
}

// GetProjectStatePredicateEnabledOk returns a tuple with the ProjectStatePredicateEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GerritInfo) GetProjectStatePredicateEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ProjectStatePredicateEnabled) {
		return nil, false
	}
	return o.ProjectStatePredicateEnabled, true
}

// HasProjectStatePredicateEnabled returns a boolean if a field has been set.
func (o *GerritInfo) HasProjectStatePredicateEnabled() bool {
	if o != nil && !IsNil(o.ProjectStatePredicateEnabled) {
		return true
	}

	return false
}

// SetProjectStatePredicateEnabled gets a reference to the given bool and assigns it to the ProjectStatePredicateEnabled field.
func (o *GerritInfo) SetProjectStatePredicateEnabled(v bool) {
	o.ProjectStatePredicateEnabled = &v
}

func (o GerritInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GerritInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllProjects) {
		toSerialize["all_projects"] = o.AllProjects
	}
	if !IsNil(o.AllUsers) {
		toSerialize["all_users"] = o.AllUsers
	}
	if !IsNil(o.DocSearch) {
		toSerialize["doc_search"] = o.DocSearch
	}
	if !IsNil(o.DocUrl) {
		toSerialize["doc_url"] = o.DocUrl
	}
	if !IsNil(o.EditGpgKeys) {
		toSerialize["edit_gpg_keys"] = o.EditGpgKeys
	}
	if !IsNil(o.ReportBugUrl) {
		toSerialize["report_bug_url"] = o.ReportBugUrl
	}
	if !IsNil(o.PrimaryWeblinkName) {
		toSerialize["primary_weblink_name"] = o.PrimaryWeblinkName
	}
	if !IsNil(o.InstanceId) {
		toSerialize["instance_id"] = o.InstanceId
	}
	if !IsNil(o.DefaultBranch) {
		toSerialize["default_branch"] = o.DefaultBranch
	}
	if !IsNil(o.ProjectStatePredicateEnabled) {
		toSerialize["project_state_predicate_enabled"] = o.ProjectStatePredicateEnabled
	}
	return toSerialize, nil
}

type NullableGerritInfo struct {
	value *GerritInfo
	isSet bool
}

func (v NullableGerritInfo) Get() *GerritInfo {
	return v.value
}

func (v *NullableGerritInfo) Set(val *GerritInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGerritInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGerritInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGerritInfo(val *GerritInfo) *NullableGerritInfo {
	return &NullableGerritInfo{value: val, isSet: true}
}

func (v NullableGerritInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGerritInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


