/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the LabelDefinitionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelDefinitionInfo{}

// LabelDefinitionInfo struct for LabelDefinitionInfo
type LabelDefinitionInfo struct {
	// The name of the label.
	Name *string `json:"name,omitempty"`
	// The description of the label.
	Description *string `json:"description,omitempty"`
	// The name of the project in which this label is defined. Not set for globally defined labels.
	ProjectName *string `json:"project_name,omitempty"`
	// The function of the label (can be MaxWithBlock, AnyWithBlock, MaxNoBlock, NoBlock, NoOp and PatchSetLock.
	Function *string `json:"function,omitempty"`
	// The values of the label as a map of label value to value description. The label values are formatted strings, e.g. \"+1\" instead of \"1\", \" 0\" instead of \"0\".
	Values map[string]string `json:"values,omitempty"`
	// The default value of the label (as integer).
	DefaultValue *int32 `json:"default_value,omitempty"`
	// A list of branches for which the label applies. A branch can be a ref, a ref pattern or a regular expression. If not set, the label applies for all branches.
	Branches []string `json:"branches,omitempty"`
	// Whether this label can be overridden by child projects.
	CanOverride *bool `json:"can_override,omitempty"`
	// See copyCondition.
	CopyCondition *string `json:"copy_condition,omitempty"`
	// Whether allowPostSubmit is set on the label.
	AllowPostSubmit *bool `json:"allow_post_submit,omitempty"`
	// Whether ignoreSelfApproval is set on the label.
	IgnoreSelfApproval *bool `json:"ignore_self_approval,omitempty"`
}

// NewLabelDefinitionInfo instantiates a new LabelDefinitionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelDefinitionInfo() *LabelDefinitionInfo {
	this := LabelDefinitionInfo{}
	return &this
}

// NewLabelDefinitionInfoWithDefaults instantiates a new LabelDefinitionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelDefinitionInfoWithDefaults() *LabelDefinitionInfo {
	this := LabelDefinitionInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LabelDefinitionInfo) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *LabelDefinitionInfo) SetDescription(v string) {
	o.Description = &v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *LabelDefinitionInfo) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetFunction returns the Function field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetFunction() string {
	if o == nil || IsNil(o.Function) {
		var ret string
		return ret
	}
	return *o.Function
}

// GetFunctionOk returns a tuple with the Function field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetFunctionOk() (*string, bool) {
	if o == nil || IsNil(o.Function) {
		return nil, false
	}
	return o.Function, true
}

// HasFunction returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasFunction() bool {
	if o != nil && !IsNil(o.Function) {
		return true
	}

	return false
}

// SetFunction gets a reference to the given string and assigns it to the Function field.
func (o *LabelDefinitionInfo) SetFunction(v string) {
	o.Function = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetValues() map[string]string {
	if o == nil || IsNil(o.Values) {
		var ret map[string]string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetValuesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Values) {
		return map[string]string{}, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]string and assigns it to the Values field.
func (o *LabelDefinitionInfo) SetValues(v map[string]string) {
	o.Values = v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetDefaultValue() int32 {
	if o == nil || IsNil(o.DefaultValue) {
		var ret int32
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetDefaultValueOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given int32 and assigns it to the DefaultValue field.
func (o *LabelDefinitionInfo) SetDefaultValue(v int32) {
	o.DefaultValue = &v
}

// GetBranches returns the Branches field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetBranches() []string {
	if o == nil || IsNil(o.Branches) {
		var ret []string
		return ret
	}
	return o.Branches
}

// GetBranchesOk returns a tuple with the Branches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetBranchesOk() ([]string, bool) {
	if o == nil || IsNil(o.Branches) {
		return nil, false
	}
	return o.Branches, true
}

// HasBranches returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasBranches() bool {
	if o != nil && !IsNil(o.Branches) {
		return true
	}

	return false
}

// SetBranches gets a reference to the given []string and assigns it to the Branches field.
func (o *LabelDefinitionInfo) SetBranches(v []string) {
	o.Branches = v
}

// GetCanOverride returns the CanOverride field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetCanOverride() bool {
	if o == nil || IsNil(o.CanOverride) {
		var ret bool
		return ret
	}
	return *o.CanOverride
}

// GetCanOverrideOk returns a tuple with the CanOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetCanOverrideOk() (*bool, bool) {
	if o == nil || IsNil(o.CanOverride) {
		return nil, false
	}
	return o.CanOverride, true
}

// HasCanOverride returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasCanOverride() bool {
	if o != nil && !IsNil(o.CanOverride) {
		return true
	}

	return false
}

// SetCanOverride gets a reference to the given bool and assigns it to the CanOverride field.
func (o *LabelDefinitionInfo) SetCanOverride(v bool) {
	o.CanOverride = &v
}

// GetCopyCondition returns the CopyCondition field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetCopyCondition() string {
	if o == nil || IsNil(o.CopyCondition) {
		var ret string
		return ret
	}
	return *o.CopyCondition
}

// GetCopyConditionOk returns a tuple with the CopyCondition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetCopyConditionOk() (*string, bool) {
	if o == nil || IsNil(o.CopyCondition) {
		return nil, false
	}
	return o.CopyCondition, true
}

// HasCopyCondition returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasCopyCondition() bool {
	if o != nil && !IsNil(o.CopyCondition) {
		return true
	}

	return false
}

// SetCopyCondition gets a reference to the given string and assigns it to the CopyCondition field.
func (o *LabelDefinitionInfo) SetCopyCondition(v string) {
	o.CopyCondition = &v
}

// GetAllowPostSubmit returns the AllowPostSubmit field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetAllowPostSubmit() bool {
	if o == nil || IsNil(o.AllowPostSubmit) {
		var ret bool
		return ret
	}
	return *o.AllowPostSubmit
}

// GetAllowPostSubmitOk returns a tuple with the AllowPostSubmit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetAllowPostSubmitOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowPostSubmit) {
		return nil, false
	}
	return o.AllowPostSubmit, true
}

// HasAllowPostSubmit returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasAllowPostSubmit() bool {
	if o != nil && !IsNil(o.AllowPostSubmit) {
		return true
	}

	return false
}

// SetAllowPostSubmit gets a reference to the given bool and assigns it to the AllowPostSubmit field.
func (o *LabelDefinitionInfo) SetAllowPostSubmit(v bool) {
	o.AllowPostSubmit = &v
}

// GetIgnoreSelfApproval returns the IgnoreSelfApproval field value if set, zero value otherwise.
func (o *LabelDefinitionInfo) GetIgnoreSelfApproval() bool {
	if o == nil || IsNil(o.IgnoreSelfApproval) {
		var ret bool
		return ret
	}
	return *o.IgnoreSelfApproval
}

// GetIgnoreSelfApprovalOk returns a tuple with the IgnoreSelfApproval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionInfo) GetIgnoreSelfApprovalOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreSelfApproval) {
		return nil, false
	}
	return o.IgnoreSelfApproval, true
}

// HasIgnoreSelfApproval returns a boolean if a field has been set.
func (o *LabelDefinitionInfo) HasIgnoreSelfApproval() bool {
	if o != nil && !IsNil(o.IgnoreSelfApproval) {
		return true
	}

	return false
}

// SetIgnoreSelfApproval gets a reference to the given bool and assigns it to the IgnoreSelfApproval field.
func (o *LabelDefinitionInfo) SetIgnoreSelfApproval(v bool) {
	o.IgnoreSelfApproval = &v
}

func (o LabelDefinitionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelDefinitionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ProjectName) {
		toSerialize["project_name"] = o.ProjectName
	}
	if !IsNil(o.Function) {
		toSerialize["function"] = o.Function
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["default_value"] = o.DefaultValue
	}
	if !IsNil(o.Branches) {
		toSerialize["branches"] = o.Branches
	}
	if !IsNil(o.CanOverride) {
		toSerialize["can_override"] = o.CanOverride
	}
	if !IsNil(o.CopyCondition) {
		toSerialize["copy_condition"] = o.CopyCondition
	}
	if !IsNil(o.AllowPostSubmit) {
		toSerialize["allow_post_submit"] = o.AllowPostSubmit
	}
	if !IsNil(o.IgnoreSelfApproval) {
		toSerialize["ignore_self_approval"] = o.IgnoreSelfApproval
	}
	return toSerialize, nil
}

type NullableLabelDefinitionInfo struct {
	value *LabelDefinitionInfo
	isSet bool
}

func (v NullableLabelDefinitionInfo) Get() *LabelDefinitionInfo {
	return v.value
}

func (v *NullableLabelDefinitionInfo) Set(val *LabelDefinitionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelDefinitionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelDefinitionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelDefinitionInfo(val *LabelDefinitionInfo) *NullableLabelDefinitionInfo {
	return &NullableLabelDefinitionInfo{value: val, isSet: true}
}

func (v NullableLabelDefinitionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelDefinitionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


