/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the UsernameInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsernameInput{}

// UsernameInput struct for UsernameInput
type UsernameInput struct {
	Username *string `json:"username,omitempty"`
}

// NewUsernameInput instantiates a new UsernameInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsernameInput() *UsernameInput {
	this := UsernameInput{}
	return &this
}

// NewUsernameInputWithDefaults instantiates a new UsernameInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsernameInputWithDefaults() *UsernameInput {
	this := UsernameInput{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *UsernameInput) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsernameInput) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *UsernameInput) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *UsernameInput) SetUsername(v string) {
	o.Username = &v
}

func (o UsernameInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsernameInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableUsernameInput struct {
	value *UsernameInput
	isSet bool
}

func (v NullableUsernameInput) Get() *UsernameInput {
	return v.value
}

func (v *NullableUsernameInput) Set(val *UsernameInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUsernameInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUsernameInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsernameInput(val *UsernameInput) *NullableUsernameInput {
	return &NullableUsernameInput{value: val, isSet: true}
}

func (v NullableUsernameInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsernameInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


