/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
	"fmt"
)

// Whitespace the model 'Whitespace'
type Whitespace string

// List of Whitespace
const (
	WHITESPACE_IGNORE_NONE Whitespace = "IGNORE_NONE"
	WHITESPACE_IGNORE_TRAILING Whitespace = "IGNORE_TRAILING"
	WHITESPACE_IGNORE_LEADING_AND_TRAILING Whitespace = "IGNORE_LEADING_AND_TRAILING"
	WHITESPACE_IGNORE_ALL Whitespace = "IGNORE_ALL"
)

// All allowed values of Whitespace enum
var AllowedWhitespaceEnumValues = []Whitespace{
	"IGNORE_NONE",
	"IGNORE_TRAILING",
	"IGNORE_LEADING_AND_TRAILING",
	"IGNORE_ALL",
}

func (v *Whitespace) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Whitespace(value)
	for _, existing := range AllowedWhitespaceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Whitespace", value)
}

// NewWhitespaceFromValue returns a pointer to a valid Whitespace
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWhitespaceFromValue(v string) (*Whitespace, error) {
	ev := Whitespace(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Whitespace: valid values are %v", v, AllowedWhitespaceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Whitespace) IsValid() bool {
	for _, existing := range AllowedWhitespaceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Whitespace value
func (v Whitespace) Ptr() *Whitespace {
	return &v
}

type NullableWhitespace struct {
	value *Whitespace
	isSet bool
}

func (v NullableWhitespace) Get() *Whitespace {
	return v.value
}

func (v *NullableWhitespace) Set(val *Whitespace) {
	v.value = val
	v.isSet = true
}

func (v NullableWhitespace) IsSet() bool {
	return v.isSet
}

func (v *NullableWhitespace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhitespace(val *Whitespace) *NullableWhitespace {
	return &NullableWhitespace{value: val, isSet: true}
}

func (v NullableWhitespace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhitespace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

