/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the InstallPluginInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstallPluginInput{}

// InstallPluginInput struct for InstallPluginInput
type InstallPluginInput struct {
	Url *string `json:"url,omitempty"`
	Raw map[string]interface{} `json:"raw,omitempty"`
}

// NewInstallPluginInput instantiates a new InstallPluginInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstallPluginInput() *InstallPluginInput {
	this := InstallPluginInput{}
	return &this
}

// NewInstallPluginInputWithDefaults instantiates a new InstallPluginInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstallPluginInputWithDefaults() *InstallPluginInput {
	this := InstallPluginInput{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *InstallPluginInput) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstallPluginInput) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *InstallPluginInput) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *InstallPluginInput) SetUrl(v string) {
	o.Url = &v
}

// GetRaw returns the Raw field value if set, zero value otherwise.
func (o *InstallPluginInput) GetRaw() map[string]interface{} {
	if o == nil || IsNil(o.Raw) {
		var ret map[string]interface{}
		return ret
	}
	return o.Raw
}

// GetRawOk returns a tuple with the Raw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstallPluginInput) GetRawOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Raw) {
		return map[string]interface{}{}, false
	}
	return o.Raw, true
}

// HasRaw returns a boolean if a field has been set.
func (o *InstallPluginInput) HasRaw() bool {
	if o != nil && !IsNil(o.Raw) {
		return true
	}

	return false
}

// SetRaw gets a reference to the given map[string]interface{} and assigns it to the Raw field.
func (o *InstallPluginInput) SetRaw(v map[string]interface{}) {
	o.Raw = v
}

func (o InstallPluginInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstallPluginInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Raw) {
		toSerialize["raw"] = o.Raw
	}
	return toSerialize, nil
}

type NullableInstallPluginInput struct {
	value *InstallPluginInput
	isSet bool
}

func (v NullableInstallPluginInput) Get() *InstallPluginInput {
	return v.value
}

func (v *NullableInstallPluginInput) Set(val *InstallPluginInput) {
	v.value = val
	v.isSet = true
}

func (v NullableInstallPluginInput) IsSet() bool {
	return v.isSet
}

func (v *NullableInstallPluginInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstallPluginInput(val *InstallPluginInput) *NullableInstallPluginInput {
	return &NullableInstallPluginInput{value: val, isSet: true}
}

func (v NullableInstallPluginInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstallPluginInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


