/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the SuggestedReviewerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuggestedReviewerInfo{}

// SuggestedReviewerInfo struct for SuggestedReviewerInfo
type SuggestedReviewerInfo struct {
	// An AccountInfo entity, if the suggestion is an account.
	Account *AccountInfo `json:"account,omitempty"`
	// A GroupBaseInfo entity, if the suggestion is a group.
	Group *GroupBaseInfo `json:"group,omitempty"`
	// The total number of accounts in the suggestion. This is 1 if account is present. If group is present, the total number of accounts that are members of the group is returned (this count includes members of nested groups).
	Count *int32 `json:"count,omitempty"`
	// True if group is present and count is above the threshold where the confirmed flag must be passed to add the group as a reviewer.
	Confirm *bool `json:"confirm,omitempty"`
}

// NewSuggestedReviewerInfo instantiates a new SuggestedReviewerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuggestedReviewerInfo() *SuggestedReviewerInfo {
	this := SuggestedReviewerInfo{}
	return &this
}

// NewSuggestedReviewerInfoWithDefaults instantiates a new SuggestedReviewerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuggestedReviewerInfoWithDefaults() *SuggestedReviewerInfo {
	this := SuggestedReviewerInfo{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *SuggestedReviewerInfo) GetAccount() AccountInfo {
	if o == nil || IsNil(o.Account) {
		var ret AccountInfo
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuggestedReviewerInfo) GetAccountOk() (*AccountInfo, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *SuggestedReviewerInfo) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given AccountInfo and assigns it to the Account field.
func (o *SuggestedReviewerInfo) SetAccount(v AccountInfo) {
	o.Account = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *SuggestedReviewerInfo) GetGroup() GroupBaseInfo {
	if o == nil || IsNil(o.Group) {
		var ret GroupBaseInfo
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuggestedReviewerInfo) GetGroupOk() (*GroupBaseInfo, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *SuggestedReviewerInfo) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given GroupBaseInfo and assigns it to the Group field.
func (o *SuggestedReviewerInfo) SetGroup(v GroupBaseInfo) {
	o.Group = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *SuggestedReviewerInfo) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuggestedReviewerInfo) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *SuggestedReviewerInfo) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *SuggestedReviewerInfo) SetCount(v int32) {
	o.Count = &v
}

// GetConfirm returns the Confirm field value if set, zero value otherwise.
func (o *SuggestedReviewerInfo) GetConfirm() bool {
	if o == nil || IsNil(o.Confirm) {
		var ret bool
		return ret
	}
	return *o.Confirm
}

// GetConfirmOk returns a tuple with the Confirm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuggestedReviewerInfo) GetConfirmOk() (*bool, bool) {
	if o == nil || IsNil(o.Confirm) {
		return nil, false
	}
	return o.Confirm, true
}

// HasConfirm returns a boolean if a field has been set.
func (o *SuggestedReviewerInfo) HasConfirm() bool {
	if o != nil && !IsNil(o.Confirm) {
		return true
	}

	return false
}

// SetConfirm gets a reference to the given bool and assigns it to the Confirm field.
func (o *SuggestedReviewerInfo) SetConfirm(v bool) {
	o.Confirm = &v
}

func (o SuggestedReviewerInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuggestedReviewerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Confirm) {
		toSerialize["confirm"] = o.Confirm
	}
	return toSerialize, nil
}

type NullableSuggestedReviewerInfo struct {
	value *SuggestedReviewerInfo
	isSet bool
}

func (v NullableSuggestedReviewerInfo) Get() *SuggestedReviewerInfo {
	return v.value
}

func (v *NullableSuggestedReviewerInfo) Set(val *SuggestedReviewerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSuggestedReviewerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSuggestedReviewerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuggestedReviewerInfo(val *SuggestedReviewerInfo) *NullableSuggestedReviewerInfo {
	return &NullableSuggestedReviewerInfo{value: val, isSet: true}
}

func (v NullableSuggestedReviewerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuggestedReviewerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


