/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the BatchSubmitRequirementInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchSubmitRequirementInput{}

// BatchSubmitRequirementInput struct for BatchSubmitRequirementInput
type BatchSubmitRequirementInput struct {
	// Message that should be used to commit the submit requirements updates in the project.config file to the refs/meta/config branch.
	CommitMessage *string `json:"commit_message,omitempty"`
	// List of submit requirements that should be deleted.
	Delete []string `json:"delete,omitempty"`
	// List of SubmitRequirementInput entities that describe submit requirements that should be created.
	Create []SubmitRequirementInput `json:"create,omitempty"`
	// Map of submit requirement names to SubmitRequirementInput entities that describe the updates that should be done for the submit requirements. The given inputs must set all properties (including those that are not being changed).
	Update map[string]SubmitRequirementInput `json:"update,omitempty"`
}

// NewBatchSubmitRequirementInput instantiates a new BatchSubmitRequirementInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchSubmitRequirementInput() *BatchSubmitRequirementInput {
	this := BatchSubmitRequirementInput{}
	return &this
}

// NewBatchSubmitRequirementInputWithDefaults instantiates a new BatchSubmitRequirementInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchSubmitRequirementInputWithDefaults() *BatchSubmitRequirementInput {
	this := BatchSubmitRequirementInput{}
	return &this
}

// GetCommitMessage returns the CommitMessage field value if set, zero value otherwise.
func (o *BatchSubmitRequirementInput) GetCommitMessage() string {
	if o == nil || IsNil(o.CommitMessage) {
		var ret string
		return ret
	}
	return *o.CommitMessage
}

// GetCommitMessageOk returns a tuple with the CommitMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchSubmitRequirementInput) GetCommitMessageOk() (*string, bool) {
	if o == nil || IsNil(o.CommitMessage) {
		return nil, false
	}
	return o.CommitMessage, true
}

// HasCommitMessage returns a boolean if a field has been set.
func (o *BatchSubmitRequirementInput) HasCommitMessage() bool {
	if o != nil && !IsNil(o.CommitMessage) {
		return true
	}

	return false
}

// SetCommitMessage gets a reference to the given string and assigns it to the CommitMessage field.
func (o *BatchSubmitRequirementInput) SetCommitMessage(v string) {
	o.CommitMessage = &v
}

// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *BatchSubmitRequirementInput) GetDelete() []string {
	if o == nil || IsNil(o.Delete) {
		var ret []string
		return ret
	}
	return o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchSubmitRequirementInput) GetDeleteOk() ([]string, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *BatchSubmitRequirementInput) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given []string and assigns it to the Delete field.
func (o *BatchSubmitRequirementInput) SetDelete(v []string) {
	o.Delete = v
}

// GetCreate returns the Create field value if set, zero value otherwise.
func (o *BatchSubmitRequirementInput) GetCreate() []SubmitRequirementInput {
	if o == nil || IsNil(o.Create) {
		var ret []SubmitRequirementInput
		return ret
	}
	return o.Create
}

// GetCreateOk returns a tuple with the Create field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchSubmitRequirementInput) GetCreateOk() ([]SubmitRequirementInput, bool) {
	if o == nil || IsNil(o.Create) {
		return nil, false
	}
	return o.Create, true
}

// HasCreate returns a boolean if a field has been set.
func (o *BatchSubmitRequirementInput) HasCreate() bool {
	if o != nil && !IsNil(o.Create) {
		return true
	}

	return false
}

// SetCreate gets a reference to the given []SubmitRequirementInput and assigns it to the Create field.
func (o *BatchSubmitRequirementInput) SetCreate(v []SubmitRequirementInput) {
	o.Create = v
}

// GetUpdate returns the Update field value if set, zero value otherwise.
func (o *BatchSubmitRequirementInput) GetUpdate() map[string]SubmitRequirementInput {
	if o == nil || IsNil(o.Update) {
		var ret map[string]SubmitRequirementInput
		return ret
	}
	return o.Update
}

// GetUpdateOk returns a tuple with the Update field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchSubmitRequirementInput) GetUpdateOk() (map[string]SubmitRequirementInput, bool) {
	if o == nil || IsNil(o.Update) {
		return map[string]SubmitRequirementInput{}, false
	}
	return o.Update, true
}

// HasUpdate returns a boolean if a field has been set.
func (o *BatchSubmitRequirementInput) HasUpdate() bool {
	if o != nil && !IsNil(o.Update) {
		return true
	}

	return false
}

// SetUpdate gets a reference to the given map[string]SubmitRequirementInput and assigns it to the Update field.
func (o *BatchSubmitRequirementInput) SetUpdate(v map[string]SubmitRequirementInput) {
	o.Update = v
}

func (o BatchSubmitRequirementInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchSubmitRequirementInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CommitMessage) {
		toSerialize["commit_message"] = o.CommitMessage
	}
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	if !IsNil(o.Create) {
		toSerialize["create"] = o.Create
	}
	if !IsNil(o.Update) {
		toSerialize["update"] = o.Update
	}
	return toSerialize, nil
}

type NullableBatchSubmitRequirementInput struct {
	value *BatchSubmitRequirementInput
	isSet bool
}

func (v NullableBatchSubmitRequirementInput) Get() *BatchSubmitRequirementInput {
	return v.value
}

func (v *NullableBatchSubmitRequirementInput) Set(val *BatchSubmitRequirementInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchSubmitRequirementInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchSubmitRequirementInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchSubmitRequirementInput(val *BatchSubmitRequirementInput) *NullableBatchSubmitRequirementInput {
	return &NullableBatchSubmitRequirementInput{value: val, isSet: true}
}

func (v NullableBatchSubmitRequirementInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchSubmitRequirementInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


