/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the BanCommitInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BanCommitInput{}

// BanCommitInput struct for BanCommitInput
type BanCommitInput struct {
	Commits []string `json:"commits,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

// NewBanCommitInput instantiates a new BanCommitInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBanCommitInput() *BanCommitInput {
	this := BanCommitInput{}
	return &this
}

// NewBanCommitInputWithDefaults instantiates a new BanCommitInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBanCommitInputWithDefaults() *BanCommitInput {
	this := BanCommitInput{}
	return &this
}

// GetCommits returns the Commits field value if set, zero value otherwise.
func (o *BanCommitInput) GetCommits() []string {
	if o == nil || IsNil(o.Commits) {
		var ret []string
		return ret
	}
	return o.Commits
}

// GetCommitsOk returns a tuple with the Commits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BanCommitInput) GetCommitsOk() ([]string, bool) {
	if o == nil || IsNil(o.Commits) {
		return nil, false
	}
	return o.Commits, true
}

// HasCommits returns a boolean if a field has been set.
func (o *BanCommitInput) HasCommits() bool {
	if o != nil && !IsNil(o.Commits) {
		return true
	}

	return false
}

// SetCommits gets a reference to the given []string and assigns it to the Commits field.
func (o *BanCommitInput) SetCommits(v []string) {
	o.Commits = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *BanCommitInput) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BanCommitInput) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *BanCommitInput) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *BanCommitInput) SetReason(v string) {
	o.Reason = &v
}

func (o BanCommitInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BanCommitInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Commits) {
		toSerialize["commits"] = o.Commits
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableBanCommitInput struct {
	value *BanCommitInput
	isSet bool
}

func (v NullableBanCommitInput) Get() *BanCommitInput {
	return v.value
}

func (v *NullableBanCommitInput) Set(val *BanCommitInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBanCommitInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBanCommitInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBanCommitInput(val *BanCommitInput) *NullableBanCommitInput {
	return &NullableBanCommitInput{value: val, isSet: true}
}

func (v NullableBanCommitInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBanCommitInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


