/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the SubmitInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitInput{}

// SubmitInput struct for SubmitInput
type SubmitInput struct {
	WaitForMerge *bool `json:"wait_for_merge,omitempty"`
	// If set, submit the change on behalf of the given user. The value may take any format accepted by the accounts REST API. Using this option requires Submit (On Behalf Of) permission on the branch.
	OnBehalfOf *string `json:"on_behalf_of,omitempty"`
	// Notify handling that defines to whom email notifications should be sent after the change is submitted. + Allowed values are NONE, OWNER, OWNER_REVIEWERS and ALL. + If not set, the default is ALL. + Ignored if a post approval diff is present (i.e.
	Notify *NotifyHandling `json:"notify,omitempty"`
	// Additional information about whom to notify about the update as a map of recipient type to NotifyInfo entity.
	NotifyDetails map[string]NotifyInfo `json:"notify_details,omitempty"`
}

// NewSubmitInput instantiates a new SubmitInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitInput() *SubmitInput {
	this := SubmitInput{}
	return &this
}

// NewSubmitInputWithDefaults instantiates a new SubmitInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitInputWithDefaults() *SubmitInput {
	this := SubmitInput{}
	return &this
}

// GetWaitForMerge returns the WaitForMerge field value if set, zero value otherwise.
func (o *SubmitInput) GetWaitForMerge() bool {
	if o == nil || IsNil(o.WaitForMerge) {
		var ret bool
		return ret
	}
	return *o.WaitForMerge
}

// GetWaitForMergeOk returns a tuple with the WaitForMerge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitInput) GetWaitForMergeOk() (*bool, bool) {
	if o == nil || IsNil(o.WaitForMerge) {
		return nil, false
	}
	return o.WaitForMerge, true
}

// HasWaitForMerge returns a boolean if a field has been set.
func (o *SubmitInput) HasWaitForMerge() bool {
	if o != nil && !IsNil(o.WaitForMerge) {
		return true
	}

	return false
}

// SetWaitForMerge gets a reference to the given bool and assigns it to the WaitForMerge field.
func (o *SubmitInput) SetWaitForMerge(v bool) {
	o.WaitForMerge = &v
}

// GetOnBehalfOf returns the OnBehalfOf field value if set, zero value otherwise.
func (o *SubmitInput) GetOnBehalfOf() string {
	if o == nil || IsNil(o.OnBehalfOf) {
		var ret string
		return ret
	}
	return *o.OnBehalfOf
}

// GetOnBehalfOfOk returns a tuple with the OnBehalfOf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitInput) GetOnBehalfOfOk() (*string, bool) {
	if o == nil || IsNil(o.OnBehalfOf) {
		return nil, false
	}
	return o.OnBehalfOf, true
}

// HasOnBehalfOf returns a boolean if a field has been set.
func (o *SubmitInput) HasOnBehalfOf() bool {
	if o != nil && !IsNil(o.OnBehalfOf) {
		return true
	}

	return false
}

// SetOnBehalfOf gets a reference to the given string and assigns it to the OnBehalfOf field.
func (o *SubmitInput) SetOnBehalfOf(v string) {
	o.OnBehalfOf = &v
}

// GetNotify returns the Notify field value if set, zero value otherwise.
func (o *SubmitInput) GetNotify() NotifyHandling {
	if o == nil || IsNil(o.Notify) {
		var ret NotifyHandling
		return ret
	}
	return *o.Notify
}

// GetNotifyOk returns a tuple with the Notify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitInput) GetNotifyOk() (*NotifyHandling, bool) {
	if o == nil || IsNil(o.Notify) {
		return nil, false
	}
	return o.Notify, true
}

// HasNotify returns a boolean if a field has been set.
func (o *SubmitInput) HasNotify() bool {
	if o != nil && !IsNil(o.Notify) {
		return true
	}

	return false
}

// SetNotify gets a reference to the given NotifyHandling and assigns it to the Notify field.
func (o *SubmitInput) SetNotify(v NotifyHandling) {
	o.Notify = &v
}

// GetNotifyDetails returns the NotifyDetails field value if set, zero value otherwise.
func (o *SubmitInput) GetNotifyDetails() map[string]NotifyInfo {
	if o == nil || IsNil(o.NotifyDetails) {
		var ret map[string]NotifyInfo
		return ret
	}
	return o.NotifyDetails
}

// GetNotifyDetailsOk returns a tuple with the NotifyDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitInput) GetNotifyDetailsOk() (map[string]NotifyInfo, bool) {
	if o == nil || IsNil(o.NotifyDetails) {
		return map[string]NotifyInfo{}, false
	}
	return o.NotifyDetails, true
}

// HasNotifyDetails returns a boolean if a field has been set.
func (o *SubmitInput) HasNotifyDetails() bool {
	if o != nil && !IsNil(o.NotifyDetails) {
		return true
	}

	return false
}

// SetNotifyDetails gets a reference to the given map[string]NotifyInfo and assigns it to the NotifyDetails field.
func (o *SubmitInput) SetNotifyDetails(v map[string]NotifyInfo) {
	o.NotifyDetails = v
}

func (o SubmitInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WaitForMerge) {
		toSerialize["wait_for_merge"] = o.WaitForMerge
	}
	if !IsNil(o.OnBehalfOf) {
		toSerialize["on_behalf_of"] = o.OnBehalfOf
	}
	if !IsNil(o.Notify) {
		toSerialize["notify"] = o.Notify
	}
	if !IsNil(o.NotifyDetails) {
		toSerialize["notify_details"] = o.NotifyDetails
	}
	return toSerialize, nil
}

type NullableSubmitInput struct {
	value *SubmitInput
	isSet bool
}

func (v NullableSubmitInput) Get() *SubmitInput {
	return v.value
}

func (v *NullableSubmitInput) Set(val *SubmitInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitInput(val *SubmitInput) *NullableSubmitInput {
	return &NullableSubmitInput{value: val, isSet: true}
}

func (v NullableSubmitInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


