/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the WebLinkInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebLinkInfo{}

// WebLinkInfo struct for WebLinkInfo
type WebLinkInfo struct {
	// The text to be linkified.
	Name *string `json:"name,omitempty"`
	// Tooltip to show when hovering over the link. Using \"Open in $NAME_OF_EXTERNAL_TOOL\" is a good option here.
	Tooltip *string `json:"tooltip,omitempty"`
	// URL to the icon of the link.
	ImageUrl *string `json:"image_url,omitempty"`
	// The link URL.
	Url *string `json:"url,omitempty"`
}

// NewWebLinkInfo instantiates a new WebLinkInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebLinkInfo() *WebLinkInfo {
	this := WebLinkInfo{}
	return &this
}

// NewWebLinkInfoWithDefaults instantiates a new WebLinkInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebLinkInfoWithDefaults() *WebLinkInfo {
	this := WebLinkInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WebLinkInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebLinkInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WebLinkInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WebLinkInfo) SetName(v string) {
	o.Name = &v
}

// GetTooltip returns the Tooltip field value if set, zero value otherwise.
func (o *WebLinkInfo) GetTooltip() string {
	if o == nil || IsNil(o.Tooltip) {
		var ret string
		return ret
	}
	return *o.Tooltip
}

// GetTooltipOk returns a tuple with the Tooltip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebLinkInfo) GetTooltipOk() (*string, bool) {
	if o == nil || IsNil(o.Tooltip) {
		return nil, false
	}
	return o.Tooltip, true
}

// HasTooltip returns a boolean if a field has been set.
func (o *WebLinkInfo) HasTooltip() bool {
	if o != nil && !IsNil(o.Tooltip) {
		return true
	}

	return false
}

// SetTooltip gets a reference to the given string and assigns it to the Tooltip field.
func (o *WebLinkInfo) SetTooltip(v string) {
	o.Tooltip = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *WebLinkInfo) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebLinkInfo) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *WebLinkInfo) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *WebLinkInfo) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *WebLinkInfo) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebLinkInfo) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *WebLinkInfo) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *WebLinkInfo) SetUrl(v string) {
	o.Url = &v
}

func (o WebLinkInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebLinkInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Tooltip) {
		toSerialize["tooltip"] = o.Tooltip
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["image_url"] = o.ImageUrl
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableWebLinkInfo struct {
	value *WebLinkInfo
	isSet bool
}

func (v NullableWebLinkInfo) Get() *WebLinkInfo {
	return v.value
}

func (v *NullableWebLinkInfo) Set(val *WebLinkInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableWebLinkInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableWebLinkInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebLinkInfo(val *WebLinkInfo) *NullableWebLinkInfo {
	return &NullableWebLinkInfo{value: val, isSet: true}
}

func (v NullableWebLinkInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebLinkInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


