/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
	"fmt"
)

// AuthType the model 'AuthType'
type AuthType string

// List of AuthType
const (
	AUTHTYPE_OPENID AuthType = "OPENID"
	AUTHTYPE_OPENID_SSO AuthType = "OPENID_SSO"
	AUTHTYPE_HTTP AuthType = "HTTP"
	AUTHTYPE_HTTP_LDAP AuthType = "HTTP_LDAP"
	AUTHTYPE_CLIENT_SSL_CERT_LDAP AuthType = "CLIENT_SSL_CERT_LDAP"
	AUTHTYPE_LDAP AuthType = "LDAP"
	AUTHTYPE_LDAP_BIND AuthType = "LDAP_BIND"
	AUTHTYPE_CUSTOM_EXTENSION AuthType = "CUSTOM_EXTENSION"
	AUTHTYPE_DEVELOPMENT_BECOME_ANY_ACCOUNT AuthType = "DEVELOPMENT_BECOME_ANY_ACCOUNT"
	AUTHTYPE_OAUTH AuthType = "OAUTH"
)

// All allowed values of AuthType enum
var AllowedAuthTypeEnumValues = []AuthType{
	"OPENID",
	"OPENID_SSO",
	"HTTP",
	"HTTP_LDAP",
	"CLIENT_SSL_CERT_LDAP",
	"LDAP",
	"LDAP_BIND",
	"CUSTOM_EXTENSION",
	"DEVELOPMENT_BECOME_ANY_ACCOUNT",
	"OAUTH",
}

func (v *AuthType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AuthType(value)
	for _, existing := range AllowedAuthTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AuthType", value)
}

// NewAuthTypeFromValue returns a pointer to a valid AuthType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAuthTypeFromValue(v string) (*AuthType, error) {
	ev := AuthType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AuthType: valid values are %v", v, AllowedAuthTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AuthType) IsValid() bool {
	for _, existing := range AllowedAuthTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AuthType value
func (v AuthType) Ptr() *AuthType {
	return &v
}

type NullableAuthType struct {
	value *AuthType
	isSet bool
}

func (v NullableAuthType) Get() *AuthType {
	return v.value
}

func (v *NullableAuthType) Set(val *AuthType) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthType) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthType(val *AuthType) *NullableAuthType {
	return &NullableAuthType{value: val, isSet: true}
}

func (v NullableAuthType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

