/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the EntriesInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntriesInfo{}

// EntriesInfo struct for EntriesInfo
type EntriesInfo struct {
	Mem *int32 `json:"mem,omitempty"`
	Disk *int32 `json:"disk,omitempty"`
	Space *string `json:"space,omitempty"`
}

// NewEntriesInfo instantiates a new EntriesInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntriesInfo() *EntriesInfo {
	this := EntriesInfo{}
	return &this
}

// NewEntriesInfoWithDefaults instantiates a new EntriesInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntriesInfoWithDefaults() *EntriesInfo {
	this := EntriesInfo{}
	return &this
}

// GetMem returns the Mem field value if set, zero value otherwise.
func (o *EntriesInfo) GetMem() int32 {
	if o == nil || IsNil(o.Mem) {
		var ret int32
		return ret
	}
	return *o.Mem
}

// GetMemOk returns a tuple with the Mem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntriesInfo) GetMemOk() (*int32, bool) {
	if o == nil || IsNil(o.Mem) {
		return nil, false
	}
	return o.Mem, true
}

// HasMem returns a boolean if a field has been set.
func (o *EntriesInfo) HasMem() bool {
	if o != nil && !IsNil(o.Mem) {
		return true
	}

	return false
}

// SetMem gets a reference to the given int32 and assigns it to the Mem field.
func (o *EntriesInfo) SetMem(v int32) {
	o.Mem = &v
}

// GetDisk returns the Disk field value if set, zero value otherwise.
func (o *EntriesInfo) GetDisk() int32 {
	if o == nil || IsNil(o.Disk) {
		var ret int32
		return ret
	}
	return *o.Disk
}

// GetDiskOk returns a tuple with the Disk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntriesInfo) GetDiskOk() (*int32, bool) {
	if o == nil || IsNil(o.Disk) {
		return nil, false
	}
	return o.Disk, true
}

// HasDisk returns a boolean if a field has been set.
func (o *EntriesInfo) HasDisk() bool {
	if o != nil && !IsNil(o.Disk) {
		return true
	}

	return false
}

// SetDisk gets a reference to the given int32 and assigns it to the Disk field.
func (o *EntriesInfo) SetDisk(v int32) {
	o.Disk = &v
}

// GetSpace returns the Space field value if set, zero value otherwise.
func (o *EntriesInfo) GetSpace() string {
	if o == nil || IsNil(o.Space) {
		var ret string
		return ret
	}
	return *o.Space
}

// GetSpaceOk returns a tuple with the Space field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntriesInfo) GetSpaceOk() (*string, bool) {
	if o == nil || IsNil(o.Space) {
		return nil, false
	}
	return o.Space, true
}

// HasSpace returns a boolean if a field has been set.
func (o *EntriesInfo) HasSpace() bool {
	if o != nil && !IsNil(o.Space) {
		return true
	}

	return false
}

// SetSpace gets a reference to the given string and assigns it to the Space field.
func (o *EntriesInfo) SetSpace(v string) {
	o.Space = &v
}

func (o EntriesInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntriesInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mem) {
		toSerialize["mem"] = o.Mem
	}
	if !IsNil(o.Disk) {
		toSerialize["disk"] = o.Disk
	}
	if !IsNil(o.Space) {
		toSerialize["space"] = o.Space
	}
	return toSerialize, nil
}

type NullableEntriesInfo struct {
	value *EntriesInfo
	isSet bool
}

func (v NullableEntriesInfo) Get() *EntriesInfo {
	return v.value
}

func (v *NullableEntriesInfo) Set(val *EntriesInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableEntriesInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableEntriesInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntriesInfo(val *EntriesInfo) *NullableEntriesInfo {
	return &NullableEntriesInfo{value: val, isSet: true}
}

func (v NullableEntriesInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntriesInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


