/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the AttentionSetInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttentionSetInput{}

// AttentionSetInput struct for AttentionSetInput
type AttentionSetInput struct {
	// ID of the account that should be added to the attention set. For removals, this field should be empty or the same as the field in the request header.
	User *string `json:"user,omitempty"`
	// The reason of for adding or removing the user.
	Reason *string `json:"reason,omitempty"`
	// Notify handling that defines to whom email notifications should be sent after the change is created. + Allowed values are NONE, OWNER, OWNER_REVIEWERS and ALL. + If not set, the default is OWNER.
	Notify *NotifyHandling `json:"notify,omitempty"`
	// Additional information about whom to notify about the change creation as a map of recipient type to NotifyInfo entity.
	NotifyDetails map[string]NotifyInfo `json:"notify_details,omitempty"`
}

// NewAttentionSetInput instantiates a new AttentionSetInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttentionSetInput() *AttentionSetInput {
	this := AttentionSetInput{}
	return &this
}

// NewAttentionSetInputWithDefaults instantiates a new AttentionSetInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttentionSetInputWithDefaults() *AttentionSetInput {
	this := AttentionSetInput{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *AttentionSetInput) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttentionSetInput) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *AttentionSetInput) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *AttentionSetInput) SetUser(v string) {
	o.User = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *AttentionSetInput) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttentionSetInput) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *AttentionSetInput) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *AttentionSetInput) SetReason(v string) {
	o.Reason = &v
}

// GetNotify returns the Notify field value if set, zero value otherwise.
func (o *AttentionSetInput) GetNotify() NotifyHandling {
	if o == nil || IsNil(o.Notify) {
		var ret NotifyHandling
		return ret
	}
	return *o.Notify
}

// GetNotifyOk returns a tuple with the Notify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttentionSetInput) GetNotifyOk() (*NotifyHandling, bool) {
	if o == nil || IsNil(o.Notify) {
		return nil, false
	}
	return o.Notify, true
}

// HasNotify returns a boolean if a field has been set.
func (o *AttentionSetInput) HasNotify() bool {
	if o != nil && !IsNil(o.Notify) {
		return true
	}

	return false
}

// SetNotify gets a reference to the given NotifyHandling and assigns it to the Notify field.
func (o *AttentionSetInput) SetNotify(v NotifyHandling) {
	o.Notify = &v
}

// GetNotifyDetails returns the NotifyDetails field value if set, zero value otherwise.
func (o *AttentionSetInput) GetNotifyDetails() map[string]NotifyInfo {
	if o == nil || IsNil(o.NotifyDetails) {
		var ret map[string]NotifyInfo
		return ret
	}
	return o.NotifyDetails
}

// GetNotifyDetailsOk returns a tuple with the NotifyDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttentionSetInput) GetNotifyDetailsOk() (map[string]NotifyInfo, bool) {
	if o == nil || IsNil(o.NotifyDetails) {
		return map[string]NotifyInfo{}, false
	}
	return o.NotifyDetails, true
}

// HasNotifyDetails returns a boolean if a field has been set.
func (o *AttentionSetInput) HasNotifyDetails() bool {
	if o != nil && !IsNil(o.NotifyDetails) {
		return true
	}

	return false
}

// SetNotifyDetails gets a reference to the given map[string]NotifyInfo and assigns it to the NotifyDetails field.
func (o *AttentionSetInput) SetNotifyDetails(v map[string]NotifyInfo) {
	o.NotifyDetails = v
}

func (o AttentionSetInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttentionSetInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.Notify) {
		toSerialize["notify"] = o.Notify
	}
	if !IsNil(o.NotifyDetails) {
		toSerialize["notify_details"] = o.NotifyDetails
	}
	return toSerialize, nil
}

type NullableAttentionSetInput struct {
	value *AttentionSetInput
	isSet bool
}

func (v NullableAttentionSetInput) Get() *AttentionSetInput {
	return v.value
}

func (v *NullableAttentionSetInput) Set(val *AttentionSetInput) {
	v.value = val
	v.isSet = true
}

func (v NullableAttentionSetInput) IsSet() bool {
	return v.isSet
}

func (v *NullableAttentionSetInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttentionSetInput(val *AttentionSetInput) *NullableAttentionSetInput {
	return &NullableAttentionSetInput{value: val, isSet: true}
}

func (v NullableAttentionSetInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttentionSetInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


