/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the DeleteChangesInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteChangesInput{}

// DeleteChangesInput struct for DeleteChangesInput
type DeleteChangesInput struct {
	Changes []string `json:"changes,omitempty"`
}

// NewDeleteChangesInput instantiates a new DeleteChangesInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteChangesInput() *DeleteChangesInput {
	this := DeleteChangesInput{}
	return &this
}

// NewDeleteChangesInputWithDefaults instantiates a new DeleteChangesInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteChangesInputWithDefaults() *DeleteChangesInput {
	this := DeleteChangesInput{}
	return &this
}

// GetChanges returns the Changes field value if set, zero value otherwise.
func (o *DeleteChangesInput) GetChanges() []string {
	if o == nil || IsNil(o.Changes) {
		var ret []string
		return ret
	}
	return o.Changes
}

// GetChangesOk returns a tuple with the Changes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteChangesInput) GetChangesOk() ([]string, bool) {
	if o == nil || IsNil(o.Changes) {
		return nil, false
	}
	return o.Changes, true
}

// HasChanges returns a boolean if a field has been set.
func (o *DeleteChangesInput) HasChanges() bool {
	if o != nil && !IsNil(o.Changes) {
		return true
	}

	return false
}

// SetChanges gets a reference to the given []string and assigns it to the Changes field.
func (o *DeleteChangesInput) SetChanges(v []string) {
	o.Changes = v
}

func (o DeleteChangesInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteChangesInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Changes) {
		toSerialize["changes"] = o.Changes
	}
	return toSerialize, nil
}

type NullableDeleteChangesInput struct {
	value *DeleteChangesInput
	isSet bool
}

func (v NullableDeleteChangesInput) Get() *DeleteChangesInput {
	return v.value
}

func (v *NullableDeleteChangesInput) Set(val *DeleteChangesInput) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteChangesInput) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteChangesInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteChangesInput(val *DeleteChangesInput) *NullableDeleteChangesInput {
	return &NullableDeleteChangesInput{value: val, isSet: true}
}

func (v NullableDeleteChangesInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteChangesInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


