/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the FixInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FixInput{}

// FixInput struct for FixInput
type FixInput struct {
	DeletePatchSetIfCommitMissing *bool `json:"delete_patch_set_if_commit_missing,omitempty"`
	ExpectMergedAs *string `json:"expect_merged_as,omitempty"`
}

// NewFixInput instantiates a new FixInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFixInput() *FixInput {
	this := FixInput{}
	return &this
}

// NewFixInputWithDefaults instantiates a new FixInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFixInputWithDefaults() *FixInput {
	this := FixInput{}
	return &this
}

// GetDeletePatchSetIfCommitMissing returns the DeletePatchSetIfCommitMissing field value if set, zero value otherwise.
func (o *FixInput) GetDeletePatchSetIfCommitMissing() bool {
	if o == nil || IsNil(o.DeletePatchSetIfCommitMissing) {
		var ret bool
		return ret
	}
	return *o.DeletePatchSetIfCommitMissing
}

// GetDeletePatchSetIfCommitMissingOk returns a tuple with the DeletePatchSetIfCommitMissing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FixInput) GetDeletePatchSetIfCommitMissingOk() (*bool, bool) {
	if o == nil || IsNil(o.DeletePatchSetIfCommitMissing) {
		return nil, false
	}
	return o.DeletePatchSetIfCommitMissing, true
}

// HasDeletePatchSetIfCommitMissing returns a boolean if a field has been set.
func (o *FixInput) HasDeletePatchSetIfCommitMissing() bool {
	if o != nil && !IsNil(o.DeletePatchSetIfCommitMissing) {
		return true
	}

	return false
}

// SetDeletePatchSetIfCommitMissing gets a reference to the given bool and assigns it to the DeletePatchSetIfCommitMissing field.
func (o *FixInput) SetDeletePatchSetIfCommitMissing(v bool) {
	o.DeletePatchSetIfCommitMissing = &v
}

// GetExpectMergedAs returns the ExpectMergedAs field value if set, zero value otherwise.
func (o *FixInput) GetExpectMergedAs() string {
	if o == nil || IsNil(o.ExpectMergedAs) {
		var ret string
		return ret
	}
	return *o.ExpectMergedAs
}

// GetExpectMergedAsOk returns a tuple with the ExpectMergedAs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FixInput) GetExpectMergedAsOk() (*string, bool) {
	if o == nil || IsNil(o.ExpectMergedAs) {
		return nil, false
	}
	return o.ExpectMergedAs, true
}

// HasExpectMergedAs returns a boolean if a field has been set.
func (o *FixInput) HasExpectMergedAs() bool {
	if o != nil && !IsNil(o.ExpectMergedAs) {
		return true
	}

	return false
}

// SetExpectMergedAs gets a reference to the given string and assigns it to the ExpectMergedAs field.
func (o *FixInput) SetExpectMergedAs(v string) {
	o.ExpectMergedAs = &v
}

func (o FixInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FixInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeletePatchSetIfCommitMissing) {
		toSerialize["delete_patch_set_if_commit_missing"] = o.DeletePatchSetIfCommitMissing
	}
	if !IsNil(o.ExpectMergedAs) {
		toSerialize["expect_merged_as"] = o.ExpectMergedAs
	}
	return toSerialize, nil
}

type NullableFixInput struct {
	value *FixInput
	isSet bool
}

func (v NullableFixInput) Get() *FixInput {
	return v.value
}

func (v *NullableFixInput) Set(val *FixInput) {
	v.value = val
	v.isSet = true
}

func (v NullableFixInput) IsSet() bool {
	return v.isSet
}

func (v *NullableFixInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFixInput(val *FixInput) *NullableFixInput {
	return &NullableFixInput{value: val, isSet: true}
}

func (v NullableFixInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFixInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


