/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
	"fmt"
)

// DateFormat the model 'DateFormat'
type DateFormat string

// List of DateFormat
const (
	DATEFORMAT_STD DateFormat = "STD"
	DATEFORMAT_US DateFormat = "US"
	DATEFORMAT_ISO DateFormat = "ISO"
	DATEFORMAT_EURO DateFormat = "EURO"
	DATEFORMAT_UK DateFormat = "UK"
)

// All allowed values of DateFormat enum
var AllowedDateFormatEnumValues = []DateFormat{
	"STD",
	"US",
	"ISO",
	"EURO",
	"UK",
}

func (v *DateFormat) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DateFormat(value)
	for _, existing := range AllowedDateFormatEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DateFormat", value)
}

// NewDateFormatFromValue returns a pointer to a valid DateFormat
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDateFormatFromValue(v string) (*DateFormat, error) {
	ev := DateFormat(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DateFormat: valid values are %v", v, AllowedDateFormatEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DateFormat) IsValid() bool {
	for _, existing := range AllowedDateFormatEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DateFormat value
func (v DateFormat) Ptr() *DateFormat {
	return &v
}

type NullableDateFormat struct {
	value *DateFormat
	isSet bool
}

func (v NullableDateFormat) Get() *DateFormat {
	return v.value
}

func (v *NullableDateFormat) Set(val *DateFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableDateFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableDateFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDateFormat(val *DateFormat) *NullableDateFormat {
	return &NullableDateFormat{value: val, isSet: true}
}

func (v NullableDateFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDateFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

