/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the IsFlowsEnabledInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IsFlowsEnabledInfo{}

// IsFlowsEnabledInfo struct for IsFlowsEnabledInfo
type IsFlowsEnabledInfo struct {
	// A boolean indicating whether the feature is enabled.
	Enabled *bool `json:"enabled,omitempty"`
}

// NewIsFlowsEnabledInfo instantiates a new IsFlowsEnabledInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIsFlowsEnabledInfo() *IsFlowsEnabledInfo {
	this := IsFlowsEnabledInfo{}
	return &this
}

// NewIsFlowsEnabledInfoWithDefaults instantiates a new IsFlowsEnabledInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIsFlowsEnabledInfoWithDefaults() *IsFlowsEnabledInfo {
	this := IsFlowsEnabledInfo{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *IsFlowsEnabledInfo) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IsFlowsEnabledInfo) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *IsFlowsEnabledInfo) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *IsFlowsEnabledInfo) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o IsFlowsEnabledInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IsFlowsEnabledInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableIsFlowsEnabledInfo struct {
	value *IsFlowsEnabledInfo
	isSet bool
}

func (v NullableIsFlowsEnabledInfo) Get() *IsFlowsEnabledInfo {
	return v.value
}

func (v *NullableIsFlowsEnabledInfo) Set(val *IsFlowsEnabledInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableIsFlowsEnabledInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableIsFlowsEnabledInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIsFlowsEnabledInfo(val *IsFlowsEnabledInfo) *NullableIsFlowsEnabledInfo {
	return &NullableIsFlowsEnabledInfo{value: val, isSet: true}
}

func (v NullableIsFlowsEnabledInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIsFlowsEnabledInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


