/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ChangeInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeInfo{}

// ChangeInfo struct for ChangeInfo
type ChangeInfo struct {
	// The ID of the change. The format is \"'<project>\\~<_number>'\". 'project' and '_number' are URL encoded. The callers must not rely on the format.
	Id *string `json:"id,omitempty"`
	// The ID of the change in the format \"'<project>\\~<branch>~<Change-Id>'\", where 'project' and 'branch' are URL encoded. For 'branch' the refs/heads/ prefix is omitted.
	TripletId *string `json:"triplet_id,omitempty"`
	// The name of the project.
	Project *string `json:"project,omitempty"`
	// The name of the target branch. + The refs/heads/ prefix is omitted.
	Branch *string `json:"branch,omitempty"`
	// The full name of the target branch. + Always starts with refs/.
	FullBranch *string `json:"full_branch,omitempty"`
	// The topic to which this change belongs.
	Topic *string `json:"topic,omitempty"`
	// The map that maps account IDs to AttentionSetInfo of that account. Those are all accounts that are currently in the attention set.
	AttentionSet map[string]AttentionSetInfo `json:"attention_set,omitempty"`
	// The map that maps account IDs to AttentionSetInfo of that account. Those are all accounts that were in the attention set but were removed. The AttentionSetInfo is the latest and most recent removal of the account from the attention set.
	RemovedFromAttentionSet map[string]AttentionSetInfo `json:"removed_from_attention_set,omitempty"`
	// A map that maps custom keys to custom values that are tied to a specific change, both in the form of strings. Only set if custom keyed values are requested.
	CustomKeyedValues map[string]string `json:"custom_keyed_values,omitempty"`
	// List of hashtags that are set on the change.
	Hashtags []string `json:"hashtags,omitempty"`
	// The Change-Id of the change.
	ChangeId *string `json:"change_id,omitempty"`
	// The subject of the change (header line of the commit message).
	Subject *string `json:"subject,omitempty"`
	// The status of the change (NEW, MERGED, ABANDONED).
	Status *ChangeStatus `json:"status,omitempty"`
	// The timestamp of when the change was created.
	Created *string `json:"created,omitempty"`
	// The timestamp of when the change was last updated.
	Updated *string `json:"updated,omitempty"`
	// The timestamp of when the change was submitted.
	Submitted *string `json:"submitted,omitempty"`
	// The user who submitted the change, as an AccountInfo entity.
	Submitter *AccountInfo `json:"submitter,omitempty"`
	// Whether the calling user has starred this change. Only set if requested.
	Starred *bool `json:"starred,omitempty"`
	Stars []string `json:"stars,omitempty"`
	// Whether the change was reviewed by the calling user. Only set if reviewed is requested.
	Reviewed *bool `json:"reviewed,omitempty"`
	// The submit type of the change. + Not set for merged changes.
	SubmitType *SubmitType `json:"submit_type,omitempty"`
	// Whether the change is mergeable. + Only set for open changes if change.mergeabilityComputationBehavior is API_REF_UPDATED_AND_CHANGE_REINDEX.
	Mergeable *bool `json:"mergeable,omitempty"`
	// Whether the change has been approved by the project submit rules. + Only set if requested.
	Submittable *bool `json:"submittable,omitempty"`
	// Number of inserted lines.
	Insertions *int32 `json:"insertions,omitempty"`
	// Number of deleted lines.
	Deletions *int32 `json:"deletions,omitempty"`
	// Total number of inline comments across all patch sets.
	TotalCommentCount *int32 `json:"total_comment_count,omitempty"`
	// Number of unresolved inline comment threads across all patch sets.
	UnresolvedCommentCount *int32 `json:"unresolved_comment_count,omitempty"`
	// When present, change is marked as private.
	IsPrivate *bool `json:"is_private,omitempty"`
	// When present, change is marked as Work In Progress.
	WorkInProgress *bool `json:"work_in_progress,omitempty"`
	// When present, change has been marked Ready at some point in time.
	HasReviewStarted *bool `json:"has_review_started,omitempty"`
	// The change number of the change that this change reverts.
	RevertOf *int32 `json:"revert_of,omitempty"`
	// ID of the submission of this change. Only set if the status is MERGED. This ID is equal to the change number of the change that triggered the submission. If the change that triggered the submission also has a topic, it will be \"<id>-<topic>\" of the change that triggered the submission.
	SubmissionId *string `json:"submission_id,omitempty"`
	// The change number of the change that this change was cherry-picked from. Only set if the cherry-pick has been done through the Gerrit REST API (and not if a cherry-picked commit was pushed).
	CherryPickOfChange *int32 `json:"cherry_pick_of_change,omitempty"`
	// The patchset number of the change that this change was cherry-picked from. Only set if the cherry-pick has been done through the Gerrit REST API (and not if a cherry-picked commit was pushed).
	CherryPickOfPatchSet *int32 `json:"cherry_pick_of_patch_set,omitempty"`
	// The SHA-1 of the NoteDb meta ref.
	MetaRevId *string `json:"meta_rev_id,omitempty"`
	// Whether the change contains conflicts. + If true, some of the file contents of the change contain git conflict markers to indicate the conflicts. + Only set if this change info is returned in response to a request that creates a new change or patch set and conflicts are allowed.
	ContainsGitConflicts *bool `json:"contains_git_conflicts,omitempty"`
	// The change number. (The underscore is just a relict of a prior attempt to deprecate the change number.)
	Number *int32 `json:"_number,omitempty"`
	// The virtual id number is globally unique. For local changes, it is equal to the _number attribute. For imported changes, the original _number is processed through a function designed to prevent conflicts with local change numbers.
	VirtualIdNumber *int32 `json:"virtual_id_number,omitempty"`
	// The owner of the change as an AccountInfo entity.
	Owner *AccountInfo `json:"owner,omitempty"`
	// Actions the caller might be able to perform on this revision. The information is a map of view name to ActionInfo entities.
	Actions map[string]ActionInfo `json:"actions,omitempty"`
	// The labels of the change as a map that maps the label names to LabelInfo entries. + Only set if labels or detailed labels are requested.
	Labels map[string]LabelInfo `json:"labels,omitempty"`
	// A map of the permitted labels that maps a label name to the list of values that the current user can vote on. + Only set if detailed labels are requested.
	PermittedLabels map[string][]string `json:"permitted_labels,omitempty"`
	// A map of the removable labels that maps a label name to the map of values and reviewers ( AccountInfo entities) that are allowed to be removed from the change. + Only set if labels or detailed labels are requested.
	RemovableLabels map[string]map[string][]AccountInfo `json:"removable_labels,omitempty"`
	// The reviewers that can be removed by the calling user as a list of AccountInfo entities. + Only set if labels or detailed labels are requested.
	RemovableReviewers []AccountInfo `json:"removable_reviewers,omitempty"`
	// The reviewers as a map that maps a reviewer state to a list of AccountInfo entities. Possible reviewer states are REVIEWER, CC. + REVIEWER: Users with at least one non-zero vote on the change. + CC: Users that were added to the change, but have not voted.
	Reviewers map[string][]AccountInfo `json:"reviewers,omitempty"`
	// Updates to reviewers that have been made while the change was in the WIP state. Only present on WIP changes and only if there are pending reviewer updates to report. These are reviewers who have not yet been notified about being added to or removed from the change.
	PendingReviewers map[string][]AccountInfo `json:"pending_reviewers,omitempty"`
	// Updates to reviewers set for the change as ReviewerUpdateInfo entities. Only set if reviewer updates are requested.
	ReviewerUpdates []ReviewerUpdateInfo `json:"reviewer_updates,omitempty"`
	// Messages associated with the change as a list of ChangeMessageInfo entities. + Only set if messages are requested.
	Messages []ChangeMessageInfo `json:"messages,omitempty"`
	// The number of the current patch set of this change. +
	CurrentRevisionNumber *int32 `json:"current_revision_number,omitempty"`
	// The commit ID of the current patch set of this change. + Only set if the current revision is requested or if all revisions are requested.
	CurrentRevision *string `json:"current_revision,omitempty"`
	// All patch sets of this change as a map that maps the commit ID of the patch set to a RevisionInfo entity. + Only set if the current revision is requested (in which case it will only contain a key for the current revision) or if all revisions are requested.
	Revisions map[string]RevisionInfo `json:"revisions,omitempty"`
	// Whether the query would deliver more results if not limited. + Only set on the last change that is returned.
	MoreChanges *bool `json:"_more_changes,omitempty"`
	// A list of ProblemInfo entities describing potential problems with this change. Only set if CHECK is set.
	Problems []ProblemInfo `json:"problems,omitempty"`
	Plugins []PluginDefinedInfo `json:"plugins,omitempty"`
	// A list of TrackingIdInfo entities describing references to external tracking systems. Only set if tracking ids are requested.
	TrackingIds []TrackingIdInfo `json:"tracking_ids,omitempty"`
	// List of the requirements to be met before this change can be submitted. This field is deprecated in favour of submit_requirements. Only set if SUBMIT_REQUIREMENTS is requested.
	Requirements []LegacySubmitRequirementInfo `json:"requirements,omitempty"`
	// List of the SubmitRecordInfo containing the submit records for the change at the latest patchset. This field is deprecated in favour of submit_requirements. Only set if SUBMIT_REQUIREMENTS is requested.
	SubmitRecords []SubmitRecordInfo `json:"submit_records,omitempty"`
	// List of the SubmitRequirementResultInfo containing the evaluated submit requirements for the change. Only set if SUBMIT_REQUIREMENTS is requested.
	SubmitRequirements []SubmitRequirementResultInfo `json:"submit_requirements,omitempty"`
}

// NewChangeInfo instantiates a new ChangeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeInfo() *ChangeInfo {
	this := ChangeInfo{}
	return &this
}

// NewChangeInfoWithDefaults instantiates a new ChangeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeInfoWithDefaults() *ChangeInfo {
	this := ChangeInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ChangeInfo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ChangeInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ChangeInfo) SetId(v string) {
	o.Id = &v
}

// GetTripletId returns the TripletId field value if set, zero value otherwise.
func (o *ChangeInfo) GetTripletId() string {
	if o == nil || IsNil(o.TripletId) {
		var ret string
		return ret
	}
	return *o.TripletId
}

// GetTripletIdOk returns a tuple with the TripletId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetTripletIdOk() (*string, bool) {
	if o == nil || IsNil(o.TripletId) {
		return nil, false
	}
	return o.TripletId, true
}

// HasTripletId returns a boolean if a field has been set.
func (o *ChangeInfo) HasTripletId() bool {
	if o != nil && !IsNil(o.TripletId) {
		return true
	}

	return false
}

// SetTripletId gets a reference to the given string and assigns it to the TripletId field.
func (o *ChangeInfo) SetTripletId(v string) {
	o.TripletId = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *ChangeInfo) GetProject() string {
	if o == nil || IsNil(o.Project) {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetProjectOk() (*string, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *ChangeInfo) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *ChangeInfo) SetProject(v string) {
	o.Project = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *ChangeInfo) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *ChangeInfo) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *ChangeInfo) SetBranch(v string) {
	o.Branch = &v
}

// GetFullBranch returns the FullBranch field value if set, zero value otherwise.
func (o *ChangeInfo) GetFullBranch() string {
	if o == nil || IsNil(o.FullBranch) {
		var ret string
		return ret
	}
	return *o.FullBranch
}

// GetFullBranchOk returns a tuple with the FullBranch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetFullBranchOk() (*string, bool) {
	if o == nil || IsNil(o.FullBranch) {
		return nil, false
	}
	return o.FullBranch, true
}

// HasFullBranch returns a boolean if a field has been set.
func (o *ChangeInfo) HasFullBranch() bool {
	if o != nil && !IsNil(o.FullBranch) {
		return true
	}

	return false
}

// SetFullBranch gets a reference to the given string and assigns it to the FullBranch field.
func (o *ChangeInfo) SetFullBranch(v string) {
	o.FullBranch = &v
}

// GetTopic returns the Topic field value if set, zero value otherwise.
func (o *ChangeInfo) GetTopic() string {
	if o == nil || IsNil(o.Topic) {
		var ret string
		return ret
	}
	return *o.Topic
}

// GetTopicOk returns a tuple with the Topic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetTopicOk() (*string, bool) {
	if o == nil || IsNil(o.Topic) {
		return nil, false
	}
	return o.Topic, true
}

// HasTopic returns a boolean if a field has been set.
func (o *ChangeInfo) HasTopic() bool {
	if o != nil && !IsNil(o.Topic) {
		return true
	}

	return false
}

// SetTopic gets a reference to the given string and assigns it to the Topic field.
func (o *ChangeInfo) SetTopic(v string) {
	o.Topic = &v
}

// GetAttentionSet returns the AttentionSet field value if set, zero value otherwise.
func (o *ChangeInfo) GetAttentionSet() map[string]AttentionSetInfo {
	if o == nil || IsNil(o.AttentionSet) {
		var ret map[string]AttentionSetInfo
		return ret
	}
	return o.AttentionSet
}

// GetAttentionSetOk returns a tuple with the AttentionSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetAttentionSetOk() (map[string]AttentionSetInfo, bool) {
	if o == nil || IsNil(o.AttentionSet) {
		return map[string]AttentionSetInfo{}, false
	}
	return o.AttentionSet, true
}

// HasAttentionSet returns a boolean if a field has been set.
func (o *ChangeInfo) HasAttentionSet() bool {
	if o != nil && !IsNil(o.AttentionSet) {
		return true
	}

	return false
}

// SetAttentionSet gets a reference to the given map[string]AttentionSetInfo and assigns it to the AttentionSet field.
func (o *ChangeInfo) SetAttentionSet(v map[string]AttentionSetInfo) {
	o.AttentionSet = v
}

// GetRemovedFromAttentionSet returns the RemovedFromAttentionSet field value if set, zero value otherwise.
func (o *ChangeInfo) GetRemovedFromAttentionSet() map[string]AttentionSetInfo {
	if o == nil || IsNil(o.RemovedFromAttentionSet) {
		var ret map[string]AttentionSetInfo
		return ret
	}
	return o.RemovedFromAttentionSet
}

// GetRemovedFromAttentionSetOk returns a tuple with the RemovedFromAttentionSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetRemovedFromAttentionSetOk() (map[string]AttentionSetInfo, bool) {
	if o == nil || IsNil(o.RemovedFromAttentionSet) {
		return map[string]AttentionSetInfo{}, false
	}
	return o.RemovedFromAttentionSet, true
}

// HasRemovedFromAttentionSet returns a boolean if a field has been set.
func (o *ChangeInfo) HasRemovedFromAttentionSet() bool {
	if o != nil && !IsNil(o.RemovedFromAttentionSet) {
		return true
	}

	return false
}

// SetRemovedFromAttentionSet gets a reference to the given map[string]AttentionSetInfo and assigns it to the RemovedFromAttentionSet field.
func (o *ChangeInfo) SetRemovedFromAttentionSet(v map[string]AttentionSetInfo) {
	o.RemovedFromAttentionSet = v
}

// GetCustomKeyedValues returns the CustomKeyedValues field value if set, zero value otherwise.
func (o *ChangeInfo) GetCustomKeyedValues() map[string]string {
	if o == nil || IsNil(o.CustomKeyedValues) {
		var ret map[string]string
		return ret
	}
	return o.CustomKeyedValues
}

// GetCustomKeyedValuesOk returns a tuple with the CustomKeyedValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetCustomKeyedValuesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.CustomKeyedValues) {
		return map[string]string{}, false
	}
	return o.CustomKeyedValues, true
}

// HasCustomKeyedValues returns a boolean if a field has been set.
func (o *ChangeInfo) HasCustomKeyedValues() bool {
	if o != nil && !IsNil(o.CustomKeyedValues) {
		return true
	}

	return false
}

// SetCustomKeyedValues gets a reference to the given map[string]string and assigns it to the CustomKeyedValues field.
func (o *ChangeInfo) SetCustomKeyedValues(v map[string]string) {
	o.CustomKeyedValues = v
}

// GetHashtags returns the Hashtags field value if set, zero value otherwise.
func (o *ChangeInfo) GetHashtags() []string {
	if o == nil || IsNil(o.Hashtags) {
		var ret []string
		return ret
	}
	return o.Hashtags
}

// GetHashtagsOk returns a tuple with the Hashtags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetHashtagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Hashtags) {
		return nil, false
	}
	return o.Hashtags, true
}

// HasHashtags returns a boolean if a field has been set.
func (o *ChangeInfo) HasHashtags() bool {
	if o != nil && !IsNil(o.Hashtags) {
		return true
	}

	return false
}

// SetHashtags gets a reference to the given []string and assigns it to the Hashtags field.
func (o *ChangeInfo) SetHashtags(v []string) {
	o.Hashtags = v
}

// GetChangeId returns the ChangeId field value if set, zero value otherwise.
func (o *ChangeInfo) GetChangeId() string {
	if o == nil || IsNil(o.ChangeId) {
		var ret string
		return ret
	}
	return *o.ChangeId
}

// GetChangeIdOk returns a tuple with the ChangeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetChangeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChangeId) {
		return nil, false
	}
	return o.ChangeId, true
}

// HasChangeId returns a boolean if a field has been set.
func (o *ChangeInfo) HasChangeId() bool {
	if o != nil && !IsNil(o.ChangeId) {
		return true
	}

	return false
}

// SetChangeId gets a reference to the given string and assigns it to the ChangeId field.
func (o *ChangeInfo) SetChangeId(v string) {
	o.ChangeId = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *ChangeInfo) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *ChangeInfo) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *ChangeInfo) SetSubject(v string) {
	o.Subject = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ChangeInfo) GetStatus() ChangeStatus {
	if o == nil || IsNil(o.Status) {
		var ret ChangeStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetStatusOk() (*ChangeStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ChangeInfo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ChangeStatus and assigns it to the Status field.
func (o *ChangeInfo) SetStatus(v ChangeStatus) {
	o.Status = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ChangeInfo) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ChangeInfo) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *ChangeInfo) SetCreated(v string) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ChangeInfo) GetUpdated() string {
	if o == nil || IsNil(o.Updated) {
		var ret string
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ChangeInfo) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given string and assigns it to the Updated field.
func (o *ChangeInfo) SetUpdated(v string) {
	o.Updated = &v
}

// GetSubmitted returns the Submitted field value if set, zero value otherwise.
func (o *ChangeInfo) GetSubmitted() string {
	if o == nil || IsNil(o.Submitted) {
		var ret string
		return ret
	}
	return *o.Submitted
}

// GetSubmittedOk returns a tuple with the Submitted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetSubmittedOk() (*string, bool) {
	if o == nil || IsNil(o.Submitted) {
		return nil, false
	}
	return o.Submitted, true
}

// HasSubmitted returns a boolean if a field has been set.
func (o *ChangeInfo) HasSubmitted() bool {
	if o != nil && !IsNil(o.Submitted) {
		return true
	}

	return false
}

// SetSubmitted gets a reference to the given string and assigns it to the Submitted field.
func (o *ChangeInfo) SetSubmitted(v string) {
	o.Submitted = &v
}

// GetSubmitter returns the Submitter field value if set, zero value otherwise.
func (o *ChangeInfo) GetSubmitter() AccountInfo {
	if o == nil || IsNil(o.Submitter) {
		var ret AccountInfo
		return ret
	}
	return *o.Submitter
}

// GetSubmitterOk returns a tuple with the Submitter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetSubmitterOk() (*AccountInfo, bool) {
	if o == nil || IsNil(o.Submitter) {
		return nil, false
	}
	return o.Submitter, true
}

// HasSubmitter returns a boolean if a field has been set.
func (o *ChangeInfo) HasSubmitter() bool {
	if o != nil && !IsNil(o.Submitter) {
		return true
	}

	return false
}

// SetSubmitter gets a reference to the given AccountInfo and assigns it to the Submitter field.
func (o *ChangeInfo) SetSubmitter(v AccountInfo) {
	o.Submitter = &v
}

// GetStarred returns the Starred field value if set, zero value otherwise.
func (o *ChangeInfo) GetStarred() bool {
	if o == nil || IsNil(o.Starred) {
		var ret bool
		return ret
	}
	return *o.Starred
}

// GetStarredOk returns a tuple with the Starred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetStarredOk() (*bool, bool) {
	if o == nil || IsNil(o.Starred) {
		return nil, false
	}
	return o.Starred, true
}

// HasStarred returns a boolean if a field has been set.
func (o *ChangeInfo) HasStarred() bool {
	if o != nil && !IsNil(o.Starred) {
		return true
	}

	return false
}

// SetStarred gets a reference to the given bool and assigns it to the Starred field.
func (o *ChangeInfo) SetStarred(v bool) {
	o.Starred = &v
}

// GetStars returns the Stars field value if set, zero value otherwise.
func (o *ChangeInfo) GetStars() []string {
	if o == nil || IsNil(o.Stars) {
		var ret []string
		return ret
	}
	return o.Stars
}

// GetStarsOk returns a tuple with the Stars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetStarsOk() ([]string, bool) {
	if o == nil || IsNil(o.Stars) {
		return nil, false
	}
	return o.Stars, true
}

// HasStars returns a boolean if a field has been set.
func (o *ChangeInfo) HasStars() bool {
	if o != nil && !IsNil(o.Stars) {
		return true
	}

	return false
}

// SetStars gets a reference to the given []string and assigns it to the Stars field.
func (o *ChangeInfo) SetStars(v []string) {
	o.Stars = v
}

// GetReviewed returns the Reviewed field value if set, zero value otherwise.
func (o *ChangeInfo) GetReviewed() bool {
	if o == nil || IsNil(o.Reviewed) {
		var ret bool
		return ret
	}
	return *o.Reviewed
}

// GetReviewedOk returns a tuple with the Reviewed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetReviewedOk() (*bool, bool) {
	if o == nil || IsNil(o.Reviewed) {
		return nil, false
	}
	return o.Reviewed, true
}

// HasReviewed returns a boolean if a field has been set.
func (o *ChangeInfo) HasReviewed() bool {
	if o != nil && !IsNil(o.Reviewed) {
		return true
	}

	return false
}

// SetReviewed gets a reference to the given bool and assigns it to the Reviewed field.
func (o *ChangeInfo) SetReviewed(v bool) {
	o.Reviewed = &v
}

// GetSubmitType returns the SubmitType field value if set, zero value otherwise.
func (o *ChangeInfo) GetSubmitType() SubmitType {
	if o == nil || IsNil(o.SubmitType) {
		var ret SubmitType
		return ret
	}
	return *o.SubmitType
}

// GetSubmitTypeOk returns a tuple with the SubmitType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetSubmitTypeOk() (*SubmitType, bool) {
	if o == nil || IsNil(o.SubmitType) {
		return nil, false
	}
	return o.SubmitType, true
}

// HasSubmitType returns a boolean if a field has been set.
func (o *ChangeInfo) HasSubmitType() bool {
	if o != nil && !IsNil(o.SubmitType) {
		return true
	}

	return false
}

// SetSubmitType gets a reference to the given SubmitType and assigns it to the SubmitType field.
func (o *ChangeInfo) SetSubmitType(v SubmitType) {
	o.SubmitType = &v
}

// GetMergeable returns the Mergeable field value if set, zero value otherwise.
func (o *ChangeInfo) GetMergeable() bool {
	if o == nil || IsNil(o.Mergeable) {
		var ret bool
		return ret
	}
	return *o.Mergeable
}

// GetMergeableOk returns a tuple with the Mergeable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetMergeableOk() (*bool, bool) {
	if o == nil || IsNil(o.Mergeable) {
		return nil, false
	}
	return o.Mergeable, true
}

// HasMergeable returns a boolean if a field has been set.
func (o *ChangeInfo) HasMergeable() bool {
	if o != nil && !IsNil(o.Mergeable) {
		return true
	}

	return false
}

// SetMergeable gets a reference to the given bool and assigns it to the Mergeable field.
func (o *ChangeInfo) SetMergeable(v bool) {
	o.Mergeable = &v
}

// GetSubmittable returns the Submittable field value if set, zero value otherwise.
func (o *ChangeInfo) GetSubmittable() bool {
	if o == nil || IsNil(o.Submittable) {
		var ret bool
		return ret
	}
	return *o.Submittable
}

// GetSubmittableOk returns a tuple with the Submittable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetSubmittableOk() (*bool, bool) {
	if o == nil || IsNil(o.Submittable) {
		return nil, false
	}
	return o.Submittable, true
}

// HasSubmittable returns a boolean if a field has been set.
func (o *ChangeInfo) HasSubmittable() bool {
	if o != nil && !IsNil(o.Submittable) {
		return true
	}

	return false
}

// SetSubmittable gets a reference to the given bool and assigns it to the Submittable field.
func (o *ChangeInfo) SetSubmittable(v bool) {
	o.Submittable = &v
}

// GetInsertions returns the Insertions field value if set, zero value otherwise.
func (o *ChangeInfo) GetInsertions() int32 {
	if o == nil || IsNil(o.Insertions) {
		var ret int32
		return ret
	}
	return *o.Insertions
}

// GetInsertionsOk returns a tuple with the Insertions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetInsertionsOk() (*int32, bool) {
	if o == nil || IsNil(o.Insertions) {
		return nil, false
	}
	return o.Insertions, true
}

// HasInsertions returns a boolean if a field has been set.
func (o *ChangeInfo) HasInsertions() bool {
	if o != nil && !IsNil(o.Insertions) {
		return true
	}

	return false
}

// SetInsertions gets a reference to the given int32 and assigns it to the Insertions field.
func (o *ChangeInfo) SetInsertions(v int32) {
	o.Insertions = &v
}

// GetDeletions returns the Deletions field value if set, zero value otherwise.
func (o *ChangeInfo) GetDeletions() int32 {
	if o == nil || IsNil(o.Deletions) {
		var ret int32
		return ret
	}
	return *o.Deletions
}

// GetDeletionsOk returns a tuple with the Deletions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetDeletionsOk() (*int32, bool) {
	if o == nil || IsNil(o.Deletions) {
		return nil, false
	}
	return o.Deletions, true
}

// HasDeletions returns a boolean if a field has been set.
func (o *ChangeInfo) HasDeletions() bool {
	if o != nil && !IsNil(o.Deletions) {
		return true
	}

	return false
}

// SetDeletions gets a reference to the given int32 and assigns it to the Deletions field.
func (o *ChangeInfo) SetDeletions(v int32) {
	o.Deletions = &v
}

// GetTotalCommentCount returns the TotalCommentCount field value if set, zero value otherwise.
func (o *ChangeInfo) GetTotalCommentCount() int32 {
	if o == nil || IsNil(o.TotalCommentCount) {
		var ret int32
		return ret
	}
	return *o.TotalCommentCount
}

// GetTotalCommentCountOk returns a tuple with the TotalCommentCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetTotalCommentCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCommentCount) {
		return nil, false
	}
	return o.TotalCommentCount, true
}

// HasTotalCommentCount returns a boolean if a field has been set.
func (o *ChangeInfo) HasTotalCommentCount() bool {
	if o != nil && !IsNil(o.TotalCommentCount) {
		return true
	}

	return false
}

// SetTotalCommentCount gets a reference to the given int32 and assigns it to the TotalCommentCount field.
func (o *ChangeInfo) SetTotalCommentCount(v int32) {
	o.TotalCommentCount = &v
}

// GetUnresolvedCommentCount returns the UnresolvedCommentCount field value if set, zero value otherwise.
func (o *ChangeInfo) GetUnresolvedCommentCount() int32 {
	if o == nil || IsNil(o.UnresolvedCommentCount) {
		var ret int32
		return ret
	}
	return *o.UnresolvedCommentCount
}

// GetUnresolvedCommentCountOk returns a tuple with the UnresolvedCommentCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetUnresolvedCommentCountOk() (*int32, bool) {
	if o == nil || IsNil(o.UnresolvedCommentCount) {
		return nil, false
	}
	return o.UnresolvedCommentCount, true
}

// HasUnresolvedCommentCount returns a boolean if a field has been set.
func (o *ChangeInfo) HasUnresolvedCommentCount() bool {
	if o != nil && !IsNil(o.UnresolvedCommentCount) {
		return true
	}

	return false
}

// SetUnresolvedCommentCount gets a reference to the given int32 and assigns it to the UnresolvedCommentCount field.
func (o *ChangeInfo) SetUnresolvedCommentCount(v int32) {
	o.UnresolvedCommentCount = &v
}

// GetIsPrivate returns the IsPrivate field value if set, zero value otherwise.
func (o *ChangeInfo) GetIsPrivate() bool {
	if o == nil || IsNil(o.IsPrivate) {
		var ret bool
		return ret
	}
	return *o.IsPrivate
}

// GetIsPrivateOk returns a tuple with the IsPrivate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetIsPrivateOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPrivate) {
		return nil, false
	}
	return o.IsPrivate, true
}

// HasIsPrivate returns a boolean if a field has been set.
func (o *ChangeInfo) HasIsPrivate() bool {
	if o != nil && !IsNil(o.IsPrivate) {
		return true
	}

	return false
}

// SetIsPrivate gets a reference to the given bool and assigns it to the IsPrivate field.
func (o *ChangeInfo) SetIsPrivate(v bool) {
	o.IsPrivate = &v
}

// GetWorkInProgress returns the WorkInProgress field value if set, zero value otherwise.
func (o *ChangeInfo) GetWorkInProgress() bool {
	if o == nil || IsNil(o.WorkInProgress) {
		var ret bool
		return ret
	}
	return *o.WorkInProgress
}

// GetWorkInProgressOk returns a tuple with the WorkInProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetWorkInProgressOk() (*bool, bool) {
	if o == nil || IsNil(o.WorkInProgress) {
		return nil, false
	}
	return o.WorkInProgress, true
}

// HasWorkInProgress returns a boolean if a field has been set.
func (o *ChangeInfo) HasWorkInProgress() bool {
	if o != nil && !IsNil(o.WorkInProgress) {
		return true
	}

	return false
}

// SetWorkInProgress gets a reference to the given bool and assigns it to the WorkInProgress field.
func (o *ChangeInfo) SetWorkInProgress(v bool) {
	o.WorkInProgress = &v
}

// GetHasReviewStarted returns the HasReviewStarted field value if set, zero value otherwise.
func (o *ChangeInfo) GetHasReviewStarted() bool {
	if o == nil || IsNil(o.HasReviewStarted) {
		var ret bool
		return ret
	}
	return *o.HasReviewStarted
}

// GetHasReviewStartedOk returns a tuple with the HasReviewStarted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetHasReviewStartedOk() (*bool, bool) {
	if o == nil || IsNil(o.HasReviewStarted) {
		return nil, false
	}
	return o.HasReviewStarted, true
}

// HasHasReviewStarted returns a boolean if a field has been set.
func (o *ChangeInfo) HasHasReviewStarted() bool {
	if o != nil && !IsNil(o.HasReviewStarted) {
		return true
	}

	return false
}

// SetHasReviewStarted gets a reference to the given bool and assigns it to the HasReviewStarted field.
func (o *ChangeInfo) SetHasReviewStarted(v bool) {
	o.HasReviewStarted = &v
}

// GetRevertOf returns the RevertOf field value if set, zero value otherwise.
func (o *ChangeInfo) GetRevertOf() int32 {
	if o == nil || IsNil(o.RevertOf) {
		var ret int32
		return ret
	}
	return *o.RevertOf
}

// GetRevertOfOk returns a tuple with the RevertOf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetRevertOfOk() (*int32, bool) {
	if o == nil || IsNil(o.RevertOf) {
		return nil, false
	}
	return o.RevertOf, true
}

// HasRevertOf returns a boolean if a field has been set.
func (o *ChangeInfo) HasRevertOf() bool {
	if o != nil && !IsNil(o.RevertOf) {
		return true
	}

	return false
}

// SetRevertOf gets a reference to the given int32 and assigns it to the RevertOf field.
func (o *ChangeInfo) SetRevertOf(v int32) {
	o.RevertOf = &v
}

// GetSubmissionId returns the SubmissionId field value if set, zero value otherwise.
func (o *ChangeInfo) GetSubmissionId() string {
	if o == nil || IsNil(o.SubmissionId) {
		var ret string
		return ret
	}
	return *o.SubmissionId
}

// GetSubmissionIdOk returns a tuple with the SubmissionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetSubmissionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubmissionId) {
		return nil, false
	}
	return o.SubmissionId, true
}

// HasSubmissionId returns a boolean if a field has been set.
func (o *ChangeInfo) HasSubmissionId() bool {
	if o != nil && !IsNil(o.SubmissionId) {
		return true
	}

	return false
}

// SetSubmissionId gets a reference to the given string and assigns it to the SubmissionId field.
func (o *ChangeInfo) SetSubmissionId(v string) {
	o.SubmissionId = &v
}

// GetCherryPickOfChange returns the CherryPickOfChange field value if set, zero value otherwise.
func (o *ChangeInfo) GetCherryPickOfChange() int32 {
	if o == nil || IsNil(o.CherryPickOfChange) {
		var ret int32
		return ret
	}
	return *o.CherryPickOfChange
}

// GetCherryPickOfChangeOk returns a tuple with the CherryPickOfChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetCherryPickOfChangeOk() (*int32, bool) {
	if o == nil || IsNil(o.CherryPickOfChange) {
		return nil, false
	}
	return o.CherryPickOfChange, true
}

// HasCherryPickOfChange returns a boolean if a field has been set.
func (o *ChangeInfo) HasCherryPickOfChange() bool {
	if o != nil && !IsNil(o.CherryPickOfChange) {
		return true
	}

	return false
}

// SetCherryPickOfChange gets a reference to the given int32 and assigns it to the CherryPickOfChange field.
func (o *ChangeInfo) SetCherryPickOfChange(v int32) {
	o.CherryPickOfChange = &v
}

// GetCherryPickOfPatchSet returns the CherryPickOfPatchSet field value if set, zero value otherwise.
func (o *ChangeInfo) GetCherryPickOfPatchSet() int32 {
	if o == nil || IsNil(o.CherryPickOfPatchSet) {
		var ret int32
		return ret
	}
	return *o.CherryPickOfPatchSet
}

// GetCherryPickOfPatchSetOk returns a tuple with the CherryPickOfPatchSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetCherryPickOfPatchSetOk() (*int32, bool) {
	if o == nil || IsNil(o.CherryPickOfPatchSet) {
		return nil, false
	}
	return o.CherryPickOfPatchSet, true
}

// HasCherryPickOfPatchSet returns a boolean if a field has been set.
func (o *ChangeInfo) HasCherryPickOfPatchSet() bool {
	if o != nil && !IsNil(o.CherryPickOfPatchSet) {
		return true
	}

	return false
}

// SetCherryPickOfPatchSet gets a reference to the given int32 and assigns it to the CherryPickOfPatchSet field.
func (o *ChangeInfo) SetCherryPickOfPatchSet(v int32) {
	o.CherryPickOfPatchSet = &v
}

// GetMetaRevId returns the MetaRevId field value if set, zero value otherwise.
func (o *ChangeInfo) GetMetaRevId() string {
	if o == nil || IsNil(o.MetaRevId) {
		var ret string
		return ret
	}
	return *o.MetaRevId
}

// GetMetaRevIdOk returns a tuple with the MetaRevId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetMetaRevIdOk() (*string, bool) {
	if o == nil || IsNil(o.MetaRevId) {
		return nil, false
	}
	return o.MetaRevId, true
}

// HasMetaRevId returns a boolean if a field has been set.
func (o *ChangeInfo) HasMetaRevId() bool {
	if o != nil && !IsNil(o.MetaRevId) {
		return true
	}

	return false
}

// SetMetaRevId gets a reference to the given string and assigns it to the MetaRevId field.
func (o *ChangeInfo) SetMetaRevId(v string) {
	o.MetaRevId = &v
}

// GetContainsGitConflicts returns the ContainsGitConflicts field value if set, zero value otherwise.
func (o *ChangeInfo) GetContainsGitConflicts() bool {
	if o == nil || IsNil(o.ContainsGitConflicts) {
		var ret bool
		return ret
	}
	return *o.ContainsGitConflicts
}

// GetContainsGitConflictsOk returns a tuple with the ContainsGitConflicts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetContainsGitConflictsOk() (*bool, bool) {
	if o == nil || IsNil(o.ContainsGitConflicts) {
		return nil, false
	}
	return o.ContainsGitConflicts, true
}

// HasContainsGitConflicts returns a boolean if a field has been set.
func (o *ChangeInfo) HasContainsGitConflicts() bool {
	if o != nil && !IsNil(o.ContainsGitConflicts) {
		return true
	}

	return false
}

// SetContainsGitConflicts gets a reference to the given bool and assigns it to the ContainsGitConflicts field.
func (o *ChangeInfo) SetContainsGitConflicts(v bool) {
	o.ContainsGitConflicts = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *ChangeInfo) GetNumber() int32 {
	if o == nil || IsNil(o.Number) {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *ChangeInfo) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *ChangeInfo) SetNumber(v int32) {
	o.Number = &v
}

// GetVirtualIdNumber returns the VirtualIdNumber field value if set, zero value otherwise.
func (o *ChangeInfo) GetVirtualIdNumber() int32 {
	if o == nil || IsNil(o.VirtualIdNumber) {
		var ret int32
		return ret
	}
	return *o.VirtualIdNumber
}

// GetVirtualIdNumberOk returns a tuple with the VirtualIdNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetVirtualIdNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.VirtualIdNumber) {
		return nil, false
	}
	return o.VirtualIdNumber, true
}

// HasVirtualIdNumber returns a boolean if a field has been set.
func (o *ChangeInfo) HasVirtualIdNumber() bool {
	if o != nil && !IsNil(o.VirtualIdNumber) {
		return true
	}

	return false
}

// SetVirtualIdNumber gets a reference to the given int32 and assigns it to the VirtualIdNumber field.
func (o *ChangeInfo) SetVirtualIdNumber(v int32) {
	o.VirtualIdNumber = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *ChangeInfo) GetOwner() AccountInfo {
	if o == nil || IsNil(o.Owner) {
		var ret AccountInfo
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetOwnerOk() (*AccountInfo, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *ChangeInfo) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given AccountInfo and assigns it to the Owner field.
func (o *ChangeInfo) SetOwner(v AccountInfo) {
	o.Owner = &v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *ChangeInfo) GetActions() map[string]ActionInfo {
	if o == nil || IsNil(o.Actions) {
		var ret map[string]ActionInfo
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetActionsOk() (map[string]ActionInfo, bool) {
	if o == nil || IsNil(o.Actions) {
		return map[string]ActionInfo{}, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *ChangeInfo) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given map[string]ActionInfo and assigns it to the Actions field.
func (o *ChangeInfo) SetActions(v map[string]ActionInfo) {
	o.Actions = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ChangeInfo) GetLabels() map[string]LabelInfo {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]LabelInfo
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetLabelsOk() (map[string]LabelInfo, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]LabelInfo{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ChangeInfo) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]LabelInfo and assigns it to the Labels field.
func (o *ChangeInfo) SetLabels(v map[string]LabelInfo) {
	o.Labels = v
}

// GetPermittedLabels returns the PermittedLabels field value if set, zero value otherwise.
func (o *ChangeInfo) GetPermittedLabels() map[string][]string {
	if o == nil || IsNil(o.PermittedLabels) {
		var ret map[string][]string
		return ret
	}
	return o.PermittedLabels
}

// GetPermittedLabelsOk returns a tuple with the PermittedLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetPermittedLabelsOk() (map[string][]string, bool) {
	if o == nil || IsNil(o.PermittedLabels) {
		return map[string][]string{}, false
	}
	return o.PermittedLabels, true
}

// HasPermittedLabels returns a boolean if a field has been set.
func (o *ChangeInfo) HasPermittedLabels() bool {
	if o != nil && !IsNil(o.PermittedLabels) {
		return true
	}

	return false
}

// SetPermittedLabels gets a reference to the given map[string][]string and assigns it to the PermittedLabels field.
func (o *ChangeInfo) SetPermittedLabels(v map[string][]string) {
	o.PermittedLabels = v
}

// GetRemovableLabels returns the RemovableLabels field value if set, zero value otherwise.
func (o *ChangeInfo) GetRemovableLabels() map[string]map[string][]AccountInfo {
	if o == nil || IsNil(o.RemovableLabels) {
		var ret map[string]map[string][]AccountInfo
		return ret
	}
	return o.RemovableLabels
}

// GetRemovableLabelsOk returns a tuple with the RemovableLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetRemovableLabelsOk() (map[string]map[string][]AccountInfo, bool) {
	if o == nil || IsNil(o.RemovableLabels) {
		return map[string]map[string][]AccountInfo{}, false
	}
	return o.RemovableLabels, true
}

// HasRemovableLabels returns a boolean if a field has been set.
func (o *ChangeInfo) HasRemovableLabels() bool {
	if o != nil && !IsNil(o.RemovableLabels) {
		return true
	}

	return false
}

// SetRemovableLabels gets a reference to the given map[string]map[string][]AccountInfo and assigns it to the RemovableLabels field.
func (o *ChangeInfo) SetRemovableLabels(v map[string]map[string][]AccountInfo) {
	o.RemovableLabels = v
}

// GetRemovableReviewers returns the RemovableReviewers field value if set, zero value otherwise.
func (o *ChangeInfo) GetRemovableReviewers() []AccountInfo {
	if o == nil || IsNil(o.RemovableReviewers) {
		var ret []AccountInfo
		return ret
	}
	return o.RemovableReviewers
}

// GetRemovableReviewersOk returns a tuple with the RemovableReviewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetRemovableReviewersOk() ([]AccountInfo, bool) {
	if o == nil || IsNil(o.RemovableReviewers) {
		return nil, false
	}
	return o.RemovableReviewers, true
}

// HasRemovableReviewers returns a boolean if a field has been set.
func (o *ChangeInfo) HasRemovableReviewers() bool {
	if o != nil && !IsNil(o.RemovableReviewers) {
		return true
	}

	return false
}

// SetRemovableReviewers gets a reference to the given []AccountInfo and assigns it to the RemovableReviewers field.
func (o *ChangeInfo) SetRemovableReviewers(v []AccountInfo) {
	o.RemovableReviewers = v
}

// GetReviewers returns the Reviewers field value if set, zero value otherwise.
func (o *ChangeInfo) GetReviewers() map[string][]AccountInfo {
	if o == nil || IsNil(o.Reviewers) {
		var ret map[string][]AccountInfo
		return ret
	}
	return o.Reviewers
}

// GetReviewersOk returns a tuple with the Reviewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetReviewersOk() (map[string][]AccountInfo, bool) {
	if o == nil || IsNil(o.Reviewers) {
		return map[string][]AccountInfo{}, false
	}
	return o.Reviewers, true
}

// HasReviewers returns a boolean if a field has been set.
func (o *ChangeInfo) HasReviewers() bool {
	if o != nil && !IsNil(o.Reviewers) {
		return true
	}

	return false
}

// SetReviewers gets a reference to the given map[string][]AccountInfo and assigns it to the Reviewers field.
func (o *ChangeInfo) SetReviewers(v map[string][]AccountInfo) {
	o.Reviewers = v
}

// GetPendingReviewers returns the PendingReviewers field value if set, zero value otherwise.
func (o *ChangeInfo) GetPendingReviewers() map[string][]AccountInfo {
	if o == nil || IsNil(o.PendingReviewers) {
		var ret map[string][]AccountInfo
		return ret
	}
	return o.PendingReviewers
}

// GetPendingReviewersOk returns a tuple with the PendingReviewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetPendingReviewersOk() (map[string][]AccountInfo, bool) {
	if o == nil || IsNil(o.PendingReviewers) {
		return map[string][]AccountInfo{}, false
	}
	return o.PendingReviewers, true
}

// HasPendingReviewers returns a boolean if a field has been set.
func (o *ChangeInfo) HasPendingReviewers() bool {
	if o != nil && !IsNil(o.PendingReviewers) {
		return true
	}

	return false
}

// SetPendingReviewers gets a reference to the given map[string][]AccountInfo and assigns it to the PendingReviewers field.
func (o *ChangeInfo) SetPendingReviewers(v map[string][]AccountInfo) {
	o.PendingReviewers = v
}

// GetReviewerUpdates returns the ReviewerUpdates field value if set, zero value otherwise.
func (o *ChangeInfo) GetReviewerUpdates() []ReviewerUpdateInfo {
	if o == nil || IsNil(o.ReviewerUpdates) {
		var ret []ReviewerUpdateInfo
		return ret
	}
	return o.ReviewerUpdates
}

// GetReviewerUpdatesOk returns a tuple with the ReviewerUpdates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetReviewerUpdatesOk() ([]ReviewerUpdateInfo, bool) {
	if o == nil || IsNil(o.ReviewerUpdates) {
		return nil, false
	}
	return o.ReviewerUpdates, true
}

// HasReviewerUpdates returns a boolean if a field has been set.
func (o *ChangeInfo) HasReviewerUpdates() bool {
	if o != nil && !IsNil(o.ReviewerUpdates) {
		return true
	}

	return false
}

// SetReviewerUpdates gets a reference to the given []ReviewerUpdateInfo and assigns it to the ReviewerUpdates field.
func (o *ChangeInfo) SetReviewerUpdates(v []ReviewerUpdateInfo) {
	o.ReviewerUpdates = v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *ChangeInfo) GetMessages() []ChangeMessageInfo {
	if o == nil || IsNil(o.Messages) {
		var ret []ChangeMessageInfo
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetMessagesOk() ([]ChangeMessageInfo, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *ChangeInfo) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []ChangeMessageInfo and assigns it to the Messages field.
func (o *ChangeInfo) SetMessages(v []ChangeMessageInfo) {
	o.Messages = v
}

// GetCurrentRevisionNumber returns the CurrentRevisionNumber field value if set, zero value otherwise.
func (o *ChangeInfo) GetCurrentRevisionNumber() int32 {
	if o == nil || IsNil(o.CurrentRevisionNumber) {
		var ret int32
		return ret
	}
	return *o.CurrentRevisionNumber
}

// GetCurrentRevisionNumberOk returns a tuple with the CurrentRevisionNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetCurrentRevisionNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentRevisionNumber) {
		return nil, false
	}
	return o.CurrentRevisionNumber, true
}

// HasCurrentRevisionNumber returns a boolean if a field has been set.
func (o *ChangeInfo) HasCurrentRevisionNumber() bool {
	if o != nil && !IsNil(o.CurrentRevisionNumber) {
		return true
	}

	return false
}

// SetCurrentRevisionNumber gets a reference to the given int32 and assigns it to the CurrentRevisionNumber field.
func (o *ChangeInfo) SetCurrentRevisionNumber(v int32) {
	o.CurrentRevisionNumber = &v
}

// GetCurrentRevision returns the CurrentRevision field value if set, zero value otherwise.
func (o *ChangeInfo) GetCurrentRevision() string {
	if o == nil || IsNil(o.CurrentRevision) {
		var ret string
		return ret
	}
	return *o.CurrentRevision
}

// GetCurrentRevisionOk returns a tuple with the CurrentRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetCurrentRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentRevision) {
		return nil, false
	}
	return o.CurrentRevision, true
}

// HasCurrentRevision returns a boolean if a field has been set.
func (o *ChangeInfo) HasCurrentRevision() bool {
	if o != nil && !IsNil(o.CurrentRevision) {
		return true
	}

	return false
}

// SetCurrentRevision gets a reference to the given string and assigns it to the CurrentRevision field.
func (o *ChangeInfo) SetCurrentRevision(v string) {
	o.CurrentRevision = &v
}

// GetRevisions returns the Revisions field value if set, zero value otherwise.
func (o *ChangeInfo) GetRevisions() map[string]RevisionInfo {
	if o == nil || IsNil(o.Revisions) {
		var ret map[string]RevisionInfo
		return ret
	}
	return o.Revisions
}

// GetRevisionsOk returns a tuple with the Revisions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetRevisionsOk() (map[string]RevisionInfo, bool) {
	if o == nil || IsNil(o.Revisions) {
		return map[string]RevisionInfo{}, false
	}
	return o.Revisions, true
}

// HasRevisions returns a boolean if a field has been set.
func (o *ChangeInfo) HasRevisions() bool {
	if o != nil && !IsNil(o.Revisions) {
		return true
	}

	return false
}

// SetRevisions gets a reference to the given map[string]RevisionInfo and assigns it to the Revisions field.
func (o *ChangeInfo) SetRevisions(v map[string]RevisionInfo) {
	o.Revisions = v
}

// GetMoreChanges returns the MoreChanges field value if set, zero value otherwise.
func (o *ChangeInfo) GetMoreChanges() bool {
	if o == nil || IsNil(o.MoreChanges) {
		var ret bool
		return ret
	}
	return *o.MoreChanges
}

// GetMoreChangesOk returns a tuple with the MoreChanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetMoreChangesOk() (*bool, bool) {
	if o == nil || IsNil(o.MoreChanges) {
		return nil, false
	}
	return o.MoreChanges, true
}

// HasMoreChanges returns a boolean if a field has been set.
func (o *ChangeInfo) HasMoreChanges() bool {
	if o != nil && !IsNil(o.MoreChanges) {
		return true
	}

	return false
}

// SetMoreChanges gets a reference to the given bool and assigns it to the MoreChanges field.
func (o *ChangeInfo) SetMoreChanges(v bool) {
	o.MoreChanges = &v
}

// GetProblems returns the Problems field value if set, zero value otherwise.
func (o *ChangeInfo) GetProblems() []ProblemInfo {
	if o == nil || IsNil(o.Problems) {
		var ret []ProblemInfo
		return ret
	}
	return o.Problems
}

// GetProblemsOk returns a tuple with the Problems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetProblemsOk() ([]ProblemInfo, bool) {
	if o == nil || IsNil(o.Problems) {
		return nil, false
	}
	return o.Problems, true
}

// HasProblems returns a boolean if a field has been set.
func (o *ChangeInfo) HasProblems() bool {
	if o != nil && !IsNil(o.Problems) {
		return true
	}

	return false
}

// SetProblems gets a reference to the given []ProblemInfo and assigns it to the Problems field.
func (o *ChangeInfo) SetProblems(v []ProblemInfo) {
	o.Problems = v
}

// GetPlugins returns the Plugins field value if set, zero value otherwise.
func (o *ChangeInfo) GetPlugins() []PluginDefinedInfo {
	if o == nil || IsNil(o.Plugins) {
		var ret []PluginDefinedInfo
		return ret
	}
	return o.Plugins
}

// GetPluginsOk returns a tuple with the Plugins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetPluginsOk() ([]PluginDefinedInfo, bool) {
	if o == nil || IsNil(o.Plugins) {
		return nil, false
	}
	return o.Plugins, true
}

// HasPlugins returns a boolean if a field has been set.
func (o *ChangeInfo) HasPlugins() bool {
	if o != nil && !IsNil(o.Plugins) {
		return true
	}

	return false
}

// SetPlugins gets a reference to the given []PluginDefinedInfo and assigns it to the Plugins field.
func (o *ChangeInfo) SetPlugins(v []PluginDefinedInfo) {
	o.Plugins = v
}

// GetTrackingIds returns the TrackingIds field value if set, zero value otherwise.
func (o *ChangeInfo) GetTrackingIds() []TrackingIdInfo {
	if o == nil || IsNil(o.TrackingIds) {
		var ret []TrackingIdInfo
		return ret
	}
	return o.TrackingIds
}

// GetTrackingIdsOk returns a tuple with the TrackingIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetTrackingIdsOk() ([]TrackingIdInfo, bool) {
	if o == nil || IsNil(o.TrackingIds) {
		return nil, false
	}
	return o.TrackingIds, true
}

// HasTrackingIds returns a boolean if a field has been set.
func (o *ChangeInfo) HasTrackingIds() bool {
	if o != nil && !IsNil(o.TrackingIds) {
		return true
	}

	return false
}

// SetTrackingIds gets a reference to the given []TrackingIdInfo and assigns it to the TrackingIds field.
func (o *ChangeInfo) SetTrackingIds(v []TrackingIdInfo) {
	o.TrackingIds = v
}

// GetRequirements returns the Requirements field value if set, zero value otherwise.
func (o *ChangeInfo) GetRequirements() []LegacySubmitRequirementInfo {
	if o == nil || IsNil(o.Requirements) {
		var ret []LegacySubmitRequirementInfo
		return ret
	}
	return o.Requirements
}

// GetRequirementsOk returns a tuple with the Requirements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetRequirementsOk() ([]LegacySubmitRequirementInfo, bool) {
	if o == nil || IsNil(o.Requirements) {
		return nil, false
	}
	return o.Requirements, true
}

// HasRequirements returns a boolean if a field has been set.
func (o *ChangeInfo) HasRequirements() bool {
	if o != nil && !IsNil(o.Requirements) {
		return true
	}

	return false
}

// SetRequirements gets a reference to the given []LegacySubmitRequirementInfo and assigns it to the Requirements field.
func (o *ChangeInfo) SetRequirements(v []LegacySubmitRequirementInfo) {
	o.Requirements = v
}

// GetSubmitRecords returns the SubmitRecords field value if set, zero value otherwise.
func (o *ChangeInfo) GetSubmitRecords() []SubmitRecordInfo {
	if o == nil || IsNil(o.SubmitRecords) {
		var ret []SubmitRecordInfo
		return ret
	}
	return o.SubmitRecords
}

// GetSubmitRecordsOk returns a tuple with the SubmitRecords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetSubmitRecordsOk() ([]SubmitRecordInfo, bool) {
	if o == nil || IsNil(o.SubmitRecords) {
		return nil, false
	}
	return o.SubmitRecords, true
}

// HasSubmitRecords returns a boolean if a field has been set.
func (o *ChangeInfo) HasSubmitRecords() bool {
	if o != nil && !IsNil(o.SubmitRecords) {
		return true
	}

	return false
}

// SetSubmitRecords gets a reference to the given []SubmitRecordInfo and assigns it to the SubmitRecords field.
func (o *ChangeInfo) SetSubmitRecords(v []SubmitRecordInfo) {
	o.SubmitRecords = v
}

// GetSubmitRequirements returns the SubmitRequirements field value if set, zero value otherwise.
func (o *ChangeInfo) GetSubmitRequirements() []SubmitRequirementResultInfo {
	if o == nil || IsNil(o.SubmitRequirements) {
		var ret []SubmitRequirementResultInfo
		return ret
	}
	return o.SubmitRequirements
}

// GetSubmitRequirementsOk returns a tuple with the SubmitRequirements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeInfo) GetSubmitRequirementsOk() ([]SubmitRequirementResultInfo, bool) {
	if o == nil || IsNil(o.SubmitRequirements) {
		return nil, false
	}
	return o.SubmitRequirements, true
}

// HasSubmitRequirements returns a boolean if a field has been set.
func (o *ChangeInfo) HasSubmitRequirements() bool {
	if o != nil && !IsNil(o.SubmitRequirements) {
		return true
	}

	return false
}

// SetSubmitRequirements gets a reference to the given []SubmitRequirementResultInfo and assigns it to the SubmitRequirements field.
func (o *ChangeInfo) SetSubmitRequirements(v []SubmitRequirementResultInfo) {
	o.SubmitRequirements = v
}

func (o ChangeInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.TripletId) {
		toSerialize["triplet_id"] = o.TripletId
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.FullBranch) {
		toSerialize["full_branch"] = o.FullBranch
	}
	if !IsNil(o.Topic) {
		toSerialize["topic"] = o.Topic
	}
	if !IsNil(o.AttentionSet) {
		toSerialize["attention_set"] = o.AttentionSet
	}
	if !IsNil(o.RemovedFromAttentionSet) {
		toSerialize["removed_from_attention_set"] = o.RemovedFromAttentionSet
	}
	if !IsNil(o.CustomKeyedValues) {
		toSerialize["custom_keyed_values"] = o.CustomKeyedValues
	}
	if !IsNil(o.Hashtags) {
		toSerialize["hashtags"] = o.Hashtags
	}
	if !IsNil(o.ChangeId) {
		toSerialize["change_id"] = o.ChangeId
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.Submitted) {
		toSerialize["submitted"] = o.Submitted
	}
	if !IsNil(o.Submitter) {
		toSerialize["submitter"] = o.Submitter
	}
	if !IsNil(o.Starred) {
		toSerialize["starred"] = o.Starred
	}
	if !IsNil(o.Stars) {
		toSerialize["stars"] = o.Stars
	}
	if !IsNil(o.Reviewed) {
		toSerialize["reviewed"] = o.Reviewed
	}
	if !IsNil(o.SubmitType) {
		toSerialize["submit_type"] = o.SubmitType
	}
	if !IsNil(o.Mergeable) {
		toSerialize["mergeable"] = o.Mergeable
	}
	if !IsNil(o.Submittable) {
		toSerialize["submittable"] = o.Submittable
	}
	if !IsNil(o.Insertions) {
		toSerialize["insertions"] = o.Insertions
	}
	if !IsNil(o.Deletions) {
		toSerialize["deletions"] = o.Deletions
	}
	if !IsNil(o.TotalCommentCount) {
		toSerialize["total_comment_count"] = o.TotalCommentCount
	}
	if !IsNil(o.UnresolvedCommentCount) {
		toSerialize["unresolved_comment_count"] = o.UnresolvedCommentCount
	}
	if !IsNil(o.IsPrivate) {
		toSerialize["is_private"] = o.IsPrivate
	}
	if !IsNil(o.WorkInProgress) {
		toSerialize["work_in_progress"] = o.WorkInProgress
	}
	if !IsNil(o.HasReviewStarted) {
		toSerialize["has_review_started"] = o.HasReviewStarted
	}
	if !IsNil(o.RevertOf) {
		toSerialize["revert_of"] = o.RevertOf
	}
	if !IsNil(o.SubmissionId) {
		toSerialize["submission_id"] = o.SubmissionId
	}
	if !IsNil(o.CherryPickOfChange) {
		toSerialize["cherry_pick_of_change"] = o.CherryPickOfChange
	}
	if !IsNil(o.CherryPickOfPatchSet) {
		toSerialize["cherry_pick_of_patch_set"] = o.CherryPickOfPatchSet
	}
	if !IsNil(o.MetaRevId) {
		toSerialize["meta_rev_id"] = o.MetaRevId
	}
	if !IsNil(o.ContainsGitConflicts) {
		toSerialize["contains_git_conflicts"] = o.ContainsGitConflicts
	}
	if !IsNil(o.Number) {
		toSerialize["_number"] = o.Number
	}
	if !IsNil(o.VirtualIdNumber) {
		toSerialize["virtual_id_number"] = o.VirtualIdNumber
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.PermittedLabels) {
		toSerialize["permitted_labels"] = o.PermittedLabels
	}
	if !IsNil(o.RemovableLabels) {
		toSerialize["removable_labels"] = o.RemovableLabels
	}
	if !IsNil(o.RemovableReviewers) {
		toSerialize["removable_reviewers"] = o.RemovableReviewers
	}
	if !IsNil(o.Reviewers) {
		toSerialize["reviewers"] = o.Reviewers
	}
	if !IsNil(o.PendingReviewers) {
		toSerialize["pending_reviewers"] = o.PendingReviewers
	}
	if !IsNil(o.ReviewerUpdates) {
		toSerialize["reviewer_updates"] = o.ReviewerUpdates
	}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	if !IsNil(o.CurrentRevisionNumber) {
		toSerialize["current_revision_number"] = o.CurrentRevisionNumber
	}
	if !IsNil(o.CurrentRevision) {
		toSerialize["current_revision"] = o.CurrentRevision
	}
	if !IsNil(o.Revisions) {
		toSerialize["revisions"] = o.Revisions
	}
	if !IsNil(o.MoreChanges) {
		toSerialize["_more_changes"] = o.MoreChanges
	}
	if !IsNil(o.Problems) {
		toSerialize["problems"] = o.Problems
	}
	if !IsNil(o.Plugins) {
		toSerialize["plugins"] = o.Plugins
	}
	if !IsNil(o.TrackingIds) {
		toSerialize["tracking_ids"] = o.TrackingIds
	}
	if !IsNil(o.Requirements) {
		toSerialize["requirements"] = o.Requirements
	}
	if !IsNil(o.SubmitRecords) {
		toSerialize["submit_records"] = o.SubmitRecords
	}
	if !IsNil(o.SubmitRequirements) {
		toSerialize["submit_requirements"] = o.SubmitRequirements
	}
	return toSerialize, nil
}

type NullableChangeInfo struct {
	value *ChangeInfo
	isSet bool
}

func (v NullableChangeInfo) Get() *ChangeInfo {
	return v.value
}

func (v *NullableChangeInfo) Set(val *ChangeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeInfo(val *ChangeInfo) *NullableChangeInfo {
	return &NullableChangeInfo{value: val, isSet: true}
}

func (v NullableChangeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


