/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the FixReplacementInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FixReplacementInfo{}

// FixReplacementInfo struct for FixReplacementInfo
type FixReplacementInfo struct {
	// The path of the file which should be modified. Any file in the repository may be modified. The commit message can be modified via the magic file /COMMIT_MSG though only the part below the generated header of that magic file can be modified.
	Path *string `json:"path,omitempty"`
	// A CommentRange indicating which content of the file should be replaced. Lines in the file are assumed to be separated by the line feed character.
	Range *Range `json:"range,omitempty"`
	// The content which should be used instead of the current one.
	Replacement *string `json:"replacement,omitempty"`
}

// NewFixReplacementInfo instantiates a new FixReplacementInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFixReplacementInfo() *FixReplacementInfo {
	this := FixReplacementInfo{}
	return &this
}

// NewFixReplacementInfoWithDefaults instantiates a new FixReplacementInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFixReplacementInfoWithDefaults() *FixReplacementInfo {
	this := FixReplacementInfo{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *FixReplacementInfo) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FixReplacementInfo) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *FixReplacementInfo) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *FixReplacementInfo) SetPath(v string) {
	o.Path = &v
}

// GetRange returns the Range field value if set, zero value otherwise.
func (o *FixReplacementInfo) GetRange() Range {
	if o == nil || IsNil(o.Range) {
		var ret Range
		return ret
	}
	return *o.Range
}

// GetRangeOk returns a tuple with the Range field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FixReplacementInfo) GetRangeOk() (*Range, bool) {
	if o == nil || IsNil(o.Range) {
		return nil, false
	}
	return o.Range, true
}

// HasRange returns a boolean if a field has been set.
func (o *FixReplacementInfo) HasRange() bool {
	if o != nil && !IsNil(o.Range) {
		return true
	}

	return false
}

// SetRange gets a reference to the given Range and assigns it to the Range field.
func (o *FixReplacementInfo) SetRange(v Range) {
	o.Range = &v
}

// GetReplacement returns the Replacement field value if set, zero value otherwise.
func (o *FixReplacementInfo) GetReplacement() string {
	if o == nil || IsNil(o.Replacement) {
		var ret string
		return ret
	}
	return *o.Replacement
}

// GetReplacementOk returns a tuple with the Replacement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FixReplacementInfo) GetReplacementOk() (*string, bool) {
	if o == nil || IsNil(o.Replacement) {
		return nil, false
	}
	return o.Replacement, true
}

// HasReplacement returns a boolean if a field has been set.
func (o *FixReplacementInfo) HasReplacement() bool {
	if o != nil && !IsNil(o.Replacement) {
		return true
	}

	return false
}

// SetReplacement gets a reference to the given string and assigns it to the Replacement field.
func (o *FixReplacementInfo) SetReplacement(v string) {
	o.Replacement = &v
}

func (o FixReplacementInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FixReplacementInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Range) {
		toSerialize["range"] = o.Range
	}
	if !IsNil(o.Replacement) {
		toSerialize["replacement"] = o.Replacement
	}
	return toSerialize, nil
}

type NullableFixReplacementInfo struct {
	value *FixReplacementInfo
	isSet bool
}

func (v NullableFixReplacementInfo) Get() *FixReplacementInfo {
	return v.value
}

func (v *NullableFixReplacementInfo) Set(val *FixReplacementInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFixReplacementInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFixReplacementInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFixReplacementInfo(val *FixReplacementInfo) *NullableFixReplacementInfo {
	return &NullableFixReplacementInfo{value: val, isSet: true}
}

func (v NullableFixReplacementInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFixReplacementInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


