/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the InheritedBooleanInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InheritedBooleanInfo{}

// InheritedBooleanInfo struct for InheritedBooleanInfo
type InheritedBooleanInfo struct {
	// The effective boolean value.
	Value *bool `json:"value,omitempty"`
	// The configured value, can be TRUE, FALSE or INHERIT.
	ConfiguredValue *InheritableBoolean `json:"configured_value,omitempty"`
	// The boolean value inherited from the parent. + Not set if there is no parent.
	InheritedValue *bool `json:"inherited_value,omitempty"`
}

// NewInheritedBooleanInfo instantiates a new InheritedBooleanInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInheritedBooleanInfo() *InheritedBooleanInfo {
	this := InheritedBooleanInfo{}
	return &this
}

// NewInheritedBooleanInfoWithDefaults instantiates a new InheritedBooleanInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInheritedBooleanInfoWithDefaults() *InheritedBooleanInfo {
	this := InheritedBooleanInfo{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *InheritedBooleanInfo) GetValue() bool {
	if o == nil || IsNil(o.Value) {
		var ret bool
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InheritedBooleanInfo) GetValueOk() (*bool, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *InheritedBooleanInfo) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given bool and assigns it to the Value field.
func (o *InheritedBooleanInfo) SetValue(v bool) {
	o.Value = &v
}

// GetConfiguredValue returns the ConfiguredValue field value if set, zero value otherwise.
func (o *InheritedBooleanInfo) GetConfiguredValue() InheritableBoolean {
	if o == nil || IsNil(o.ConfiguredValue) {
		var ret InheritableBoolean
		return ret
	}
	return *o.ConfiguredValue
}

// GetConfiguredValueOk returns a tuple with the ConfiguredValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InheritedBooleanInfo) GetConfiguredValueOk() (*InheritableBoolean, bool) {
	if o == nil || IsNil(o.ConfiguredValue) {
		return nil, false
	}
	return o.ConfiguredValue, true
}

// HasConfiguredValue returns a boolean if a field has been set.
func (o *InheritedBooleanInfo) HasConfiguredValue() bool {
	if o != nil && !IsNil(o.ConfiguredValue) {
		return true
	}

	return false
}

// SetConfiguredValue gets a reference to the given InheritableBoolean and assigns it to the ConfiguredValue field.
func (o *InheritedBooleanInfo) SetConfiguredValue(v InheritableBoolean) {
	o.ConfiguredValue = &v
}

// GetInheritedValue returns the InheritedValue field value if set, zero value otherwise.
func (o *InheritedBooleanInfo) GetInheritedValue() bool {
	if o == nil || IsNil(o.InheritedValue) {
		var ret bool
		return ret
	}
	return *o.InheritedValue
}

// GetInheritedValueOk returns a tuple with the InheritedValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InheritedBooleanInfo) GetInheritedValueOk() (*bool, bool) {
	if o == nil || IsNil(o.InheritedValue) {
		return nil, false
	}
	return o.InheritedValue, true
}

// HasInheritedValue returns a boolean if a field has been set.
func (o *InheritedBooleanInfo) HasInheritedValue() bool {
	if o != nil && !IsNil(o.InheritedValue) {
		return true
	}

	return false
}

// SetInheritedValue gets a reference to the given bool and assigns it to the InheritedValue field.
func (o *InheritedBooleanInfo) SetInheritedValue(v bool) {
	o.InheritedValue = &v
}

func (o InheritedBooleanInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InheritedBooleanInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.ConfiguredValue) {
		toSerialize["configured_value"] = o.ConfiguredValue
	}
	if !IsNil(o.InheritedValue) {
		toSerialize["inherited_value"] = o.InheritedValue
	}
	return toSerialize, nil
}

type NullableInheritedBooleanInfo struct {
	value *InheritedBooleanInfo
	isSet bool
}

func (v NullableInheritedBooleanInfo) Get() *InheritedBooleanInfo {
	return v.value
}

func (v *NullableInheritedBooleanInfo) Set(val *InheritedBooleanInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableInheritedBooleanInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableInheritedBooleanInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInheritedBooleanInfo(val *InheritedBooleanInfo) *NullableInheritedBooleanInfo {
	return &NullableInheritedBooleanInfo{value: val, isSet: true}
}

func (v NullableInheritedBooleanInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInheritedBooleanInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


