/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the DownloadInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DownloadInfo{}

// DownloadInfo struct for DownloadInfo
type DownloadInfo struct {
	// The supported download schemes as a map which maps the scheme name to a of DownloadSchemeInfo entity.
	Schemes map[string]DownloadSchemeInfo `json:"schemes,omitempty"`
	// List of supported archive formats. Possible values are tgz, tar, tbz2 and txz.
	Archives []string `json:"archives,omitempty"`
}

// NewDownloadInfo instantiates a new DownloadInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDownloadInfo() *DownloadInfo {
	this := DownloadInfo{}
	return &this
}

// NewDownloadInfoWithDefaults instantiates a new DownloadInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDownloadInfoWithDefaults() *DownloadInfo {
	this := DownloadInfo{}
	return &this
}

// GetSchemes returns the Schemes field value if set, zero value otherwise.
func (o *DownloadInfo) GetSchemes() map[string]DownloadSchemeInfo {
	if o == nil || IsNil(o.Schemes) {
		var ret map[string]DownloadSchemeInfo
		return ret
	}
	return o.Schemes
}

// GetSchemesOk returns a tuple with the Schemes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadInfo) GetSchemesOk() (map[string]DownloadSchemeInfo, bool) {
	if o == nil || IsNil(o.Schemes) {
		return map[string]DownloadSchemeInfo{}, false
	}
	return o.Schemes, true
}

// HasSchemes returns a boolean if a field has been set.
func (o *DownloadInfo) HasSchemes() bool {
	if o != nil && !IsNil(o.Schemes) {
		return true
	}

	return false
}

// SetSchemes gets a reference to the given map[string]DownloadSchemeInfo and assigns it to the Schemes field.
func (o *DownloadInfo) SetSchemes(v map[string]DownloadSchemeInfo) {
	o.Schemes = v
}

// GetArchives returns the Archives field value if set, zero value otherwise.
func (o *DownloadInfo) GetArchives() []string {
	if o == nil || IsNil(o.Archives) {
		var ret []string
		return ret
	}
	return o.Archives
}

// GetArchivesOk returns a tuple with the Archives field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadInfo) GetArchivesOk() ([]string, bool) {
	if o == nil || IsNil(o.Archives) {
		return nil, false
	}
	return o.Archives, true
}

// HasArchives returns a boolean if a field has been set.
func (o *DownloadInfo) HasArchives() bool {
	if o != nil && !IsNil(o.Archives) {
		return true
	}

	return false
}

// SetArchives gets a reference to the given []string and assigns it to the Archives field.
func (o *DownloadInfo) SetArchives(v []string) {
	o.Archives = v
}

func (o DownloadInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DownloadInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schemes) {
		toSerialize["schemes"] = o.Schemes
	}
	if !IsNil(o.Archives) {
		toSerialize["archives"] = o.Archives
	}
	return toSerialize, nil
}

type NullableDownloadInfo struct {
	value *DownloadInfo
	isSet bool
}

func (v NullableDownloadInfo) Get() *DownloadInfo {
	return v.value
}

func (v *NullableDownloadInfo) Set(val *DownloadInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDownloadInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDownloadInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDownloadInfo(val *DownloadInfo) *NullableDownloadInfo {
	return &NullableDownloadInfo{value: val, isSet: true}
}

func (v NullableDownloadInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDownloadInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


