/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// GetConfigServerVersion200Response - struct for GetConfigServerVersion200Response
type GetConfigServerVersion200Response struct {
	GetConfigServerVersion200ResponseOneOf *GetConfigServerVersion200ResponseOneOf
	String *string
}

// GetConfigServerVersion200ResponseOneOfAsGetConfigServerVersion200Response is a convenience function that returns GetConfigServerVersion200ResponseOneOf wrapped in GetConfigServerVersion200Response
func GetConfigServerVersion200ResponseOneOfAsGetConfigServerVersion200Response(v *GetConfigServerVersion200ResponseOneOf) GetConfigServerVersion200Response {
	return GetConfigServerVersion200Response{
		GetConfigServerVersion200ResponseOneOf: v,
	}
}

// stringAsGetConfigServerVersion200Response is a convenience function that returns string wrapped in GetConfigServerVersion200Response
func StringAsGetConfigServerVersion200Response(v *string) GetConfigServerVersion200Response {
	return GetConfigServerVersion200Response{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetConfigServerVersion200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into GetConfigServerVersion200ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.GetConfigServerVersion200ResponseOneOf)
	if err == nil {
		jsonGetConfigServerVersion200ResponseOneOf, _ := json.Marshal(dst.GetConfigServerVersion200ResponseOneOf)
		if string(jsonGetConfigServerVersion200ResponseOneOf) == "{}" { // empty struct
			dst.GetConfigServerVersion200ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.GetConfigServerVersion200ResponseOneOf); err != nil {
				dst.GetConfigServerVersion200ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetConfigServerVersion200ResponseOneOf = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.GetConfigServerVersion200ResponseOneOf = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetConfigServerVersion200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(GetConfigServerVersion200Response): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(GetConfigServerVersion200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetConfigServerVersion200Response) MarshalJSON() ([]byte, error) {
	if src.GetConfigServerVersion200ResponseOneOf != nil {
		return json.Marshal(&src.GetConfigServerVersion200ResponseOneOf)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetConfigServerVersion200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.GetConfigServerVersion200ResponseOneOf != nil {
		return obj.GetConfigServerVersion200ResponseOneOf
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj GetConfigServerVersion200Response) GetActualInstanceValue() (interface{}) {
	if obj.GetConfigServerVersion200ResponseOneOf != nil {
		return *obj.GetConfigServerVersion200ResponseOneOf
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableGetConfigServerVersion200Response struct {
	value *GetConfigServerVersion200Response
	isSet bool
}

func (v NullableGetConfigServerVersion200Response) Get() *GetConfigServerVersion200Response {
	return v.value
}

func (v *NullableGetConfigServerVersion200Response) Set(val *GetConfigServerVersion200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConfigServerVersion200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConfigServerVersion200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConfigServerVersion200Response(val *GetConfigServerVersion200Response) *NullableGetConfigServerVersion200Response {
	return &NullableGetConfigServerVersion200Response{value: val, isSet: true}
}

func (v NullableGetConfigServerVersion200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConfigServerVersion200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


