/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ChangeMessageInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeMessageInfo{}

// ChangeMessageInfo struct for ChangeMessageInfo
type ChangeMessageInfo struct {
	// The ID of the message.
	Id *string `json:"id,omitempty"`
	// Value of the tag field from ReviewInput set while posting the review. Votes/comments that contain tag with 'autogenerated:' prefix can be filtered out in the web UI. NOTE: To apply different tags on different votes/comments multiple invocations of the REST call are required.
	Tag *string `json:"tag,omitempty"`
	// Author of the message as an AccountInfo entity. + Unset if written by the Gerrit system.
	Author *AccountInfo `json:"author,omitempty"`
	// Real author of the message as an AccountInfo entity. + Only set if the message was posted on behalf of another user.
	RealAuthor *AccountInfo `json:"real_author,omitempty"`
	// The timestamp this message was posted.
	Date *string `json:"date,omitempty"`
	// The text left by the user or Gerrit system. Accounts are served as account IDs inlined in the text as <GERRIT_ACCOUNT_18419>. All accounts, used in message, can be found in accounts_in_message field.
	Message *string `json:"message,omitempty"`
	// AccountInfo list, used in message.
	AccountsInMessage []AccountInfo `json:"accounts_in_message,omitempty"`
	// Which patchset (if any) generated this message.
	RevisionNumber *int32 `json:"_revision_number,omitempty"`
}

// NewChangeMessageInfo instantiates a new ChangeMessageInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeMessageInfo() *ChangeMessageInfo {
	this := ChangeMessageInfo{}
	return &this
}

// NewChangeMessageInfoWithDefaults instantiates a new ChangeMessageInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeMessageInfoWithDefaults() *ChangeMessageInfo {
	this := ChangeMessageInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ChangeMessageInfo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeMessageInfo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ChangeMessageInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ChangeMessageInfo) SetId(v string) {
	o.Id = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *ChangeMessageInfo) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeMessageInfo) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *ChangeMessageInfo) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *ChangeMessageInfo) SetTag(v string) {
	o.Tag = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *ChangeMessageInfo) GetAuthor() AccountInfo {
	if o == nil || IsNil(o.Author) {
		var ret AccountInfo
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeMessageInfo) GetAuthorOk() (*AccountInfo, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *ChangeMessageInfo) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given AccountInfo and assigns it to the Author field.
func (o *ChangeMessageInfo) SetAuthor(v AccountInfo) {
	o.Author = &v
}

// GetRealAuthor returns the RealAuthor field value if set, zero value otherwise.
func (o *ChangeMessageInfo) GetRealAuthor() AccountInfo {
	if o == nil || IsNil(o.RealAuthor) {
		var ret AccountInfo
		return ret
	}
	return *o.RealAuthor
}

// GetRealAuthorOk returns a tuple with the RealAuthor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeMessageInfo) GetRealAuthorOk() (*AccountInfo, bool) {
	if o == nil || IsNil(o.RealAuthor) {
		return nil, false
	}
	return o.RealAuthor, true
}

// HasRealAuthor returns a boolean if a field has been set.
func (o *ChangeMessageInfo) HasRealAuthor() bool {
	if o != nil && !IsNil(o.RealAuthor) {
		return true
	}

	return false
}

// SetRealAuthor gets a reference to the given AccountInfo and assigns it to the RealAuthor field.
func (o *ChangeMessageInfo) SetRealAuthor(v AccountInfo) {
	o.RealAuthor = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ChangeMessageInfo) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeMessageInfo) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ChangeMessageInfo) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *ChangeMessageInfo) SetDate(v string) {
	o.Date = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ChangeMessageInfo) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeMessageInfo) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ChangeMessageInfo) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ChangeMessageInfo) SetMessage(v string) {
	o.Message = &v
}

// GetAccountsInMessage returns the AccountsInMessage field value if set, zero value otherwise.
func (o *ChangeMessageInfo) GetAccountsInMessage() []AccountInfo {
	if o == nil || IsNil(o.AccountsInMessage) {
		var ret []AccountInfo
		return ret
	}
	return o.AccountsInMessage
}

// GetAccountsInMessageOk returns a tuple with the AccountsInMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeMessageInfo) GetAccountsInMessageOk() ([]AccountInfo, bool) {
	if o == nil || IsNil(o.AccountsInMessage) {
		return nil, false
	}
	return o.AccountsInMessage, true
}

// HasAccountsInMessage returns a boolean if a field has been set.
func (o *ChangeMessageInfo) HasAccountsInMessage() bool {
	if o != nil && !IsNil(o.AccountsInMessage) {
		return true
	}

	return false
}

// SetAccountsInMessage gets a reference to the given []AccountInfo and assigns it to the AccountsInMessage field.
func (o *ChangeMessageInfo) SetAccountsInMessage(v []AccountInfo) {
	o.AccountsInMessage = v
}

// GetRevisionNumber returns the RevisionNumber field value if set, zero value otherwise.
func (o *ChangeMessageInfo) GetRevisionNumber() int32 {
	if o == nil || IsNil(o.RevisionNumber) {
		var ret int32
		return ret
	}
	return *o.RevisionNumber
}

// GetRevisionNumberOk returns a tuple with the RevisionNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeMessageInfo) GetRevisionNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.RevisionNumber) {
		return nil, false
	}
	return o.RevisionNumber, true
}

// HasRevisionNumber returns a boolean if a field has been set.
func (o *ChangeMessageInfo) HasRevisionNumber() bool {
	if o != nil && !IsNil(o.RevisionNumber) {
		return true
	}

	return false
}

// SetRevisionNumber gets a reference to the given int32 and assigns it to the RevisionNumber field.
func (o *ChangeMessageInfo) SetRevisionNumber(v int32) {
	o.RevisionNumber = &v
}

func (o ChangeMessageInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeMessageInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.RealAuthor) {
		toSerialize["real_author"] = o.RealAuthor
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.AccountsInMessage) {
		toSerialize["accounts_in_message"] = o.AccountsInMessage
	}
	if !IsNil(o.RevisionNumber) {
		toSerialize["_revision_number"] = o.RevisionNumber
	}
	return toSerialize, nil
}

type NullableChangeMessageInfo struct {
	value *ChangeMessageInfo
	isSet bool
}

func (v NullableChangeMessageInfo) Get() *ChangeMessageInfo {
	return v.value
}

func (v *NullableChangeMessageInfo) Set(val *ChangeMessageInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeMessageInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeMessageInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeMessageInfo(val *ChangeMessageInfo) *NullableChangeMessageInfo {
	return &NullableChangeMessageInfo{value: val, isSet: true}
}

func (v NullableChangeMessageInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeMessageInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


