/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ValidationOptionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationOptionInfo{}

// ValidationOptionInfo struct for ValidationOptionInfo
type ValidationOptionInfo struct {
	// The name of the validation option.
	Name *string `json:"name,omitempty"`
	// The description of the validation option.
	Description *string `json:"description,omitempty"`
}

// NewValidationOptionInfo instantiates a new ValidationOptionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationOptionInfo() *ValidationOptionInfo {
	this := ValidationOptionInfo{}
	return &this
}

// NewValidationOptionInfoWithDefaults instantiates a new ValidationOptionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationOptionInfoWithDefaults() *ValidationOptionInfo {
	this := ValidationOptionInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ValidationOptionInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationOptionInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ValidationOptionInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ValidationOptionInfo) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ValidationOptionInfo) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationOptionInfo) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ValidationOptionInfo) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ValidationOptionInfo) SetDescription(v string) {
	o.Description = &v
}

func (o ValidationOptionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationOptionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableValidationOptionInfo struct {
	value *ValidationOptionInfo
	isSet bool
}

func (v NullableValidationOptionInfo) Get() *ValidationOptionInfo {
	return v.value
}

func (v *NullableValidationOptionInfo) Set(val *ValidationOptionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationOptionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationOptionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationOptionInfo(val *ValidationOptionInfo) *NullableValidationOptionInfo {
	return &NullableValidationOptionInfo{value: val, isSet: true}
}

func (v NullableValidationOptionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationOptionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


