/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the FileContentInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileContentInput{}

// FileContentInput struct for FileContentInput
type FileContentInput struct {
	// The new content of the file, sent as the raw request body. If not set, an empty file is created or the existing content is cleared.
	Content map[string]interface{} `json:"content,omitempty"`
	// The file content as a base-64 encoded data URI. If no content is provided, an empty is created or if an existing file is updated the file content is removed so that the file becomes empty. The content must be a SHA1 if the file mode is 160000 (gitlink).
	BinaryContent *string `json:"binary_content,omitempty"`
	// The file mode in octal format. Supported values are 100644 (regular file), 100755 (executable file), 120000 (symlink) and 160000 (gitlink). If unset, new files are created with file mode 100644 (regular file) and for existing files the existing file mode is kept.
	FileMode *int32 `json:"file_mode,omitempty"`
}

// NewFileContentInput instantiates a new FileContentInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileContentInput() *FileContentInput {
	this := FileContentInput{}
	return &this
}

// NewFileContentInputWithDefaults instantiates a new FileContentInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileContentInputWithDefaults() *FileContentInput {
	this := FileContentInput{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *FileContentInput) GetContent() map[string]interface{} {
	if o == nil || IsNil(o.Content) {
		var ret map[string]interface{}
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileContentInput) GetContentOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Content) {
		return map[string]interface{}{}, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *FileContentInput) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given map[string]interface{} and assigns it to the Content field.
func (o *FileContentInput) SetContent(v map[string]interface{}) {
	o.Content = v
}

// GetBinaryContent returns the BinaryContent field value if set, zero value otherwise.
func (o *FileContentInput) GetBinaryContent() string {
	if o == nil || IsNil(o.BinaryContent) {
		var ret string
		return ret
	}
	return *o.BinaryContent
}

// GetBinaryContentOk returns a tuple with the BinaryContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileContentInput) GetBinaryContentOk() (*string, bool) {
	if o == nil || IsNil(o.BinaryContent) {
		return nil, false
	}
	return o.BinaryContent, true
}

// HasBinaryContent returns a boolean if a field has been set.
func (o *FileContentInput) HasBinaryContent() bool {
	if o != nil && !IsNil(o.BinaryContent) {
		return true
	}

	return false
}

// SetBinaryContent gets a reference to the given string and assigns it to the BinaryContent field.
func (o *FileContentInput) SetBinaryContent(v string) {
	o.BinaryContent = &v
}

// GetFileMode returns the FileMode field value if set, zero value otherwise.
func (o *FileContentInput) GetFileMode() int32 {
	if o == nil || IsNil(o.FileMode) {
		var ret int32
		return ret
	}
	return *o.FileMode
}

// GetFileModeOk returns a tuple with the FileMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileContentInput) GetFileModeOk() (*int32, bool) {
	if o == nil || IsNil(o.FileMode) {
		return nil, false
	}
	return o.FileMode, true
}

// HasFileMode returns a boolean if a field has been set.
func (o *FileContentInput) HasFileMode() bool {
	if o != nil && !IsNil(o.FileMode) {
		return true
	}

	return false
}

// SetFileMode gets a reference to the given int32 and assigns it to the FileMode field.
func (o *FileContentInput) SetFileMode(v int32) {
	o.FileMode = &v
}

func (o FileContentInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileContentInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.BinaryContent) {
		toSerialize["binary_content"] = o.BinaryContent
	}
	if !IsNil(o.FileMode) {
		toSerialize["file_mode"] = o.FileMode
	}
	return toSerialize, nil
}

type NullableFileContentInput struct {
	value *FileContentInput
	isSet bool
}

func (v NullableFileContentInput) Get() *FileContentInput {
	return v.value
}

func (v *NullableFileContentInput) Set(val *FileContentInput) {
	v.value = val
	v.isSet = true
}

func (v NullableFileContentInput) IsSet() bool {
	return v.isSet
}

func (v *NullableFileContentInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileContentInput(val *FileContentInput) *NullableFileContentInput {
	return &NullableFileContentInput{value: val, isSet: true}
}

func (v NullableFileContentInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileContentInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


