/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ReviewerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewerInfo{}

// ReviewerInfo struct for ReviewerInfo
type ReviewerInfo struct {
	// The approvals of the reviewer as a map that maps the label names to the approval values (\"-2\", \"-1\", \"0\", \"+1\", \"+2\").
	Approvals map[string]string `json:"approvals,omitempty"`
	// This field is inherited from AccountInfo but is optional here if an unregistered reviewer was added by email. See add-reviewer for details.
	AccountId *int32 `json:"_account_id,omitempty"`
	Name *string `json:"name,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	Email *string `json:"email,omitempty"`
	SecondaryEmails []string `json:"secondary_emails,omitempty"`
	Username *string `json:"username,omitempty"`
	Avatars []AvatarInfo `json:"avatars,omitempty"`
	MoreAccounts *bool `json:"_more_accounts,omitempty"`
	Status *string `json:"status,omitempty"`
	Inactive *bool `json:"inactive,omitempty"`
	Deleted *bool `json:"deleted,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

// NewReviewerInfo instantiates a new ReviewerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewerInfo() *ReviewerInfo {
	this := ReviewerInfo{}
	return &this
}

// NewReviewerInfoWithDefaults instantiates a new ReviewerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewerInfoWithDefaults() *ReviewerInfo {
	this := ReviewerInfo{}
	return &this
}

// GetApprovals returns the Approvals field value if set, zero value otherwise.
func (o *ReviewerInfo) GetApprovals() map[string]string {
	if o == nil || IsNil(o.Approvals) {
		var ret map[string]string
		return ret
	}
	return o.Approvals
}

// GetApprovalsOk returns a tuple with the Approvals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetApprovalsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Approvals) {
		return map[string]string{}, false
	}
	return o.Approvals, true
}

// HasApprovals returns a boolean if a field has been set.
func (o *ReviewerInfo) HasApprovals() bool {
	if o != nil && !IsNil(o.Approvals) {
		return true
	}

	return false
}

// SetApprovals gets a reference to the given map[string]string and assigns it to the Approvals field.
func (o *ReviewerInfo) SetApprovals(v map[string]string) {
	o.Approvals = v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *ReviewerInfo) GetAccountId() int32 {
	if o == nil || IsNil(o.AccountId) {
		var ret int32
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetAccountIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *ReviewerInfo) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given int32 and assigns it to the AccountId field.
func (o *ReviewerInfo) SetAccountId(v int32) {
	o.AccountId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReviewerInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReviewerInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReviewerInfo) SetName(v string) {
	o.Name = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ReviewerInfo) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ReviewerInfo) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ReviewerInfo) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ReviewerInfo) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ReviewerInfo) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ReviewerInfo) SetEmail(v string) {
	o.Email = &v
}

// GetSecondaryEmails returns the SecondaryEmails field value if set, zero value otherwise.
func (o *ReviewerInfo) GetSecondaryEmails() []string {
	if o == nil || IsNil(o.SecondaryEmails) {
		var ret []string
		return ret
	}
	return o.SecondaryEmails
}

// GetSecondaryEmailsOk returns a tuple with the SecondaryEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetSecondaryEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.SecondaryEmails) {
		return nil, false
	}
	return o.SecondaryEmails, true
}

// HasSecondaryEmails returns a boolean if a field has been set.
func (o *ReviewerInfo) HasSecondaryEmails() bool {
	if o != nil && !IsNil(o.SecondaryEmails) {
		return true
	}

	return false
}

// SetSecondaryEmails gets a reference to the given []string and assigns it to the SecondaryEmails field.
func (o *ReviewerInfo) SetSecondaryEmails(v []string) {
	o.SecondaryEmails = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *ReviewerInfo) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *ReviewerInfo) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *ReviewerInfo) SetUsername(v string) {
	o.Username = &v
}

// GetAvatars returns the Avatars field value if set, zero value otherwise.
func (o *ReviewerInfo) GetAvatars() []AvatarInfo {
	if o == nil || IsNil(o.Avatars) {
		var ret []AvatarInfo
		return ret
	}
	return o.Avatars
}

// GetAvatarsOk returns a tuple with the Avatars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetAvatarsOk() ([]AvatarInfo, bool) {
	if o == nil || IsNil(o.Avatars) {
		return nil, false
	}
	return o.Avatars, true
}

// HasAvatars returns a boolean if a field has been set.
func (o *ReviewerInfo) HasAvatars() bool {
	if o != nil && !IsNil(o.Avatars) {
		return true
	}

	return false
}

// SetAvatars gets a reference to the given []AvatarInfo and assigns it to the Avatars field.
func (o *ReviewerInfo) SetAvatars(v []AvatarInfo) {
	o.Avatars = v
}

// GetMoreAccounts returns the MoreAccounts field value if set, zero value otherwise.
func (o *ReviewerInfo) GetMoreAccounts() bool {
	if o == nil || IsNil(o.MoreAccounts) {
		var ret bool
		return ret
	}
	return *o.MoreAccounts
}

// GetMoreAccountsOk returns a tuple with the MoreAccounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetMoreAccountsOk() (*bool, bool) {
	if o == nil || IsNil(o.MoreAccounts) {
		return nil, false
	}
	return o.MoreAccounts, true
}

// HasMoreAccounts returns a boolean if a field has been set.
func (o *ReviewerInfo) HasMoreAccounts() bool {
	if o != nil && !IsNil(o.MoreAccounts) {
		return true
	}

	return false
}

// SetMoreAccounts gets a reference to the given bool and assigns it to the MoreAccounts field.
func (o *ReviewerInfo) SetMoreAccounts(v bool) {
	o.MoreAccounts = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ReviewerInfo) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ReviewerInfo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ReviewerInfo) SetStatus(v string) {
	o.Status = &v
}

// GetInactive returns the Inactive field value if set, zero value otherwise.
func (o *ReviewerInfo) GetInactive() bool {
	if o == nil || IsNil(o.Inactive) {
		var ret bool
		return ret
	}
	return *o.Inactive
}

// GetInactiveOk returns a tuple with the Inactive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetInactiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Inactive) {
		return nil, false
	}
	return o.Inactive, true
}

// HasInactive returns a boolean if a field has been set.
func (o *ReviewerInfo) HasInactive() bool {
	if o != nil && !IsNil(o.Inactive) {
		return true
	}

	return false
}

// SetInactive gets a reference to the given bool and assigns it to the Inactive field.
func (o *ReviewerInfo) SetInactive(v bool) {
	o.Inactive = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *ReviewerInfo) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *ReviewerInfo) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *ReviewerInfo) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ReviewerInfo) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewerInfo) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ReviewerInfo) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *ReviewerInfo) SetTags(v []string) {
	o.Tags = v
}

func (o ReviewerInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Approvals) {
		toSerialize["approvals"] = o.Approvals
	}
	if !IsNil(o.AccountId) {
		toSerialize["_account_id"] = o.AccountId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.SecondaryEmails) {
		toSerialize["secondary_emails"] = o.SecondaryEmails
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Avatars) {
		toSerialize["avatars"] = o.Avatars
	}
	if !IsNil(o.MoreAccounts) {
		toSerialize["_more_accounts"] = o.MoreAccounts
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Inactive) {
		toSerialize["inactive"] = o.Inactive
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableReviewerInfo struct {
	value *ReviewerInfo
	isSet bool
}

func (v NullableReviewerInfo) Get() *ReviewerInfo {
	return v.value
}

func (v *NullableReviewerInfo) Set(val *ReviewerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewerInfo(val *ReviewerInfo) *NullableReviewerInfo {
	return &NullableReviewerInfo{value: val, isSet: true}
}

func (v NullableReviewerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


