/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the AccessSectionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessSectionInfo{}

// AccessSectionInfo struct for AccessSectionInfo
type AccessSectionInfo struct {
	// The permissions assigned on the ref of this access section as a map that maps the permission names to PermissionInfo entities.
	Permissions map[string]PermissionInfo `json:"permissions,omitempty"`
}

// NewAccessSectionInfo instantiates a new AccessSectionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessSectionInfo() *AccessSectionInfo {
	this := AccessSectionInfo{}
	return &this
}

// NewAccessSectionInfoWithDefaults instantiates a new AccessSectionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessSectionInfoWithDefaults() *AccessSectionInfo {
	this := AccessSectionInfo{}
	return &this
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *AccessSectionInfo) GetPermissions() map[string]PermissionInfo {
	if o == nil || IsNil(o.Permissions) {
		var ret map[string]PermissionInfo
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessSectionInfo) GetPermissionsOk() (map[string]PermissionInfo, bool) {
	if o == nil || IsNil(o.Permissions) {
		return map[string]PermissionInfo{}, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *AccessSectionInfo) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given map[string]PermissionInfo and assigns it to the Permissions field.
func (o *AccessSectionInfo) SetPermissions(v map[string]PermissionInfo) {
	o.Permissions = v
}

func (o AccessSectionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessSectionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullableAccessSectionInfo struct {
	value *AccessSectionInfo
	isSet bool
}

func (v NullableAccessSectionInfo) Get() *AccessSectionInfo {
	return v.value
}

func (v *NullableAccessSectionInfo) Set(val *AccessSectionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessSectionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessSectionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessSectionInfo(val *AccessSectionInfo) *NullableAccessSectionInfo {
	return &NullableAccessSectionInfo{value: val, isSet: true}
}

func (v NullableAccessSectionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessSectionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


