/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the GroupsInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupsInfo{}

// GroupsInfo struct for GroupsInfo
type GroupsInfo struct {
	EnableDeleteGroup *bool `json:"enable_delete_group,omitempty"`
}

// NewGroupsInfo instantiates a new GroupsInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupsInfo() *GroupsInfo {
	this := GroupsInfo{}
	return &this
}

// NewGroupsInfoWithDefaults instantiates a new GroupsInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupsInfoWithDefaults() *GroupsInfo {
	this := GroupsInfo{}
	return &this
}

// GetEnableDeleteGroup returns the EnableDeleteGroup field value if set, zero value otherwise.
func (o *GroupsInfo) GetEnableDeleteGroup() bool {
	if o == nil || IsNil(o.EnableDeleteGroup) {
		var ret bool
		return ret
	}
	return *o.EnableDeleteGroup
}

// GetEnableDeleteGroupOk returns a tuple with the EnableDeleteGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupsInfo) GetEnableDeleteGroupOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableDeleteGroup) {
		return nil, false
	}
	return o.EnableDeleteGroup, true
}

// HasEnableDeleteGroup returns a boolean if a field has been set.
func (o *GroupsInfo) HasEnableDeleteGroup() bool {
	if o != nil && !IsNil(o.EnableDeleteGroup) {
		return true
	}

	return false
}

// SetEnableDeleteGroup gets a reference to the given bool and assigns it to the EnableDeleteGroup field.
func (o *GroupsInfo) SetEnableDeleteGroup(v bool) {
	o.EnableDeleteGroup = &v
}

func (o GroupsInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupsInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EnableDeleteGroup) {
		toSerialize["enable_delete_group"] = o.EnableDeleteGroup
	}
	return toSerialize, nil
}

type NullableGroupsInfo struct {
	value *GroupsInfo
	isSet bool
}

func (v NullableGroupsInfo) Get() *GroupsInfo {
	return v.value
}

func (v *NullableGroupsInfo) Set(val *GroupsInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupsInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupsInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupsInfo(val *GroupsInfo) *NullableGroupsInfo {
	return &NullableGroupsInfo{value: val, isSet: true}
}

func (v NullableGroupsInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupsInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


