/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the IndexChangesInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexChangesInput{}

// IndexChangesInput struct for IndexChangesInput
type IndexChangesInput struct {
	// List of change-ids. When delete_missing is true, each entry must be in project~changeNumber format.
	Changes []string `json:"changes,omitempty"`
	// Delete changes which are missing in NoteDb from the index. This can be used to get rid of stale index entries. Possible values are true and false. By default set to false.
	DeleteMissing *bool `json:"delete_missing,omitempty"`
}

// NewIndexChangesInput instantiates a new IndexChangesInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexChangesInput() *IndexChangesInput {
	this := IndexChangesInput{}
	return &this
}

// NewIndexChangesInputWithDefaults instantiates a new IndexChangesInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexChangesInputWithDefaults() *IndexChangesInput {
	this := IndexChangesInput{}
	return &this
}

// GetChanges returns the Changes field value if set, zero value otherwise.
func (o *IndexChangesInput) GetChanges() []string {
	if o == nil || IsNil(o.Changes) {
		var ret []string
		return ret
	}
	return o.Changes
}

// GetChangesOk returns a tuple with the Changes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexChangesInput) GetChangesOk() ([]string, bool) {
	if o == nil || IsNil(o.Changes) {
		return nil, false
	}
	return o.Changes, true
}

// HasChanges returns a boolean if a field has been set.
func (o *IndexChangesInput) HasChanges() bool {
	if o != nil && !IsNil(o.Changes) {
		return true
	}

	return false
}

// SetChanges gets a reference to the given []string and assigns it to the Changes field.
func (o *IndexChangesInput) SetChanges(v []string) {
	o.Changes = v
}

// GetDeleteMissing returns the DeleteMissing field value if set, zero value otherwise.
func (o *IndexChangesInput) GetDeleteMissing() bool {
	if o == nil || IsNil(o.DeleteMissing) {
		var ret bool
		return ret
	}
	return *o.DeleteMissing
}

// GetDeleteMissingOk returns a tuple with the DeleteMissing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexChangesInput) GetDeleteMissingOk() (*bool, bool) {
	if o == nil || IsNil(o.DeleteMissing) {
		return nil, false
	}
	return o.DeleteMissing, true
}

// HasDeleteMissing returns a boolean if a field has been set.
func (o *IndexChangesInput) HasDeleteMissing() bool {
	if o != nil && !IsNil(o.DeleteMissing) {
		return true
	}

	return false
}

// SetDeleteMissing gets a reference to the given bool and assigns it to the DeleteMissing field.
func (o *IndexChangesInput) SetDeleteMissing(v bool) {
	o.DeleteMissing = &v
}

func (o IndexChangesInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexChangesInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Changes) {
		toSerialize["changes"] = o.Changes
	}
	if !IsNil(o.DeleteMissing) {
		toSerialize["delete_missing"] = o.DeleteMissing
	}
	return toSerialize, nil
}

type NullableIndexChangesInput struct {
	value *IndexChangesInput
	isSet bool
}

func (v NullableIndexChangesInput) Get() *IndexChangesInput {
	return v.value
}

func (v *NullableIndexChangesInput) Set(val *IndexChangesInput) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexChangesInput) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexChangesInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexChangesInput(val *IndexChangesInput) *NullableIndexChangesInput {
	return &NullableIndexChangesInput{value: val, isSet: true}
}

func (v NullableIndexChangesInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexChangesInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


