/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the CommonFileInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonFileInfo{}

// CommonFileInfo struct for CommonFileInfo
type CommonFileInfo struct {
	Status *string `json:"status,omitempty"`
	OldMode *int32 `json:"old_mode,omitempty"`
	NewMode *int32 `json:"new_mode,omitempty"`
	OldSha *string `json:"old_sha,omitempty"`
	NewSha *string `json:"new_sha,omitempty"`
	Binary *bool `json:"binary,omitempty"`
	OldPath *string `json:"old_path,omitempty"`
	LinesInserted *int32 `json:"lines_inserted,omitempty"`
	LinesDeleted *int32 `json:"lines_deleted,omitempty"`
	SizeDelta *int32 `json:"size_delta,omitempty"`
	Size *int32 `json:"size,omitempty"`
	DiffsTooExpensiveToCompute *bool `json:"diffs_too_expensive_to_compute,omitempty"`
}

// NewCommonFileInfo instantiates a new CommonFileInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonFileInfo() *CommonFileInfo {
	this := CommonFileInfo{}
	return &this
}

// NewCommonFileInfoWithDefaults instantiates a new CommonFileInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonFileInfoWithDefaults() *CommonFileInfo {
	this := CommonFileInfo{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CommonFileInfo) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CommonFileInfo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CommonFileInfo) SetStatus(v string) {
	o.Status = &v
}

// GetOldMode returns the OldMode field value if set, zero value otherwise.
func (o *CommonFileInfo) GetOldMode() int32 {
	if o == nil || IsNil(o.OldMode) {
		var ret int32
		return ret
	}
	return *o.OldMode
}

// GetOldModeOk returns a tuple with the OldMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetOldModeOk() (*int32, bool) {
	if o == nil || IsNil(o.OldMode) {
		return nil, false
	}
	return o.OldMode, true
}

// HasOldMode returns a boolean if a field has been set.
func (o *CommonFileInfo) HasOldMode() bool {
	if o != nil && !IsNil(o.OldMode) {
		return true
	}

	return false
}

// SetOldMode gets a reference to the given int32 and assigns it to the OldMode field.
func (o *CommonFileInfo) SetOldMode(v int32) {
	o.OldMode = &v
}

// GetNewMode returns the NewMode field value if set, zero value otherwise.
func (o *CommonFileInfo) GetNewMode() int32 {
	if o == nil || IsNil(o.NewMode) {
		var ret int32
		return ret
	}
	return *o.NewMode
}

// GetNewModeOk returns a tuple with the NewMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetNewModeOk() (*int32, bool) {
	if o == nil || IsNil(o.NewMode) {
		return nil, false
	}
	return o.NewMode, true
}

// HasNewMode returns a boolean if a field has been set.
func (o *CommonFileInfo) HasNewMode() bool {
	if o != nil && !IsNil(o.NewMode) {
		return true
	}

	return false
}

// SetNewMode gets a reference to the given int32 and assigns it to the NewMode field.
func (o *CommonFileInfo) SetNewMode(v int32) {
	o.NewMode = &v
}

// GetOldSha returns the OldSha field value if set, zero value otherwise.
func (o *CommonFileInfo) GetOldSha() string {
	if o == nil || IsNil(o.OldSha) {
		var ret string
		return ret
	}
	return *o.OldSha
}

// GetOldShaOk returns a tuple with the OldSha field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetOldShaOk() (*string, bool) {
	if o == nil || IsNil(o.OldSha) {
		return nil, false
	}
	return o.OldSha, true
}

// HasOldSha returns a boolean if a field has been set.
func (o *CommonFileInfo) HasOldSha() bool {
	if o != nil && !IsNil(o.OldSha) {
		return true
	}

	return false
}

// SetOldSha gets a reference to the given string and assigns it to the OldSha field.
func (o *CommonFileInfo) SetOldSha(v string) {
	o.OldSha = &v
}

// GetNewSha returns the NewSha field value if set, zero value otherwise.
func (o *CommonFileInfo) GetNewSha() string {
	if o == nil || IsNil(o.NewSha) {
		var ret string
		return ret
	}
	return *o.NewSha
}

// GetNewShaOk returns a tuple with the NewSha field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetNewShaOk() (*string, bool) {
	if o == nil || IsNil(o.NewSha) {
		return nil, false
	}
	return o.NewSha, true
}

// HasNewSha returns a boolean if a field has been set.
func (o *CommonFileInfo) HasNewSha() bool {
	if o != nil && !IsNil(o.NewSha) {
		return true
	}

	return false
}

// SetNewSha gets a reference to the given string and assigns it to the NewSha field.
func (o *CommonFileInfo) SetNewSha(v string) {
	o.NewSha = &v
}

// GetBinary returns the Binary field value if set, zero value otherwise.
func (o *CommonFileInfo) GetBinary() bool {
	if o == nil || IsNil(o.Binary) {
		var ret bool
		return ret
	}
	return *o.Binary
}

// GetBinaryOk returns a tuple with the Binary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetBinaryOk() (*bool, bool) {
	if o == nil || IsNil(o.Binary) {
		return nil, false
	}
	return o.Binary, true
}

// HasBinary returns a boolean if a field has been set.
func (o *CommonFileInfo) HasBinary() bool {
	if o != nil && !IsNil(o.Binary) {
		return true
	}

	return false
}

// SetBinary gets a reference to the given bool and assigns it to the Binary field.
func (o *CommonFileInfo) SetBinary(v bool) {
	o.Binary = &v
}

// GetOldPath returns the OldPath field value if set, zero value otherwise.
func (o *CommonFileInfo) GetOldPath() string {
	if o == nil || IsNil(o.OldPath) {
		var ret string
		return ret
	}
	return *o.OldPath
}

// GetOldPathOk returns a tuple with the OldPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetOldPathOk() (*string, bool) {
	if o == nil || IsNil(o.OldPath) {
		return nil, false
	}
	return o.OldPath, true
}

// HasOldPath returns a boolean if a field has been set.
func (o *CommonFileInfo) HasOldPath() bool {
	if o != nil && !IsNil(o.OldPath) {
		return true
	}

	return false
}

// SetOldPath gets a reference to the given string and assigns it to the OldPath field.
func (o *CommonFileInfo) SetOldPath(v string) {
	o.OldPath = &v
}

// GetLinesInserted returns the LinesInserted field value if set, zero value otherwise.
func (o *CommonFileInfo) GetLinesInserted() int32 {
	if o == nil || IsNil(o.LinesInserted) {
		var ret int32
		return ret
	}
	return *o.LinesInserted
}

// GetLinesInsertedOk returns a tuple with the LinesInserted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetLinesInsertedOk() (*int32, bool) {
	if o == nil || IsNil(o.LinesInserted) {
		return nil, false
	}
	return o.LinesInserted, true
}

// HasLinesInserted returns a boolean if a field has been set.
func (o *CommonFileInfo) HasLinesInserted() bool {
	if o != nil && !IsNil(o.LinesInserted) {
		return true
	}

	return false
}

// SetLinesInserted gets a reference to the given int32 and assigns it to the LinesInserted field.
func (o *CommonFileInfo) SetLinesInserted(v int32) {
	o.LinesInserted = &v
}

// GetLinesDeleted returns the LinesDeleted field value if set, zero value otherwise.
func (o *CommonFileInfo) GetLinesDeleted() int32 {
	if o == nil || IsNil(o.LinesDeleted) {
		var ret int32
		return ret
	}
	return *o.LinesDeleted
}

// GetLinesDeletedOk returns a tuple with the LinesDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetLinesDeletedOk() (*int32, bool) {
	if o == nil || IsNil(o.LinesDeleted) {
		return nil, false
	}
	return o.LinesDeleted, true
}

// HasLinesDeleted returns a boolean if a field has been set.
func (o *CommonFileInfo) HasLinesDeleted() bool {
	if o != nil && !IsNil(o.LinesDeleted) {
		return true
	}

	return false
}

// SetLinesDeleted gets a reference to the given int32 and assigns it to the LinesDeleted field.
func (o *CommonFileInfo) SetLinesDeleted(v int32) {
	o.LinesDeleted = &v
}

// GetSizeDelta returns the SizeDelta field value if set, zero value otherwise.
func (o *CommonFileInfo) GetSizeDelta() int32 {
	if o == nil || IsNil(o.SizeDelta) {
		var ret int32
		return ret
	}
	return *o.SizeDelta
}

// GetSizeDeltaOk returns a tuple with the SizeDelta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetSizeDeltaOk() (*int32, bool) {
	if o == nil || IsNil(o.SizeDelta) {
		return nil, false
	}
	return o.SizeDelta, true
}

// HasSizeDelta returns a boolean if a field has been set.
func (o *CommonFileInfo) HasSizeDelta() bool {
	if o != nil && !IsNil(o.SizeDelta) {
		return true
	}

	return false
}

// SetSizeDelta gets a reference to the given int32 and assigns it to the SizeDelta field.
func (o *CommonFileInfo) SetSizeDelta(v int32) {
	o.SizeDelta = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *CommonFileInfo) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *CommonFileInfo) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *CommonFileInfo) SetSize(v int32) {
	o.Size = &v
}

// GetDiffsTooExpensiveToCompute returns the DiffsTooExpensiveToCompute field value if set, zero value otherwise.
func (o *CommonFileInfo) GetDiffsTooExpensiveToCompute() bool {
	if o == nil || IsNil(o.DiffsTooExpensiveToCompute) {
		var ret bool
		return ret
	}
	return *o.DiffsTooExpensiveToCompute
}

// GetDiffsTooExpensiveToComputeOk returns a tuple with the DiffsTooExpensiveToCompute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonFileInfo) GetDiffsTooExpensiveToComputeOk() (*bool, bool) {
	if o == nil || IsNil(o.DiffsTooExpensiveToCompute) {
		return nil, false
	}
	return o.DiffsTooExpensiveToCompute, true
}

// HasDiffsTooExpensiveToCompute returns a boolean if a field has been set.
func (o *CommonFileInfo) HasDiffsTooExpensiveToCompute() bool {
	if o != nil && !IsNil(o.DiffsTooExpensiveToCompute) {
		return true
	}

	return false
}

// SetDiffsTooExpensiveToCompute gets a reference to the given bool and assigns it to the DiffsTooExpensiveToCompute field.
func (o *CommonFileInfo) SetDiffsTooExpensiveToCompute(v bool) {
	o.DiffsTooExpensiveToCompute = &v
}

func (o CommonFileInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonFileInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.OldMode) {
		toSerialize["old_mode"] = o.OldMode
	}
	if !IsNil(o.NewMode) {
		toSerialize["new_mode"] = o.NewMode
	}
	if !IsNil(o.OldSha) {
		toSerialize["old_sha"] = o.OldSha
	}
	if !IsNil(o.NewSha) {
		toSerialize["new_sha"] = o.NewSha
	}
	if !IsNil(o.Binary) {
		toSerialize["binary"] = o.Binary
	}
	if !IsNil(o.OldPath) {
		toSerialize["old_path"] = o.OldPath
	}
	if !IsNil(o.LinesInserted) {
		toSerialize["lines_inserted"] = o.LinesInserted
	}
	if !IsNil(o.LinesDeleted) {
		toSerialize["lines_deleted"] = o.LinesDeleted
	}
	if !IsNil(o.SizeDelta) {
		toSerialize["size_delta"] = o.SizeDelta
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.DiffsTooExpensiveToCompute) {
		toSerialize["diffs_too_expensive_to_compute"] = o.DiffsTooExpensiveToCompute
	}
	return toSerialize, nil
}

type NullableCommonFileInfo struct {
	value *CommonFileInfo
	isSet bool
}

func (v NullableCommonFileInfo) Get() *CommonFileInfo {
	return v.value
}

func (v *NullableCommonFileInfo) Set(val *CommonFileInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonFileInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonFileInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonFileInfo(val *CommonFileInfo) *NullableCommonFileInfo {
	return &NullableCommonFileInfo{value: val, isSet: true}
}

func (v NullableCommonFileInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonFileInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


