/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the CherryPickInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CherryPickInput{}

// CherryPickInput struct for CherryPickInput
type CherryPickInput struct {
	// Commit message for the cherry-pick change. If not set, the commit message of the cherry-picked commit is used.
	Message *string `json:"message,omitempty"`
	// Destination branch
	Destination *string `json:"destination,omitempty"`
	// 40-hex digit SHA-1 of the commit which will be the parent commit of the newly created change. If set, it must be a merged commit or a change revision on the destination branch.
	Base *string `json:"base,omitempty"`
	// Number of the parent relative to which the cherry-pick should be considered.
	Parent *int32 `json:"parent,omitempty"`
	// Notify handling that defines to whom email notifications should be sent after the cherry-pick. + Allowed values are NONE, OWNER, OWNER_REVIEWERS and ALL. + If not set, the default is ALL.
	Notify *NotifyHandling `json:"notify,omitempty"`
	// Additional information about whom to notify about the update as a map of recipient type to NotifyInfo entity.
	NotifyDetails map[string]NotifyInfo `json:"notify_details,omitempty"`
	// If true, carries reviewers and ccs over from original change to newly created one.
	KeepReviewers *bool `json:"keep_reviewers,omitempty"`
	// If true, the cherry-pick uses content merge and succeeds also if there are conflicts. If there are conflicts the file contents of the created change contain git conflict markers to indicate the conflicts.
	AllowConflicts *bool `json:"allow_conflicts,omitempty"`
	// The topic of the created cherry-picked change. If not set, the default depends on the source. If the source is a change with a topic, the resulting topic of the cherry-picked change will be {source_change_topic}-{destination_branch}.
	Topic *string `json:"topic,omitempty"`
	// If true, the cherry-pick succeeds also if the created commit will be empty. If false, a cherry-pick that would create an empty commit fails without creating the commit.
	AllowEmpty *bool `json:"allow_empty,omitempty"`
	// Map with key-value pairs that are forwarded as options to the commit validation listeners (e.g. can be used to skip certain validations). Which validation options are supported depends on the installed commit validation listeners.
	ValidationOptions map[string]string `json:"validation_options,omitempty"`
	// Cherry-pick is committed using this email address. Only the registered emails of the calling user are considered valid. Defaults to source commit's committer email if it is a registered email of the calling user, else defaults to calling user's preferred email.
	CommitterEmail *string `json:"committer_email,omitempty"`
}

// NewCherryPickInput instantiates a new CherryPickInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCherryPickInput() *CherryPickInput {
	this := CherryPickInput{}
	return &this
}

// NewCherryPickInputWithDefaults instantiates a new CherryPickInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCherryPickInputWithDefaults() *CherryPickInput {
	this := CherryPickInput{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CherryPickInput) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CherryPickInput) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CherryPickInput) SetMessage(v string) {
	o.Message = &v
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *CherryPickInput) GetDestination() string {
	if o == nil || IsNil(o.Destination) {
		var ret string
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetDestinationOk() (*string, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *CherryPickInput) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given string and assigns it to the Destination field.
func (o *CherryPickInput) SetDestination(v string) {
	o.Destination = &v
}

// GetBase returns the Base field value if set, zero value otherwise.
func (o *CherryPickInput) GetBase() string {
	if o == nil || IsNil(o.Base) {
		var ret string
		return ret
	}
	return *o.Base
}

// GetBaseOk returns a tuple with the Base field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetBaseOk() (*string, bool) {
	if o == nil || IsNil(o.Base) {
		return nil, false
	}
	return o.Base, true
}

// HasBase returns a boolean if a field has been set.
func (o *CherryPickInput) HasBase() bool {
	if o != nil && !IsNil(o.Base) {
		return true
	}

	return false
}

// SetBase gets a reference to the given string and assigns it to the Base field.
func (o *CherryPickInput) SetBase(v string) {
	o.Base = &v
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *CherryPickInput) GetParent() int32 {
	if o == nil || IsNil(o.Parent) {
		var ret int32
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetParentOk() (*int32, bool) {
	if o == nil || IsNil(o.Parent) {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *CherryPickInput) HasParent() bool {
	if o != nil && !IsNil(o.Parent) {
		return true
	}

	return false
}

// SetParent gets a reference to the given int32 and assigns it to the Parent field.
func (o *CherryPickInput) SetParent(v int32) {
	o.Parent = &v
}

// GetNotify returns the Notify field value if set, zero value otherwise.
func (o *CherryPickInput) GetNotify() NotifyHandling {
	if o == nil || IsNil(o.Notify) {
		var ret NotifyHandling
		return ret
	}
	return *o.Notify
}

// GetNotifyOk returns a tuple with the Notify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetNotifyOk() (*NotifyHandling, bool) {
	if o == nil || IsNil(o.Notify) {
		return nil, false
	}
	return o.Notify, true
}

// HasNotify returns a boolean if a field has been set.
func (o *CherryPickInput) HasNotify() bool {
	if o != nil && !IsNil(o.Notify) {
		return true
	}

	return false
}

// SetNotify gets a reference to the given NotifyHandling and assigns it to the Notify field.
func (o *CherryPickInput) SetNotify(v NotifyHandling) {
	o.Notify = &v
}

// GetNotifyDetails returns the NotifyDetails field value if set, zero value otherwise.
func (o *CherryPickInput) GetNotifyDetails() map[string]NotifyInfo {
	if o == nil || IsNil(o.NotifyDetails) {
		var ret map[string]NotifyInfo
		return ret
	}
	return o.NotifyDetails
}

// GetNotifyDetailsOk returns a tuple with the NotifyDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetNotifyDetailsOk() (map[string]NotifyInfo, bool) {
	if o == nil || IsNil(o.NotifyDetails) {
		return map[string]NotifyInfo{}, false
	}
	return o.NotifyDetails, true
}

// HasNotifyDetails returns a boolean if a field has been set.
func (o *CherryPickInput) HasNotifyDetails() bool {
	if o != nil && !IsNil(o.NotifyDetails) {
		return true
	}

	return false
}

// SetNotifyDetails gets a reference to the given map[string]NotifyInfo and assigns it to the NotifyDetails field.
func (o *CherryPickInput) SetNotifyDetails(v map[string]NotifyInfo) {
	o.NotifyDetails = v
}

// GetKeepReviewers returns the KeepReviewers field value if set, zero value otherwise.
func (o *CherryPickInput) GetKeepReviewers() bool {
	if o == nil || IsNil(o.KeepReviewers) {
		var ret bool
		return ret
	}
	return *o.KeepReviewers
}

// GetKeepReviewersOk returns a tuple with the KeepReviewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetKeepReviewersOk() (*bool, bool) {
	if o == nil || IsNil(o.KeepReviewers) {
		return nil, false
	}
	return o.KeepReviewers, true
}

// HasKeepReviewers returns a boolean if a field has been set.
func (o *CherryPickInput) HasKeepReviewers() bool {
	if o != nil && !IsNil(o.KeepReviewers) {
		return true
	}

	return false
}

// SetKeepReviewers gets a reference to the given bool and assigns it to the KeepReviewers field.
func (o *CherryPickInput) SetKeepReviewers(v bool) {
	o.KeepReviewers = &v
}

// GetAllowConflicts returns the AllowConflicts field value if set, zero value otherwise.
func (o *CherryPickInput) GetAllowConflicts() bool {
	if o == nil || IsNil(o.AllowConflicts) {
		var ret bool
		return ret
	}
	return *o.AllowConflicts
}

// GetAllowConflictsOk returns a tuple with the AllowConflicts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetAllowConflictsOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowConflicts) {
		return nil, false
	}
	return o.AllowConflicts, true
}

// HasAllowConflicts returns a boolean if a field has been set.
func (o *CherryPickInput) HasAllowConflicts() bool {
	if o != nil && !IsNil(o.AllowConflicts) {
		return true
	}

	return false
}

// SetAllowConflicts gets a reference to the given bool and assigns it to the AllowConflicts field.
func (o *CherryPickInput) SetAllowConflicts(v bool) {
	o.AllowConflicts = &v
}

// GetTopic returns the Topic field value if set, zero value otherwise.
func (o *CherryPickInput) GetTopic() string {
	if o == nil || IsNil(o.Topic) {
		var ret string
		return ret
	}
	return *o.Topic
}

// GetTopicOk returns a tuple with the Topic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetTopicOk() (*string, bool) {
	if o == nil || IsNil(o.Topic) {
		return nil, false
	}
	return o.Topic, true
}

// HasTopic returns a boolean if a field has been set.
func (o *CherryPickInput) HasTopic() bool {
	if o != nil && !IsNil(o.Topic) {
		return true
	}

	return false
}

// SetTopic gets a reference to the given string and assigns it to the Topic field.
func (o *CherryPickInput) SetTopic(v string) {
	o.Topic = &v
}

// GetAllowEmpty returns the AllowEmpty field value if set, zero value otherwise.
func (o *CherryPickInput) GetAllowEmpty() bool {
	if o == nil || IsNil(o.AllowEmpty) {
		var ret bool
		return ret
	}
	return *o.AllowEmpty
}

// GetAllowEmptyOk returns a tuple with the AllowEmpty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetAllowEmptyOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowEmpty) {
		return nil, false
	}
	return o.AllowEmpty, true
}

// HasAllowEmpty returns a boolean if a field has been set.
func (o *CherryPickInput) HasAllowEmpty() bool {
	if o != nil && !IsNil(o.AllowEmpty) {
		return true
	}

	return false
}

// SetAllowEmpty gets a reference to the given bool and assigns it to the AllowEmpty field.
func (o *CherryPickInput) SetAllowEmpty(v bool) {
	o.AllowEmpty = &v
}

// GetValidationOptions returns the ValidationOptions field value if set, zero value otherwise.
func (o *CherryPickInput) GetValidationOptions() map[string]string {
	if o == nil || IsNil(o.ValidationOptions) {
		var ret map[string]string
		return ret
	}
	return o.ValidationOptions
}

// GetValidationOptionsOk returns a tuple with the ValidationOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetValidationOptionsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.ValidationOptions) {
		return map[string]string{}, false
	}
	return o.ValidationOptions, true
}

// HasValidationOptions returns a boolean if a field has been set.
func (o *CherryPickInput) HasValidationOptions() bool {
	if o != nil && !IsNil(o.ValidationOptions) {
		return true
	}

	return false
}

// SetValidationOptions gets a reference to the given map[string]string and assigns it to the ValidationOptions field.
func (o *CherryPickInput) SetValidationOptions(v map[string]string) {
	o.ValidationOptions = v
}

// GetCommitterEmail returns the CommitterEmail field value if set, zero value otherwise.
func (o *CherryPickInput) GetCommitterEmail() string {
	if o == nil || IsNil(o.CommitterEmail) {
		var ret string
		return ret
	}
	return *o.CommitterEmail
}

// GetCommitterEmailOk returns a tuple with the CommitterEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CherryPickInput) GetCommitterEmailOk() (*string, bool) {
	if o == nil || IsNil(o.CommitterEmail) {
		return nil, false
	}
	return o.CommitterEmail, true
}

// HasCommitterEmail returns a boolean if a field has been set.
func (o *CherryPickInput) HasCommitterEmail() bool {
	if o != nil && !IsNil(o.CommitterEmail) {
		return true
	}

	return false
}

// SetCommitterEmail gets a reference to the given string and assigns it to the CommitterEmail field.
func (o *CherryPickInput) SetCommitterEmail(v string) {
	o.CommitterEmail = &v
}

func (o CherryPickInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CherryPickInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}
	if !IsNil(o.Base) {
		toSerialize["base"] = o.Base
	}
	if !IsNil(o.Parent) {
		toSerialize["parent"] = o.Parent
	}
	if !IsNil(o.Notify) {
		toSerialize["notify"] = o.Notify
	}
	if !IsNil(o.NotifyDetails) {
		toSerialize["notify_details"] = o.NotifyDetails
	}
	if !IsNil(o.KeepReviewers) {
		toSerialize["keep_reviewers"] = o.KeepReviewers
	}
	if !IsNil(o.AllowConflicts) {
		toSerialize["allow_conflicts"] = o.AllowConflicts
	}
	if !IsNil(o.Topic) {
		toSerialize["topic"] = o.Topic
	}
	if !IsNil(o.AllowEmpty) {
		toSerialize["allow_empty"] = o.AllowEmpty
	}
	if !IsNil(o.ValidationOptions) {
		toSerialize["validation_options"] = o.ValidationOptions
	}
	if !IsNil(o.CommitterEmail) {
		toSerialize["committer_email"] = o.CommitterEmail
	}
	return toSerialize, nil
}

type NullableCherryPickInput struct {
	value *CherryPickInput
	isSet bool
}

func (v NullableCherryPickInput) Get() *CherryPickInput {
	return v.value
}

func (v *NullableCherryPickInput) Set(val *CherryPickInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCherryPickInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCherryPickInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCherryPickInput(val *CherryPickInput) *NullableCherryPickInput {
	return &NullableCherryPickInput{value: val, isSet: true}
}

func (v NullableCherryPickInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCherryPickInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


