/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
	"fmt"
)

// ChangeEditIdentityType the model 'ChangeEditIdentityType'
type ChangeEditIdentityType string

// List of ChangeEditIdentityType
const (
	CHANGEEDITIDENTITYTYPE_AUTHOR ChangeEditIdentityType = "AUTHOR"
	CHANGEEDITIDENTITYTYPE_COMMITTER ChangeEditIdentityType = "COMMITTER"
)

// All allowed values of ChangeEditIdentityType enum
var AllowedChangeEditIdentityTypeEnumValues = []ChangeEditIdentityType{
	"AUTHOR",
	"COMMITTER",
}

func (v *ChangeEditIdentityType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ChangeEditIdentityType(value)
	for _, existing := range AllowedChangeEditIdentityTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ChangeEditIdentityType", value)
}

// NewChangeEditIdentityTypeFromValue returns a pointer to a valid ChangeEditIdentityType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewChangeEditIdentityTypeFromValue(v string) (*ChangeEditIdentityType, error) {
	ev := ChangeEditIdentityType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ChangeEditIdentityType: valid values are %v", v, AllowedChangeEditIdentityTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ChangeEditIdentityType) IsValid() bool {
	for _, existing := range AllowedChangeEditIdentityTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ChangeEditIdentityType value
func (v ChangeEditIdentityType) Ptr() *ChangeEditIdentityType {
	return &v
}

type NullableChangeEditIdentityType struct {
	value *ChangeEditIdentityType
	isSet bool
}

func (v NullableChangeEditIdentityType) Get() *ChangeEditIdentityType {
	return v.value
}

func (v *NullableChangeEditIdentityType) Set(val *ChangeEditIdentityType) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeEditIdentityType) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeEditIdentityType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeEditIdentityType(val *ChangeEditIdentityType) *NullableChangeEditIdentityType {
	return &NullableChangeEditIdentityType{value: val, isSet: true}
}

func (v NullableChangeEditIdentityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeEditIdentityType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

