/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the LabelTypeInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelTypeInfo{}

// LabelTypeInfo struct for LabelTypeInfo
type LabelTypeInfo struct {
	Values map[string]string `json:"values,omitempty"`
	DefaultValue *int32 `json:"default_value,omitempty"`
}

// NewLabelTypeInfo instantiates a new LabelTypeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelTypeInfo() *LabelTypeInfo {
	this := LabelTypeInfo{}
	return &this
}

// NewLabelTypeInfoWithDefaults instantiates a new LabelTypeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelTypeInfoWithDefaults() *LabelTypeInfo {
	this := LabelTypeInfo{}
	return &this
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *LabelTypeInfo) GetValues() map[string]string {
	if o == nil || IsNil(o.Values) {
		var ret map[string]string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelTypeInfo) GetValuesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Values) {
		return map[string]string{}, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *LabelTypeInfo) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]string and assigns it to the Values field.
func (o *LabelTypeInfo) SetValues(v map[string]string) {
	o.Values = v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *LabelTypeInfo) GetDefaultValue() int32 {
	if o == nil || IsNil(o.DefaultValue) {
		var ret int32
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelTypeInfo) GetDefaultValueOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *LabelTypeInfo) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given int32 and assigns it to the DefaultValue field.
func (o *LabelTypeInfo) SetDefaultValue(v int32) {
	o.DefaultValue = &v
}

func (o LabelTypeInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelTypeInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["default_value"] = o.DefaultValue
	}
	return toSerialize, nil
}

type NullableLabelTypeInfo struct {
	value *LabelTypeInfo
	isSet bool
}

func (v NullableLabelTypeInfo) Get() *LabelTypeInfo {
	return v.value
}

func (v *NullableLabelTypeInfo) Set(val *LabelTypeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelTypeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelTypeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelTypeInfo(val *LabelTypeInfo) *NullableLabelTypeInfo {
	return &NullableLabelTypeInfo{value: val, isSet: true}
}

func (v NullableLabelTypeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelTypeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


