/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ConsistencyProblemInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsistencyProblemInfo{}

// ConsistencyProblemInfo struct for ConsistencyProblemInfo
type ConsistencyProblemInfo struct {
	Status *ConsistencyProblemInfoStatus `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewConsistencyProblemInfo instantiates a new ConsistencyProblemInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsistencyProblemInfo() *ConsistencyProblemInfo {
	this := ConsistencyProblemInfo{}
	return &this
}

// NewConsistencyProblemInfoWithDefaults instantiates a new ConsistencyProblemInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsistencyProblemInfoWithDefaults() *ConsistencyProblemInfo {
	this := ConsistencyProblemInfo{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ConsistencyProblemInfo) GetStatus() ConsistencyProblemInfoStatus {
	if o == nil || IsNil(o.Status) {
		var ret ConsistencyProblemInfoStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsistencyProblemInfo) GetStatusOk() (*ConsistencyProblemInfoStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ConsistencyProblemInfo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ConsistencyProblemInfoStatus and assigns it to the Status field.
func (o *ConsistencyProblemInfo) SetStatus(v ConsistencyProblemInfoStatus) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ConsistencyProblemInfo) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsistencyProblemInfo) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ConsistencyProblemInfo) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ConsistencyProblemInfo) SetMessage(v string) {
	o.Message = &v
}

func (o ConsistencyProblemInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsistencyProblemInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableConsistencyProblemInfo struct {
	value *ConsistencyProblemInfo
	isSet bool
}

func (v NullableConsistencyProblemInfo) Get() *ConsistencyProblemInfo {
	return v.value
}

func (v *NullableConsistencyProblemInfo) Set(val *ConsistencyProblemInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableConsistencyProblemInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableConsistencyProblemInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsistencyProblemInfo(val *ConsistencyProblemInfo) *NullableConsistencyProblemInfo {
	return &NullableConsistencyProblemInfo{value: val, isSet: true}
}

func (v NullableConsistencyProblemInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsistencyProblemInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


