/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ValidationOptionInfos type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationOptionInfos{}

// ValidationOptionInfos struct for ValidationOptionInfos
type ValidationOptionInfos struct {
	ValidationOptions []ValidationOptionInfo `json:"validation_options,omitempty"`
}

// NewValidationOptionInfos instantiates a new ValidationOptionInfos object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationOptionInfos() *ValidationOptionInfos {
	this := ValidationOptionInfos{}
	return &this
}

// NewValidationOptionInfosWithDefaults instantiates a new ValidationOptionInfos object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationOptionInfosWithDefaults() *ValidationOptionInfos {
	this := ValidationOptionInfos{}
	return &this
}

// GetValidationOptions returns the ValidationOptions field value if set, zero value otherwise.
func (o *ValidationOptionInfos) GetValidationOptions() []ValidationOptionInfo {
	if o == nil || IsNil(o.ValidationOptions) {
		var ret []ValidationOptionInfo
		return ret
	}
	return o.ValidationOptions
}

// GetValidationOptionsOk returns a tuple with the ValidationOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationOptionInfos) GetValidationOptionsOk() ([]ValidationOptionInfo, bool) {
	if o == nil || IsNil(o.ValidationOptions) {
		return nil, false
	}
	return o.ValidationOptions, true
}

// HasValidationOptions returns a boolean if a field has been set.
func (o *ValidationOptionInfos) HasValidationOptions() bool {
	if o != nil && !IsNil(o.ValidationOptions) {
		return true
	}

	return false
}

// SetValidationOptions gets a reference to the given []ValidationOptionInfo and assigns it to the ValidationOptions field.
func (o *ValidationOptionInfos) SetValidationOptions(v []ValidationOptionInfo) {
	o.ValidationOptions = v
}

func (o ValidationOptionInfos) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationOptionInfos) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ValidationOptions) {
		toSerialize["validation_options"] = o.ValidationOptions
	}
	return toSerialize, nil
}

type NullableValidationOptionInfos struct {
	value *ValidationOptionInfos
	isSet bool
}

func (v NullableValidationOptionInfos) Get() *ValidationOptionInfos {
	return v.value
}

func (v *NullableValidationOptionInfos) Set(val *ValidationOptionInfos) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationOptionInfos) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationOptionInfos) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationOptionInfos(val *ValidationOptionInfos) *NullableValidationOptionInfos {
	return &NullableValidationOptionInfos{value: val, isSet: true}
}

func (v NullableValidationOptionInfos) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationOptionInfos) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


