/*
Gerrit Code Review REST API

The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server's REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gerritclient

import (
	"encoding/json"
)

// checks if the ParentInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParentInput{}

// ParentInput struct for ParentInput
type ParentInput struct {
	Parent *string `json:"parent,omitempty"`
	CommitMessage *string `json:"commit_message,omitempty"`
}

// NewParentInput instantiates a new ParentInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParentInput() *ParentInput {
	this := ParentInput{}
	return &this
}

// NewParentInputWithDefaults instantiates a new ParentInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParentInputWithDefaults() *ParentInput {
	this := ParentInput{}
	return &this
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *ParentInput) GetParent() string {
	if o == nil || IsNil(o.Parent) {
		var ret string
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParentInput) GetParentOk() (*string, bool) {
	if o == nil || IsNil(o.Parent) {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *ParentInput) HasParent() bool {
	if o != nil && !IsNil(o.Parent) {
		return true
	}

	return false
}

// SetParent gets a reference to the given string and assigns it to the Parent field.
func (o *ParentInput) SetParent(v string) {
	o.Parent = &v
}

// GetCommitMessage returns the CommitMessage field value if set, zero value otherwise.
func (o *ParentInput) GetCommitMessage() string {
	if o == nil || IsNil(o.CommitMessage) {
		var ret string
		return ret
	}
	return *o.CommitMessage
}

// GetCommitMessageOk returns a tuple with the CommitMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParentInput) GetCommitMessageOk() (*string, bool) {
	if o == nil || IsNil(o.CommitMessage) {
		return nil, false
	}
	return o.CommitMessage, true
}

// HasCommitMessage returns a boolean if a field has been set.
func (o *ParentInput) HasCommitMessage() bool {
	if o != nil && !IsNil(o.CommitMessage) {
		return true
	}

	return false
}

// SetCommitMessage gets a reference to the given string and assigns it to the CommitMessage field.
func (o *ParentInput) SetCommitMessage(v string) {
	o.CommitMessage = &v
}

func (o ParentInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParentInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Parent) {
		toSerialize["parent"] = o.Parent
	}
	if !IsNil(o.CommitMessage) {
		toSerialize["commit_message"] = o.CommitMessage
	}
	return toSerialize, nil
}

type NullableParentInput struct {
	value *ParentInput
	isSet bool
}

func (v NullableParentInput) Get() *ParentInput {
	return v.value
}

func (v *NullableParentInput) Set(val *ParentInput) {
	v.value = val
	v.isSet = true
}

func (v NullableParentInput) IsSet() bool {
	return v.isSet
}

func (v *NullableParentInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParentInput(val *ParentInput) *NullableParentInput {
	return &NullableParentInput{value: val, isSet: true}
}

func (v NullableParentInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParentInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


